### ISSUE TITLE
Incorrect fields showing/required for initial application

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#101]
When you indicate the application in an *initial* application, the validation will still error out sections that are not required for initial applicants.  If initial application is chosen, applicants are not required to complete Items 7, 9, 10 11 & 12 on the form 226, and items 6 & 7 on the form 226A.  That translates to -

For the online form, initial applicants are not required to answer: 
-    the questions under “Numbers of Workers with Disabilities” within the Employer Section, 
-    the entire Wage Data Section, 
-    the last question under #1 Add Work Site within the Work Sites & Employees Section, and 
-    the entire “#2 Add Employees” within the Work Sites & Employees Section

Ideally initial applicants wouldn’t see the questions/sections that are not required of them.

**Comment by binwang89** [comment]
Tested the 14c for an initial applicant for below not required fields and seems fixed now. 
•	the questions under “Numbers of Workers with Disabilities” within the Employer Section,
•	the entire Wage Data Section,
•	the last question under #1 Add Work Site within the Work Sites & Employees Section, and
•	the entire “#2 Add Employees” within the Work Sites & Employees Section
