### ISSUE TITLE
Mailing Address Option Missing

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#103]
Within the Employer Section, under the "Physical Address of Employer's Main Establishment" the option for "Mailing Address is different from Physical Address" is missing.  On the prototype, this option is a checkbox, and if checked, should open new fields for the employer's mailing address.

**Comment by simplyshang** [comment]
We need to add a checkbox below the address, and then if checked, repeat all the fields available to the Physical Address (including County):

![checkbox-for-mailing-address](https://cloud.githubusercontent.com/assets/1373592/20759426/e760a056-b6ea-11e6-85ef-107ff880f3c1.png)

**Comment by phirefly** [comment]
Confirmed
