### ISSUE TITLE
Inability to submit application even after all validation errors are addressed

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#105]
When a user goes through all validation responses, the application submit button is still greyed out

**Comment by klinden** [comment]
We need some more data on this one.

**Comment by klinden** [comment]
@MrMatt57 Can we take a look at the database and grab the saved view model for this application?

**Comment by MrMatt57** [comment]
I reset @jmmcnj account.  He was going to submit a fresh application and see if his issue still existed.

**Comment by jmmcnj** [comment]
I was able to submit the application and with help from Jeff was able to view it from an administrator perspective, so I think we can close this one out.  For historical purposes, seems it was mostly related to the fact that I did not have an email confirmation on that account and I had already gone halfway through an existing application before the email confirmation feature was implemented in the integration environment.
