### ISSUE TITLE
As an Applicant, I would like the ability to clear or restart my application from the landing page

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#106]
Descripition:
When an applicant logs in to an existing application, they should have the ability to hit a clear/restart my application button from the dashboard/landing page

FED - 1
BED - 2

Tasks:
- [x] Create link on the bottom of the landing page, that follows design/UX screenshots in the thread below
- [x] Action will ask "Are you Sure?", will clear out the application from the dashboard
- [ ] Backend - create delete application api endpoint, need to do the following: no new application id, mark attachments as "soft deleted", clear out data and state, clear out org membership - David 
- [x] Change button to say start new application
- [x] Follow UX guidance on verbiage and flow below...

Acceptance Criteria:
Considerations:
1. Refer comments below from Leslee and Liz for guidance and acceptance criteria

**Comment by oghaffari** [comment]
Please see #130 for more information.

**Comment by mmurthydol** [comment]
Would like to call out that this can only happen till the time Application is not submitted (Save is ok). Once submitted this feature must not be allowed.

**Comment by EStriegel** [comment]
**Functionality for this story -**  
User clicks "Clear all responses from the current application"
Pop up dialogue box asks user to confirm application clear
User clicks yes
Button changes to Start a New Application and application is blank

**Comment by phirefly** [comment]
Validated the frontend. Assigning to @mmurthydol for QA of backend item:
`Backend - create delete application api endpoint, need to do the following: no new application id, mark attachments as "soft deleted", clear out data and state, clear out org membership `

**Comment by mmurthydol** [comment]
Already verified this during code review.
