### ISSUE TITLE
As an applicant, I would like the instructions included in the Work Sites & Employee section so that I understand how to fill out the individual employee fields.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#108]
To implement page 36 of the prototype, "See details & instructions on calculating this information"

*Can we change the link to read "See detailed instructions on employee information"?

**Comment by phirefly** [comment]
Iceboxing for more general investigation about inserting instructions throughout online forms

**Comment by phirefly** [comment]
Closing because this is a dup of the general story.
