### ISSUE TITLE
As an applicant, I would like the example of employee information included in the Work Sites & Employee section so that I understand how to fill out the individual employee fields.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#109]
To implement page 36 of the prototype, "Show Me an Example"

**Edit by Leslee Sheu 11/19/17:**
See updated prototype --
https://preview.uxpin.com/672cf976db56fb446c1f954281636202590530cb#/pages/76425556/simulate/no-panels?mode=i

[prototype link edited by @simplyshang 11/20]

**Comment by phirefly** [comment]
@EStriegel will add a screenshot

**Comment by EStriegel** [comment]
![image](https://user-images.githubusercontent.com/19496579/28723680-8378a7fc-7385-11e7-86e9-244b0eb18ee6.png)

**Comment by EStriegel** [comment]
In the current example (screen shot attached), there is one employee and the information is a mix between the two employee examples on the paper forms.  We should show both examples with the correct employee information to align with paper form instructions.

![image](https://user-images.githubusercontent.com/19496579/28724000-9c11d2f6-7386-11e7-8b23-b115ece697ca.png)

**Comment by brendansudol** [comment]
question about this @EStriegel -- do you simply want to replace the image that currently there with the new one you posted above? thanks!

**Comment by EStriegel** [comment]
@brendansudol No, I'd like the image to still mirror the format that the employer is entering data into. The new image is from our paper form and just meant to provide the correct employee information that should be reflected in the example.  

However, now that I think about it, #210 is a story to rework the gray "wage data" box.  Probably don't need to work on this story until the ux re-design is done.  I'll add the dependency and move this story down under 210.

**Comment by ltsheu** [comment]
Updated prototype for this task: https://preview.uxpin.com/107df641f3eac499a1e03532bab2b062fbaecd4c#/pages/77134369/simulate/sitemap?mode=i

**Comment by simplyshang** [comment]
@ltsheu Please don't use that link. Here's the correct link: https://preview.uxpin.com/672cf976db56fb446c1f954281636202590530cb#/pages/76425556/simulate/no-panels?mode=i

**Comment by ltsheu** [comment]
@EStriegel  The sliding panel for Employee data examples has been implemented, and ready for your review.
https://dol-whd-section14c-int.aisdemos.com/#!/section/work-sites
