### ISSUE TITLE
As an applicant, I would like the name of the Work Site listed on the "#2 Add Employees" tab so that I can quickly know which work site I am adding employees under.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#110]
The "Name of Establishment / Work Site" field from the Add Work Site tab should appear  on the Add Employees tab where "Work Site Name" is on the below screenshot.

![image](https://cloud.githubusercontent.com/assets/19496579/20689013/5b051b0a-b591-11e6-9ed1-e88fccea7c5c.png)

**Comment by binwang89** [comment]
Tested 14c, please see screen shot for the test result. 
[GitHub issues_#110.docx](https://github.com/18F/dol-whd-14c/files/1188116/GitHub.issues_.110.docx)
