### ISSUE TITLE
As an applicant, I would like the form header to emphasize when the document was last saved so I feel confident the information I have entered will not be lost.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#111]
An update to the form header to reflect the below changes:

![image](https://cloud.githubusercontent.com/assets/19496579/20689224/2cc402dc-b592-11e6-8267-4bd579e0e367.png)

**Comment by mmurthydol** [comment]
Related to #112 as well. 

Need Ux specs and exact verbiage/placement. Do we need this info both at the top and bottom??

**Comment by phirefly** [comment]
Confirmed with @mmurthydol et al
