### ISSUE TITLE
As an applicant, I would like the form footer to emphasize when the document was last saved so I feel confident the information I have entered will not be lost.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#112]
The addition of the save time stamps to the bottom of the page:

![image](https://cloud.githubusercontent.com/assets/19496579/20689264/77c33b04-b592-11e6-806c-686c33aaca5f.png)

**Comment by mmurthydol** [comment]
Related to #111 as well. 

Need Ux specs and exact verbiage/placement. Do we need this info both at the top and bottom??

**Comment by phirefly** [comment]
Confirmed with @mmurthydol et al
