### ISSUE TITLE
Forgot Password Language

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#113]
A few typos in the Email Sent box.  Please update to:  "If the email address you entered matches our records, you will receive an email with a link to reset your password."

Also, is there different text we can use for the blue button?  "Email Reset Link" doesn't seem right.

![image](https://cloud.githubusercontent.com/assets/19496579/20689542/f2b600b6-b593-11e6-9e74-300217f3ffc3.png)

**Comment by rrefoy** [comment]
@EStriegel Can you prioritize this in the backlog if you want AIS to fix?

**Comment by MrMatt57** [comment]
Changed button text to "Send Email"

**Comment by MrMatt57** [comment]
https://github.com/AppliedIS/dol-whd-14c/commit/86496bd0c8cd9277ba986a1e49c2916b24f5b7eb

**Comment by phirefly** [comment]
Confirmed
