### ISSUE TITLE
Chore: Apply global delete confirmation style and functionality

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#115]
File upload delete functionality must conform globally to all delete/and other confirmation buttons.

Descripition:
Follow style of Delete confirmation alert from Style Guide and hook up front end delete function

Tasks:
- [ ] Create Styled delete confirmation alert (see style guide)
- [ ] hook up delete functionality after confirmation alert

Acceptance Criteria:  User clicks on delete button is shown confirmation notification and chooses delete or cancel, delete then kicks off delete functionality and cancel does not fire the delete functionality
Considerations:
1. Application Status
2. Role

**Comment by EStriegel** [comment]
@mmurthydol @binwang89 I believe this has been completed.  Please confirm and close, if so.

**Comment by phirefly** [comment]
@EStriegel and I will find all instances of the delete button and decide whether or not we need a global style treatment for all

**Comment by mmurthydol** [comment]
@EStriegel @wang please test when you can

**Comment by binwang89** [comment]
please see below screenshots for the delete confirmation message to the user. 

![image](https://user-images.githubusercontent.com/25330625/42427001-2824d648-82fa-11e8-84d6-34d0db612f7a.png)

![image](https://user-images.githubusercontent.com/25330625/42427055-6872c098-82fa-11e8-97aa-04fe80ecd182.png)

![image](https://user-images.githubusercontent.com/25330625/42427076-8858b926-82fa-11e8-8b08-474ebd8458f8.png)

![image](https://user-images.githubusercontent.com/25330625/42427108-b36a1344-82fa-11e8-9d69-7cac0e49d69a.png)

**Comment by mmurthydol** [comment]
@binwang89 Apart from the screenshots, what is the conclusion? Are these *all* the places where we have delete confirmation? How about in the admin dashboard where where we delete a user?
@PrabhakarThummalaDOL  FYI

**Comment by binwang89** [comment]
@mmurthydol @PrabhakarThummalaDOL  i posted all the screenshots to verify all popup message are the same for delete confirmation.  it looks the same to me.  I also checked the admin user page, i did not find the delete function.  I only found edit/view button. 

![image](https://user-images.githubusercontent.com/25330625/43139589-240ea6ce-8f20-11e8-9899-a93223512782.png)

**Comment by binwang89** [comment]
@mmurthydol @NathayaMDOL @PrabhakarThummalaDOL  the delete confirmation function looks good,however, it got 508 issue.  I have posted the same issue in another 508 bug already. The issue is after deleted the file, the tabbing key will jump to next text field but leave the delete confirmation box still open. 

![image](https://user-images.githubusercontent.com/25330625/43139801-b71c63ca-8f20-11e8-868e-882e8955d4ab.png)

**Comment by PrabhakarThummalaDOL** [comment]
@binwang89 @mmurthydol 
Michelle, a user can be deleted(soft delete) or disabled by using the check boxes from the Edit Account page. So there is no separate delete button/function available. Thanks.

**Comment by NathayaMDOL** [comment]
This issue has been fixed and included in #197

**Comment by binwang89** [comment]
Tested and looks good. Move to Done
