### ISSUE TITLE
Bug: Add radio buttons as seen in wireframes to productivity measure in Add Employees section in Work Sites and Employees

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#116]
if you go to add employee, at the productivity measure (not commensurate wage rate!) add radio buttons as seen in wirframe

![image](https://cloud.githubusercontent.com/assets/823055/20759320/9cbd40ea-b6ea-11e6-82d3-e6d66484d3c9.png)

**Comment by simplyshang** [comment]
The screenshot from the wireframe above has the Radio Buttons under the wrong label. Here's the correct view:

![add-employee-fix](https://cloud.githubusercontent.com/assets/1373592/20759638/753529a6-b6eb-11e6-8564-b2732863a2bf.png)

**Comment by phirefly** [comment]
Confirmed
