### ISSUE TITLE
As an Applicant, I want the ability to save and retrieve my application in progress so I can work on the form in more than one session.

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#12]
Descripition:
Applicant can save the application in draft while filling out the application, continue when logs back in, auto saves in n minutes (configurable) - last saved date time stamp.  Further Dashboard capabilities can be found in User STory #70 Session timeout will be encompassed in Security User STory #  Save in separate data store from submitted applications, Allowing user to do what they want in draft state, not enforce sequential completion.

Tasks:
- [x] Create logic to change button to continue versus start a new application on landing page
- [x] Implementation of save functions:
  auto-save, next section save
- [x] Implementation of Last saved date timestamp

Acceptance Criteria:  Applicant can save in draft state any time, autosave - during go to next section, autosave - every n minutes (configurable). Landing page will only have start or resume application.
Considerations:
1. Application Status : N/A
2. Role: Applicant

**Comment by rrefoy** [comment]
@jmmcnj can you confirm what work has begun on this? Liz seemed to think some had but it's not in the work for this sprint.

**Comment by jmmcnj** [comment]
I believe the team has done some work on this while putting together some back end functionality for the current in progress User STories.  Sometimes while your there under the hood it is easier to knock a few things out.  Are you and Liz grooming the backlog right now?

**Comment by rrefoy** [comment]
yeah, Liz did some prioritization and we added a few AC's for user stories that will most likely be worked on next sprint. Liz was asking how long some things would take in order to aid in prioritization. do we want to hold off on that until Monday or is that something AIS can internally discuss beforehand?

**Comment by jmmcnj** [comment]
yeah, lets hold off on estimation until Monday or we could have the team do a short amount of estimation on Friday if we have time left after the review/retro.  She should go ahead and prioritize anyway and really in the end if we discuss and estimate low then she just pulls more into the sprint.
