### ISSUE TITLE
Bug: Disable Application save on successful submission

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#120]
Save button should be disabled post Submit after successful submission

**Comment by binwang89** [comment]
Submit button is not working, can not be verified.

**Comment by binwang89** [comment]
Tested the 14c, if no error show on the "Review and Submit" Section, the  Submit 14(c) Certificate Submit button is enabled.

**Comment by jmmcnj** [comment]
@davoodharun can make pull request to replace after submission that button is replaced, need to have login workflow commited to have application status due to changes of login/dashboard, one to many applications per user

**Comment by binwang89** [comment]
tested it at INT site, it looks good
![image](https://user-images.githubusercontent.com/25330625/35643353-0af0d578-0694-11e8-9bdc-e5c719650fff.png)

**Comment by EStriegel** [comment]
Completed.  Moving to `Done`
