### ISSUE TITLE
Bug: Need to scrub entire web application (including front and admin sections) for funny characters in both normal text and validation text. Also, see burden statement at review and submit.

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#123]
typos/markup character issues in second question in government contracts within Employer section

**Comment by mgwalker** [comment]
@jmmcnj This refers to the things like "smart quotes" that get turned into weird unicode symbols, right?

**Comment by mgwalker** [comment]
I'm going to close this one as fixed by #225, but as folks use the site, if anyone finds specific places where weird characters are showing up, we can open fix stories for each of those.
