### ISSUE TITLE
As an Applicant, I would like to be able to have the option to clear out my existing application

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#130]
Descripition:
Need to wire up button to existing API call to allow applicant to clear existing application frm their dashboard

Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
- [ ] Task 4

Acceptance Criteria:
Considerations:
1. Application Status
2. Role

**Comment by oghaffari** [comment]
Incorporated into #106.
