### ISSUE TITLE
Issue with submitting an application, ended up not having an EIN associated

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#131]
@binwang89 This defect most likely doesn't exist. Please test with new login workflow. Please do not spend much time reproducing this. Good to touch base with whoever found the bug (Jason might have typed it up, not the founder of the bug).

REview this data and figure out hjow the application was started and progressed without and EIN

[
  {
    "propertyName": "EIN",
    "errorMessage": "'E I N' should not be empty.",
    "attemptedValue": null,
    "customState": null,
    "errorCode": "notempty_error",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "E I N",
      "propertyValue": null
    },
    "resourceName": "notempty_error"
  },
  {
    "propertyName": "Employer.ParentTradeName",
    "errorMessage": "'Parent Trade Name' should not be empty.",
    "attemptedValue": null,
    "customState": null,
    "errorCode": "notempty_error",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Parent Trade Name",
      "propertyValue": null
    },
    "resourceName": "notempty_error"
  },
  {
    "propertyName": "WIOA.WIOAWorkers[0].WIOAWorkerVerifiedId",
    "errorMessage": "'W I O A Worker Verified Id' must not be empty.",
    "attemptedValue": null,
    "customState": null,
    "errorCode": "notnull_error",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "W I O A Worker Verified Id",
      "propertyValue": null
    },
    "resourceName": "notnull_error"
  },
  {
    "propertyName": "WIOA.WIOAWorkers[1].WIOAWorkerVerifiedId",
    "errorMessage": "'W I O A Worker Verified Id' must not be empty.",
    "attemptedValue": null,
    "customState": null,
    "errorCode": "notnull_error",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "W I O A Worker Verified Id",
      "propertyValue": null
    },
    "resourceName": "notnull_error"
  },
  {
    "propertyName": "WIOA.WIOAWorkers[2].WIOAWorkerVerifiedId",
    "errorMessage": "'W I O A Worker Verified Id' must not be empty.",
    "attemptedValue": null,
    "customState": null,
    "errorCode": "notnull_error",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "W I O A Worker Verified Id",
      "propertyValue": null
    },
    "resourceName": "notnull_error"
  }
]

**Comment by mmurthydol** [comment]
Defer this defect till all login workflow is finished; Defect might get obsolete

**Comment by EStriegel** [comment]
The bug was pre-new login workflow.  Moving to `Closed`.
