### ISSUE TITLE
New user creation: password failure even when visuals show a valid password

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#132]
Per discussion with Madhu, there is likely a defect in the Identity Management code. The message and password validation don't seem be to correlating with each other. When trying password "DolTesting12345!", the visual tell me that the password is valid but the submission fails.

![14c-screen-2017-02-28a](https://cloud.githubusercontent.com/assets/11333/23467973/18c6cc44-fe65-11e6-8af4-edfb706404d0.png)

**Comment by mgwalker** [comment]
Does DOL/WHD have much leeway in the password requirements?  NIST just published a revision to 800-63 that updates its digital identity guidelines.  Among the recommendations is to *not* require specific character classes and to reject known-weak, low-entropy passwords (including those known to be compromised from previous breaches).  Something like [zxcvbn](https://github.com/dropbox/zxcvbn) pretty well meets the NIST recommendations.

Whatever the rules, we need to make sure they are the same on both the client side and the server side, so @phirefly's issue doesn't happen - that is, if the client says the password is good, the server better accept it too.  😛

**Comment by oghaffari** [comment]
See #157 for more context.

**Comment by phirefly** [comment]
Fwiw: my password that failed ended in `1!`. The one that worked ended in `5%`
