### ISSUE TITLE
New user creation: Confirmation email link does not work in IE, only in Chrome

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#133]
Indicated by Michelle W on dev: Confirmation email was not sent when creating a new user account

**Comment by phirefly** [comment]
When testing, I did get a confirmation email after about 10 minutes. I clicked on it and got to a page that loads, but is blank. Login still fails after that.

**Comment by phirefly** [comment]
Per https://dol-whd.slack.com/archives/14c/p1488477004000038, the issue with the confirmation email is that it doesn't work IE. It works in Chrome. Verified and logged in. https://dol-whd.slack.com/archives/14c/p1488477004000038. Updating the title of this bug.

**Comment by mmurthydol** [comment]
Actually, clicking on confirmation email link in IE (11.0.9600.18537) works for Michelle & doesn't work for Madhu/Raphy. 

Env: WHD DEV

**Comment by mmurthydol** [comment]
@binwang89 Could you please make sure that this defect is reproducible in the AIS environment? (QA/Int whichever is available to test on). Thanks!

**Comment by binwang89** [comment]
@mmurthydol tested it again,  the new account had been registered, but i did not get the confirmation link email for my external email address ( michellewang56589@yahoo.com),  However, I got the email for my internal email address (wang.bin@dol.gov) on Thursday.   Please see below screenshots: 
![image](https://user-images.githubusercontent.com/25330625/34969946-6f582446-fa3f-11e7-8344-467db787208a.png)
![image](https://user-images.githubusercontent.com/25330625/34969948-73fe35a8-fa3f-11e7-9cbd-e8cd3cc4fc3c.png)

**Comment by binwang89** [comment]
Based on my internal email address, I got the confirmation email and the link, I be able to use the link to login to the 14c application(IE or Chrome).

**Comment by mmurthydol** [comment]
Thanks @binwang89 . Closing this issue.
