### ISSUE TITLE
Email confirmation is not sent to email addresses external to DOL

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#134]
Environment: WHD DEV

User Account is created in the database although no indication is shown on the screen to that effect upon registering.

**Comment by mgwalker** [comment]
Once the vendor is able to get into the code and start working, it may be useful to combine this issue, #135, and #136 into a single one, depending on what the underlying problem is.

**Comment by mmurthydol** [comment]
Greg, #135 is unrelated to this issue.

#134, and #136 are not vendor related.
Michelle, see #136 for what needs to be done.

**Comment by oghaffari** [comment]
There may be error handling issues in the application, not sure.
