### ISSUE TITLE
Bug: Account successfully created message is not displayed when email confirmation fails

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#135]
Envrionment: WHD DEV

Although user account is created successfully, the message is not displayed due to failure in the email confirmation. 

- [x]  Ideally message should say "account successfully created. Confirmation email was not sent." or some similar verbiage. I  believe this extra message about confirmation email is not displayed in current implementation.
- [x] Set the user (as Deleted) if the transaction fails at creating the role for the user.

Dev: Is the failure causing an unhandled exception?

Causes for failure in email confirmation could be:
a) SMTP server settings (or server) not configured correctly - doesn't apply in the current situation.
b) email address external to DOL like @google.com - applies in the current situation & filed as a separate issue.

**Comment by mgwalker** [comment]
Need to understand if this is an issue with the application or with the email server.

Related to #136

**Comment by mmurthydol** [comment]
Greg, This issue is on the code/vendor side.  

1. Code creates the account successfully. 
2. Unhandled code fails when sending confirmation email (ex: SMTP service is down). 
3. As a result of failure, no message is displayed which leads the user to think account wasn't created.
4. User will continue creating the same/or different account without success in an endless loop (till the sending confirmation email feature is back up).

Resolution? Needs discussion. 
Some message must be displayed different from the normal case so the user knows to request a confirmation email and to report this issue through help desk channels.

**Comment by oghaffari** [comment]
Please see #134 for DOL-side of the issue.

**Comment by jmmcnj** [comment]
backend changes done by @dciceman need to test failure bubbling up to user and message displayed

**Comment by EStriegel** [comment]
@mmurthydol Please confirm this has been completed.

**Comment by mmurthydol** [comment]
@binwang89 : On the api server (QA environment) temporarily disable email (web.config SMTP settings - don't use the correct settings). And then create a new user. Does account created message show up?

Ideally message should say "account succesfully created. Confirmation email was not sent." I do not believe this extra message about confirmation email is not displayed currently.

**Comment by binwang89** [comment]
![image](https://user-images.githubusercontent.com/25330625/36870483-426e8b86-1d6d-11e8-91f1-3c1f416696af.png)

after i disabled the SMTP setting. i tried to registration a new user, i got above message.

**Comment by PrabhakarThummalaDOL** [comment]
@EStriegel @mmurthydol 
Below is the screenshot with a new message when email fails, please confirm the message verbiage is fine?

![image](https://user-images.githubusercontent.com/36516512/38951935-12b97fd8-4318-11e8-8d1f-6a8bb9ef965f.png)

**Comment by EStriegel** [comment]
@PrabhakarThummalaDOL @mmurthydol @binwang89 Please update the header from "Account has been created with an error" to "Account Creation Error".

**Comment by PrabhakarThummalaDOL** [comment]
@EStriegel @mmurthydol @binwang89 
I think we need to indicate the user that the Account has been created successfully, but failed to send email. Otherwise user might try to re-register with the same Id again. Please advise.

**Comment by PrabhakarThummalaDOL** [comment]
@mmurthydol 
_Set the user (as Deleted) if the transaction fails at creating the role for the user._
- To be discussed: User can be set as 'Deleted' when the transaction fails (at creating the role) - I think this is to enable the user to retry Registration. But system does not allow a user with the same emailid (unique). So setting the user as 'Deleted' is not helpful.

**Comment by mmurthydol** [comment]
reviewed code and UI.
