### ISSUE TITLE
Password reset email is not generated for external email addresses

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#136]
Environment: WHD DEV

Issue same as confirmation email not being generated for external email addresses

**Comment by mgwalker** [comment]
Need to understand if this is an issue with the application or with the email server.

**Comment by mmurthydol** [comment]
Greg, Correct! This issue is not for the vendor. At time Entry was made there was no other place to capture an issue.

Michelle, This issue needs to be tried on the non-vendor side (& eliminate SMTP/ email server issues) before escalating to the vendor.

**Comment by mgwalker** [comment]
Ah, okay!  I'm 100% okay with capturing those kinds of issues here if it's useful to you!  They're helpful on our side because they give us some visibility into what internal work y'all are doing, and that can be useful in sprint planning to make sure the vendor isn't doing things that WHD isn't ready to support just yet.  :)

**Comment by mmurthydol** [comment]
Greg, moving forwards these issues are being entered in DOL operation's internal issue tracking system (security configuration info => not public). As we work together, we'll keep each other in the loop regardless :)

**Comment by mgwalker** [comment]
Sounds good to me!

**Comment by mmurthydol** [comment]
Michelle, 

Need to create issue on GitLab. Email isn't allowed for external addresses currently.
Issue must be tested for both #134, #136 on DOL side after above issue is fixed.
In other words test whether Email confirmation and reset password emails are being sent to external addresses.

**Comment by binwang89** [comment]
@mmurthydol 
The issue has been created on GitLab. https://devopsweblv04.dol.gov/whd-dev/section-14c/issues/7

**Comment by oghaffari** [comment]
Internal email is not being generated, so could be an application issue or could be a DOL issue.
