### ISSUE TITLE
Application is writing unhandled errors to Server's event log

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#137]
Environment: WHD DEV

Application is missing global exception handling filter (does it need error logging support?)

**Comment by mgwalker** [comment]
Can you provide a sample of the kinds of errors?  That will help the vendor understand what's going on and come up with some ideas for how to address it.

**Comment by oghaffari** [comment]
Application does not seem to have a global error handler.

**Comment by mgwalker** [comment]
Superseded by #258, #259
