### ISSUE TITLE
As an Applicant, I would like to know the password complexity requirements when I am setting my password.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#157]

**Comment by mgwalker** [comment]
The API uses a customized `UserManager` implementation from ASP.NET Identity.  See the code here:  https://github.com/18F/dol-whd-14c/blob/master/DOL.WHD.Section14c.DataAccess/Identity/IdentityConfig.cs

The password requirements specified in the code here need to be made available in plain language as well so users now what their target is.  It looks like it uses [zxcvbn](https://github.com/dropbox/zxcvbn) as well, which does *not* have strict "complexity requirements," but rather uses some statistical techniques to determine whether a password is good enough.

**Comment by oghaffari** [comment]
Closed on contingency that the bug is resolved.
