### ISSUE TITLE
As a user, I can find support when running into technical issues with the application

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#160]
How this will be implemented will require additional discussion with the DOL team.
related to #156

Currently, mechanism is undetermined.  At a minimum, a phone number will be provided.

This story is for assistance before the error happens (page crash vs. error messaging on form elements)

**Comment by mmurthydol** [comment]
Vendor can have work hooking up help system/displaying technical support page. Needs definition.

**Comment by EStriegel** [comment]
Pending resolution re: WHD help desk issue.

**Comment by EStriegel** [comment]
This issue included in #156.  Moving to `Closed`
