### ISSUE TITLE
WHD Biz: As an Employer, I would like to receive an automated email confirming submission of my application.

### ISSUE THREAD

**Issue by oghaffari** [18F/dol-whd-14c#166]
Upon clicking the submit button, employer must receive an email confirming submission of application.

There will be specific language for this email confirmation provided by DOL, a generic "Your application was received on MM/DD/YYYY." will not suffice.

## Requirements
WHD to provide info:
- [x] email language /body
- [x] email subject line
- [ ] sent from what email address [no-reply email address?], 
- [ ] cc to anyone?
- [ ] email format: html or plain text?
- [ ] What to do if email is not delivered? exception from SMTP send (server down, etc.)??
- [ ] **Should consolidated application be sent as an attachment w/ this email? as an option?**  If so, need a story that has this story #166 as a blocker.
- [ ] Upon clicking the submit button, employer also receives a PDF download upon successful submission.

## Acceptance Criteria
- [ ] Email is sent per requirements above upon clicking of submit button (happy case)
- [ ] Application must be attached to the email (if it is a requirement) by clicking on a checkbox (if optional step) prior to clicking the submit button.
- [ ] In case of an application error on send, (a) error must be logged with the helpful subject "Email Send Failure: Employer" and details to include "Employer name, Id, date of failure" (b) SMTP failure notification/alert must be raised (obviously not through email) - event log? Splunk/SCOM like mechanism? DB2 SQL Job that monitors error DB for these errors? 
    TODO - Discuss with WHD/18F/AIS Devs.
         (i) which notification/alert mechanism from above?
        (ii)  What if email is sent and is undeliverable? Application doesn't know about it unless we check the "Sent From" emails. @EStriegel should we account for cases when email was sent but undelivered? If yes, after milestone 1? Need to write a story accordingly @binwang89 Question for Liz to follow up.

**Comment by EStriegel** [comment]
I will follow up re: email language.

**Comment by EStriegel** [comment]
The email subject line & body (pending approval from certification team & policy branch):

-----------
**Email Subject Line:**
Section 14(c) Online Application Submission

**Text for email body:**

To Whom It May Concern:

This email acknowledges receipt of the application for Special Minimum Wage Certificate, which was submitted via the Department of Labor Section 14(c) Online Certification Application and received in our office on XX/XX/XXXX.  A PDF copy of your submitted application is attached.  

The Wage and Hour Division makes every effort to review applications and make certificate decisions in a timely manner.  If you have an urgent issue, you may contact our office at (312) 596-7195.

This notice does not constitute a statement of compliance by the Department of Labor nor does it convey a good faith defense to the employer should violations of the Fair Labor Standards Act, the Walsh-Healey Public Contracts Act, the McNamara-O'Hara Service Contract Act, or the Contract Work Hours and Safety Standards Act occur.

Sincerely,

FLSA Certification Team

**Comment by phirefly** [comment]
@dciceman @mmurthydol My understanding is that this is in progress. If so, can we pull this into `In Progress`?

**Comment by EStriegel** [comment]
QA testing verified that an email confirming submission is sent/received.
