### ISSUE TITLE
As the WHD certification team, I would like to receive a confirmation email that an employer's application has been submitted

### ISSUE THREAD

**Issue by oghaffari** [18F/dol-whd-14c#168]
Please refer to #166 requirements/acceptance criteria to fulfill this story as well.

**REQUIREMENTS**
- [ ] The team email address should be configurable (web.config or DB - discuss) in the application in the event it needs to change. so also with the non varying part of the subject line
- [ ] Once user clicks on the submit button, asynchronoulsy/dynamically generated PDF could be stored on the file system along with corresponding entries in the DB (similar manner to how attachments are dealt with). An email must be sent to cert team with an attachment (dynamically generated PDF file). 
- [ ] A note must be made in the database that an email was generated and sent successfully (or not) to the cert team.
- [ ] The Employer's state should be included at the front of the email subject line.

The content of the email will be provided by DOL.
WHD to provide info:
- [x] email language /body
- [x] email subject line
- [ ] sent from what email address [no-reply@dol.gov], 
- [ ] cc to anyone?
- [ ] email format: html or plain text?
- [ ] What to do if email is not delivered? exception from SMTP send (server down, etc.)??

**Comment by EStriegel** [comment]
I will follow up re: email language (email subject line, email body, sent from what email address [no-reply email address?], cc to anyone?, html format or plain text?)

**Comment by binwang89** [comment]
we will put the accessibility disclaimer for #167.  I think we also need to put similar warning information in the email for internal certification team about the PDF file is not accessible. 

ACCESSIBILITY:
The PDF generated by the system won't be accessibility compliance and the system should warn the user by adding the accessibility disclaimer language.

**Comment by EStriegel** [comment]
@mmurthydol Note: We'd like the Employer's state to be included in the email subject line.

**Comment by mmurthydol** [comment]
@EStriegel format above looks fine.

**Comment by phirefly** [comment]
@dciceman @mmurthydol My understanding is that this is in progress. If so, can we pull this into `In Progress`?

**Comment by EStriegel** [comment]
QA testing verified that an email is sent/received.

@binwang89 @mmurthydol Leaving this story open until we have an email address to update config.

**Comment by jmmcnj** [comment]
completed
