### ISSUE TITLE
As an Employer, I would like to have the ability to view what I've uploaded.

### ISSUE THREAD

**Issue by oghaffari** [18F/dol-whd-14c#172]
This may have been built in, but there may be some bugs.

**Comment by binwang89** [comment]
@EStriegel @mmurthydol tested this function and the result:
1. you can click the file link to review the file. 
2. for milestone 1, we should only upload PDF file, but the system also allow docx and image file to be uploaded. 
3. you can't upload excel file, however, the system won't show any error message about it.

**Comment by binwang89** [comment]
PDF is done, close the story
