### ISSUE TITLE
As a WHD Security member AND an Employer, I would like to know that the files uploaded are secured.

### ISSUE THREAD

**Issue by oghaffari** [18F/dol-whd-14c#174]
This issue must be worked on after login workflow API is implemented (which will use ApplicationId and not EIN)

**Requirements**:
- [x]  Files uploaded must accessible only to the authenticated/authorized external users belonging to the same Employer. 
- [x]  Files upload/download API calls must not work from a browser unless external user fulfills authentication/authorization requirements from (1)
- [x] File needs to be encrypted.
- [x] Files uploaded by user must not be changed after application submission. (Note: Attachment upload and Submit)
- [x] Files uploaded by user must be available to user to view even after application submission. Is this a requirement? If so, is this a milestone 1 requirement? 
- [x] All Web methods (from all controllers not just (AttachmentController) that send "EIN" in its route or in [FromBody]/Post should replace their logic to check for authorization to prevent dictionary attacks. At the beginning of each method there should be a conditional check (a) does the authenticated user belong to SystemAdministrator role? (b) if not, does this authenticated userId associated with an employer && does the application Id belong to this employer? 
- [x] To repeat, all Controller methods need to observe this pattern above (Attachments, ApplicationSaveController, ApplicationSubmissionController, Any others?)

This story and #197 are related.
This story also relates to WHD internal JIRA story:  WC-1

**Acceptance Criteria**:
1) Meet requirements above

**Comment by mmurthydol** [comment]
AIS: WHD is working on this story. @binwang89 : Michelle, please note the acceptance criteria for the other tests.

**Comment by mgwalker** [comment]
Should the uploaded files be available from the web application at all?  I think it might be useful to list out when/how the files *should* be made available.  E.g., can an employer see their uploaded files only while they are working on their application?  Are the files completely unavailable from the web app once the application is submitted to WHD?  Things like that - could be helpful in building a robust solution.

**Comment by mmurthydol** [comment]
@mgwalker I thought I updated this story earlier today & I don't see my changes. I must have goofed up. Thanks for your comments. Will edit description again.

**Comment by mmurthydol** [comment]
@EStriegel This story needs to be split. (1) & (2) is for AIS. 
Rest is for WHD. WHD can discuss the other requirements internally. For now files will be kept forever till IT hears otherwise. TODO question: can employers view their files/attachments after submission? I believe the answer is yes. What they view will be only their initial submission.

**Comment by EStriegel** [comment]
@mmurthydol Correct - An applicant should be able to view their submitted application (form fields and all attachments) after submission.  This is a milestone 1 requirement.

**Comment by EStriegel** [comment]
@phirefly  @mmurthydol Does this still need to be split into two stories?  Or can it be closed?

**Comment by mmurthydol** [comment]
@dciceman Let's chat about this after wed 1/24  stand up. Files must be encrypted  - this requirement is not done I believe. All else I believe is done. Thanks!

**Comment by jmmcnj** [comment]
@dciceman will put in api check on status and deny api call if already submitted, this is the last action on this issue

**Comment by mgwalker** [comment]
With respect to file encryption in particular:

- Does OS-level whole-disk encryption not satisfy the requirement?  If not, why not?  Knowing that will help us understand what we need to do.
  - Who are we trying to prevent from reading these files?
  - How sensitive are the files being encrypted?  How damaging would it be to the government or to employers if the contents of these files were compromised?  If the risk is low, that simplifies the effort, but if the risk is high, this is a lot more complicated.

- How long must the files be accessible?  Are they irrelevant after a year, when new applications come in, or are they potentially important for several years?  (E.g., are there legal actions that could require accessing those files several years after they are submitted?)  Longterm encrypted storage is a hard problem and should ideally be left to systems designed specifically for that task.
  - You have to make sure the secret keys are stored in a way that they aren't going to be lost or accidentally overwritten over time.
  - You must have a plan for rotating the keys, in case they are compromised.

cc: @binwang89 @mmurthydol

**Comment by phirefly** [comment]
Assigning to @mmurthydol for QA

**Comment by mmurthydol** [comment]
@phirefly @EStriegel  Raphy/Liz, By default back end stories are already have QA before moved to awaiting acceptance from UI/business perspective. No need to assign back to me, please feel free to mark stories done in this case. Marking this done.
