### ISSUE TITLE
As a Vendor Developer, I need to setup Dev laptops to build 14C Phase1

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#179]
Vendor must also capture setup information/gotchas in a document.

A) Laptop OS/IIS/.Net: Vendor's choice based on the information from the 14C technical requirements.
1. Hardware/OS Requirements:   
1.1. Client browser side: Windows 7 Enterprise, Windows 10 Enterprise, IOS 10 
1.2. Server side: Windows Server 2012 R2, IIS 8.x, .Net 4.5.2/.Net 4.6, Web API 2.2.1 (latest for MVC 5 stack) 
B) Laptop browsers: Assuming development on a PC, IE 11/Latest Chrome. Latest MS Edge (optional, as time permits).
B) Software: Apart from above, VS2017 w/ latest update, DB2 Data Studio for DB2, PgAdmin for PostgreSQL when evaluating the existing application. 

Acceptance Criteria:
- [ ] Instructions Markdown on Dev Setup
- [x] All members of the vendor are setup following instructions
- [x] All members can build and run the 14c Application

**Comment by jmmcnj** [comment]
instructions completed for front end
instructions on backend may be changing

issue found - PR No. 251 related to issue #181 - if package wasnt installed locally it wouldnt build correctly, definitely with Jenkins build, resolved in PR shown above
