### ISSUE TITLE
As a vendor developer, I need to setup Web Server/s.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#180]
Vendor must setup WebServer.

**Steps**:
1) Setup Web Server (Integration/QA)
Specs: Windows Server 2012 R2, IIS 8.5.9, .Net 4.5.2/.Net 4.6, Web API 2.x (latest for MVC 5 stack). Web Deploy 3.6  

2) Content Switch/Load balancer: as in Phase 1. If content switch is not being setup, communicate with WHD/18F as to how machineKey, session related issues are tested/addressed.

**Acceptance Criteria**:
- [x]  Web server is setup and configured speifically with respect to the 14C application. (ex: https, application pools, settings, etc.).
- [x]  Provide documentation as to how the server was setup (in Azure Portal as well), including server configuration. Include scripts in source control rather than manual steps.
- [x] Provide documentation of machineKey, session, etc. related issues that crop up with Content Switch/Load Balancer.

**Comment by mmurthydol** [comment]
@klinden @binwang89 Regarding documentation of web server farm of issues: AIS to document all the Asp.Net/IIS settings that are needed for the web application to work with a web server farm. 
@binwang89 DOL Story to be generated to ensure work will be done on DOL sites based on documentation here. 

Examples of things to document so app can work on all web servers in a server farm: 
- [ ] machineKey needs to be the same. 
https://stackoverflow.com/questions/3855666/adding-machinekey-to-web-config-on-web-farm-sites
- [ ] viewstate validation (is this being used still?)
https://stackoverflow.com/questions/15886439/viewstate-validation-fails-in-web-farm-usual-suspects-eliminated
- [ ] what else?

Info provided will become part of DOL operations manual. Ideally references to script way of doing things is helpful.

**Comment by klinden** [comment]
@mmurthydol The "Specs" listed in bullet point number 1 in the original post are the only requirements for running the application. All the other "settings" will be specified as part of the build/deploy process which we will be providing as Jenkins scripts. As you mentioned, if you will be using a server farm all running instances of the application need to have the same machine key. The CI process will take care of setting this when it deploys the application. We are not using the viewstate so that is not an issue. I'm not aware of any other issues.

**Comment by mmurthydol** [comment]
@klinden Thanks Kyle.  CI taking care of machineKey sounds great. Am assuming you are using web.config based transformations (or something similar) for supporting different environments.

**Comment by klinden** [comment]
Yes, IIS Web Deploy allows you to patch in values for all the configuration settings in the web.config file.

**Comment by klinden** [comment]
@mmurthydol Are you ok with moving this story along to Review/QA?

**Comment by jmmcnj** [comment]
need to review documentation to finalize/close
