### ISSUE TITLE
As a vendor developer, I will implement side-by-side execution of AngularJS & Angular 4 pages.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#185]
**side-by-side definition:** 
(a) Existing Angular 1/AngularJS pages will *not* be modified and continue to work.
(b) New pages written in Angular 4 (Angular 2 not ideal needs discussion) will also work.
(c) Existing AngularJS components are not expected to be modified/upgraded to work with Angular 4 and vice versa. 
(d) Ensure that AngularJS doesn't have any problems with Angular 4 pages that use Typescript. 

**Tasks**
1) Review the links below in that order: Again, please reread requirements (a) & (b) above. If not reading documentation carefully, might need to ignore sections where AngularJS pages/components are modified (appropriate only for (c) or when rewriting/migrating AngularJS pages).

https://hackernoon.com/angular-v4-hybrid-upgrade-application-73d5afba1e01
https://angular.io/guide/upgrade
https://blog.thoughtram.io/angular/2015/10/24/upgrading-apps-to-angular-2-using-ngupgrade.html

2) Provide your thoughts to WHD whether we are on the same page, whether scope of work is larger than expected, whether (c) must be done based on hackernoon.com link.  Please note the Typescript requirement (d) above.

3) Add Angular upgrade module to the project based on links above. Angular 1 and 4 can coexist when using the Angular upgrade module. 

4) Write a new Angular 4 Typescript "Hello World Angular" page.  

**Acceptance Criteria**
i) Demonstrate existing AngularJS (v1) page/s work correctly.
ii) Demonstrate the new "Hello World Angular" Angular 4 page with Typescript works correctly as well.
iii) Document steps involved.

**Comment by mmurthydol** [comment]
Awesome Brendan :)

**Comment by brendansudol** [comment]
I believe this is done and can be closed

**Comment by mmurthydol** [comment]
@brendansudol I assigned the stories to you for tracking purposes yesterday but realize technical work was already done. We'll discuss next steps in today's meeting before closing all the "un-closed" stories you have already finished. Thanks!
