### ISSUE TITLE
As an application/technical architect, I would like the application to log Application Activity

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#188]
All application activity must be logged to an application activity log. 
Vendor must request requirements from DOL prior to working on this story (ex: Cloud? Log4Net? etc.)

**Requirements**
There are two aspects to this story:
1) Server side: 
- [x] TODO Needs Discussion on implementation (WHD/18F/AIS). related to #187
- [x] Implement [LogApiRequest] attribute 
Override API methods to log API route, action, parameters, and a description. Use the solution approach provided in link below. Apply the Logging attribute at the base controller class level. In other words all controller actions are logged. 
https://stackoverflow.com/questions/24318061/net-web-api-add-logging.
https://www.codeproject.com/articles/1028416/restful-day-sharp-request-logging-and-exception-ha

- [x] Activity logs must be written to a DB (separate from error logs). 
- [x] Activity logs must be written to a file when DB isn't available.
- [x] Activity logs must write to event log (*one* error/hour), upon error (ex:  DB/file system errors).
  -- NLog doesn't seem to work with DB2? But works with PostgreSQL/SQL Server. 
  -- Talk with AIS/18F about other options (log4net doesn't seem to be an option).
  -- Cloud API OK with AIS not with WHD
- [x] Activity logging must be asynchronous. Please refer to configuration guidelines below:
http://deep-depth.blogspot.com/2014/01/net-low-latency-logging-part-2-nlog.html
- [x] Complete unit tests to cover >90% code
2) Client side: use Google Analytics (DOL needs to figure out licensing issues when exceeding usages/month). Might have been captured as a separate story.

**Acceptance Criteria**:
- [ ] Client Side: Add Google Analytics for front end, show GA logs, drop in integration js
- [ ] Server Side: Refer to requirements above.

**Comment by jmmcnj** [comment]
Unit tests are not completed, need to complete out unit tests, version differences between JSON serializer package and web api project
