### ISSUE TITLE
As a contract owner (18F/WHD), I need access to vendor's servers.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#189]
14.3.1.3.2. The vendor must provide access to 18F/WHD personnel to all servers, tools (including source control, Jenkins, issue tracking if any)  used by the vendor for 14c application development. 

This access will allow:
(a) contract owners to help install/configure/troubleshoot server software esp. in the initial phases of project.
(b) contract owners to mirror server install/configuration in DOL environment (along with vendor provided documentation.

Acceptance Criteria:
- [x] Direct access to tier (QA environment) servers and Jenkins server (access granted to Greg Walker, Madhu and Michele Wang)
- [x] Azure Portal access to look at Azure/VM settings. Read only access is fine.

**Comment by mmurthydol** [comment]
@klinden @davoodharun Kyle/Harun wondering what firewall issues you might have configured at AIS to the Azure VM images? ex: Did you have to unblock outbound TCP port 3389? etc. Also missing credential info for Azure Portal to look at Azure/VM settings.

**Comment by klinden** [comment]
@mmurthydol The Azure VMs by default are setup to allow inbound traffic on port 3389 for RDP connections. Once we get the code deployed we'll also need to open up port 80 inbound as well. Looping in @jmmcnj for access to the Azure portal. He'll have to look into setting you up with an account as that uses Microsoft accounts not shared credentials.

**Comment by jmmcnj** [comment]
I dont think we are providing any access directly to Azure for any folks outside of AIS, given this is one of our internal cloud environments, why is access needed for @mmurthydol ?

**Comment by mgwalker** [comment]
Seconding @jmmcnj's question.  We can share configuration information without having to get direct government access to AIS's infrastructure.

**Comment by mmurthydol** [comment]
@jmmcnj Configuration information is fine - was  a convenience factor request but not at the expense of your inconvenience.

**Comment by jmmcnj** [comment]
actually just spoke to our administrator, he says I should not be so stingy, pretty easy for us to give @mmurthydol a read-only account and lock it down to the Resource Group inside the Cloud tenant, so you can see everything, that should probably be the ideal scenario

**Comment by mmurthydol** [comment]
@jmmcnj That sounds awesome and much easier to get a good picture! Kudos to all :)

**Comment by klinden** [comment]
@mmurthydol Your account is all setup. I will send you your credentials.
