### ISSUE TITLE
As an employer (or a user of the application), I expect consistent input validation across all pages

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#192]
Currently input validation is not implemented for all input creating a confusing effect to the user.
Ensure that validation is 508 compliant, responsive, and conforms to DOL web development guidelines.

**Comment by phirefly** [comment]
Details to be added in 9/21 meeting.

**Comment by brendansudol** [comment]
Can you provide an example of a place that should have input validation and currently does not? Many thanks

**Comment by mmurthydol** [comment]
@brendansudol Don't have one offhand but thinking that if you get to the submission page and click submit, the validation summary control provides all the existing validation. I believe there is a document that @EStriegel uploaded (part of a related story) that lists all the validation that needs to exist. Will need to correlated these two to find the work. If all of this is derailing you from other work you have, we can reprioritize. @binwang89 can also help track this document. Thanks!

**Comment by binwang89** [comment]
@brendansudol @mmurthydol @EStriegel  i have the excel file that Liz provided, when I tested the 14c application, i have marked the error field with highlight.  Please see attached file. 
[14c.Form.Requirements.Logic_07312017.xlsx](https://github.com/18F/dol-whd-14c/files/1338194/14c.Form.Requirements.Logic_07312017.xlsx)

**Comment by EStriegel** [comment]
Validation implemented for milestone 1.  Closed.
