### ISSUE TITLE
As a user, I am able to submit an application without uniqueness required on EIN number

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#199]
- [x] Remove ein uniqueness constraint. Already done in C# code by @dciceman.

**Comment by mmurthydol** [comment]
@dciceman I believe the uniqueness constraint was being enforced through C# code that was removed when we were working together a couple of sprints ago.  Could you please verify items 2 & 3 in the description? Then please mark this story done so Steve can proceed with his story. Thanks!
