### ISSUE TITLE
As a system, I can scan uploaded files for viruses

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#201]
Not a vendor story. DOL internal issue.

**Comment by phirefly** [comment]
Noted: ATO considerations around this?

**Comment by binwang89** [comment]
Security : Ensure file system for uploaded attachments is secure through https.

**Comment by mmurthydol** [comment]
No work needed on Vendor's part. This issue is captured from a business perspective and fulfilled by DOL.

**Comment by EStriegel** [comment]
Closing in favor of #427
