### ISSUE TITLE
Disable "Renewal Application" radio button when renewals are not supported

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#202]
Application Info -> What type of application is this? Renewal Application radio button should be disabled.

**Comment by mmurthydol** [comment]
@EStriegel Liz, Could you please confirm that renewals are not supported in milestone 1. If so, could you please move this to the backlog? Thanks! Madhu

**Comment by EStriegel** [comment]
@mmurthydol Renewal applications are supported in milestone 1.  About 90% of all applications received by WHD are renewal applications.  Happy to discuss if you have questions.

**Comment by binwang89** [comment]
In Milestone1 Data will not pre-populated for renewal, so we close the issue.
