### ISSUE TITLE
As a user I would like application to support 2FA to feel comfortable about security hardness of the system

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#203]
Backend implementation of 2FA following links below and discussion between @dciceman and @mmurthydol.  Identity Access Management implementation must support Two Factor Authentication (2FA) through email (required) and SMS (required if there isn't a need to purchase software to implement).

**Note: 18F/Vendor:**
- [x] This story is needed to fulfill security ATO requirements. 
- [x] 2FA implementation must support API call to resend verification code (needed by UI).
- [x] Use implementation from links below.

**Implementation code related links for vendor:** Please note code samples. Do not use SW (cloud or not that needs to be purchased, esp. without approval from WHD/18F. Also please note Requirements above). 

https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/two-factor-authentication-using-sms-and-email-with-aspnet-identity

https://www.hanselman.com/blog/AddingTwoFactorAuthenticationToAnASPNETApplication.aspx

**Comment by mmurthydol** [comment]
implemented by #418. Hence closing this.

**Comment by mgwalker** [comment]
![](https://i.imgur.com/B5Avc1V.gif)
