### ISSUE TITLE
As an application/technical architect, I would like to remove the EIN from Registration page to fulfill security ATO requirements.

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#205]
Fulfilling this story involves changes to UI as well as to identity management API. 
- [ ]  Remove EIN, its label, and may be associated verbiage from login page. Disconnect the identity management logic that updates EIN as part of registration process.

2) Add EIN & its label to Employer tab. Use the disconnected logic (API + EF) on this page to save and eventually write to the database on Submit in a manner similar to other fields on the form. 
WHD will provide EIN placement info on the employment tab.

Related to user story #203 for login page.
As a user I would like application to support 2FA to feel comfortable about security hardness of the system.

**Comment by mmurthydol** [comment]
@EStriegel please provide EIN placement /other UI info for EIN on the Employer tab. Thanks!

**Comment by EStriegel** [comment]
Created story #214 for new EIN placement.

**Comment by mmurthydol** [comment]
This story is automatically obsolete with the new proposed login registration workflow. See epic #339
Ensure EIN uniqueness constraint is removed internally in the DB.
