### ISSUE TITLE
As a user I need to see password changed message upon changing password

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#206]

**Comment by simplyshang** [comment]
Looked at during UX Grooming session on 10/30; functionality is currently present, so moving to review for Sprint 3.

**Comment by EStriegel** [comment]
Bug preventing acceptance - story #472

**Comment by EStriegel** [comment]
Typo in password changed message:

![image](https://user-images.githubusercontent.com/19496579/34416457-92b9778c-ebc1-11e7-801b-3f1fd33e7cca.png)
