### ISSUE TITLE
Logout click does not work. Testing failed by using two browser sessions.

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#207]
Logout click does not work.  Open two browser sessions (say two tabs). Logout from one. Continuing work from the other must show a login page.

**Comment by mmurthydol** [comment]
@binwang89 Michelle, can you try this one in our WHD Dev environment please? Looks like this works fine on the AIS server. Thanks

**Comment by binwang89** [comment]
@mmurthydol just tested on DOL DEV environment,  the logout is not working.

**Comment by jmmcnj** [comment]
passed tests with IE 11+ and Chrome
