### ISSUE TITLE
As an application/technical architect, I would like the web application follow the DOL Web standard and UI guidelines

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#208]
sample application http://savingmatters.opadev.dol.gov/
Here is a link to the template files http://dolcontentdev.opadev.dol.gov/homepage/agency-template/DOL-Agency-Template-with-2ndLevel.zip

**Comment by brendansudol** [comment]
The URL to the template files zip does not work for me (cc: @binwang89)

**Comment by binwang89** [comment]
@mgwalker I sent the zip file to you, could you share with @brendansudol

**Comment by mmurthydol** [comment]
@brendansudol My understanding is all of the above, in the preference order you laid out. The zip file contains the header/footer templates as well as the styles that DOL enforces. 

A couple of things not mentioned above: 
1) Images used must be standardized (a) use DOL image from zip file if available (b) use 18f standards where not
2) Breadcrumbs on every page. (DOL site might have an example). Placement of the breadcrumb - your best guess & it can be moved later if UX  folks have a different idea. Even if you can't get to this, your thoughts would be helpful.

**Comment by jmmcnj** [comment]
@mmurthydol is this one ok to be closed out?

**Comment by mmurthydol** [comment]
@jmmcnj This needs to be reviewed in one of the AIS envrionments along with @davoodharun @binwang89

**Comment by binwang89** [comment]
All footer links must be displayed as seen in https://www.savingmatters.dol.gov/
 Footer display must be identical to what is seen on the link above (attachment provided for convenience). 
![image](https://user-images.githubusercontent.com/25330625/31791769-b65da016-b4e7-11e7-9d61-3bb7e61984c1.png)

**Comment by ltsheu** [comment]
Footer updated with Pull Request #321. Moving this back to Review/QA.

**Comment by jmmcnj** [comment]
promoting to EPIC, add dependent stories that will bridge the gap from existing today to DOL templates/standards

**Comment by binwang89** [comment]
Please download this zip file, http://dolcontentdev.opadev.dol.gov/homepage/agency-template/DOL-Agency-Template-with-2ndLevel-new.zip
It will looks like this, http://dolcontentdev.opadev.dol.gov/homepage/agency-template/DOL-Agency-Template-with-2ndLevel-new/index.htm

**Comment by ltsheu** [comment]
I have created a User Story to address the Header/Footer template issues. #349
