### ISSUE TITLE
Employer Section - Addition of EIN Question

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#214]
- [ ] [EIN Addition to Screen.pdf](https://github.com/18F/dol-whd-14c/files/1263967/EIN.Addition.to.Screen.pdf)
- [ ] EIN should not be pre-populated 
- [ ] When user enters EIN (a) EIN could be the same as entered on Employer Registration Page (b) not the same.  @EStriegel what should happen in case of (b)? If an update is expected to be allowed by  business, it could be allowed as long as the cert# EIN# Legal Employer Name Address combo is unique. If not an error will need to be thrown.  I would also suggest we seek user confirmation that data is about to be updated prior to making any actual updates.
- [ ] This page also contains employer's legal name (& may be address?). @EStriegel same question about behavior as above. We will need to call out all the fields. 

@EStriegel @phirefly FYI.  If we want to decrease scope, we would prepopulate the EIN, & other fields that were already entered in the employer registration page.

**Comment by mgwalker** [comment]
Accessibility acceptance criteria:
- [ ] EIN text box can be reached by keyboard navigation
- [ ] EIN help text can be expanded/collapsed by keyboard control
- [ ] Expand/collapse element has appropriate ARIA attributes
- [ ] Expanded help text should be rendered by screen reader
- [ ] Collapsed help text should not be rendered by screen reader

**Comment by simplyshang** [comment]
Please refer to this prototype for the placement/order of the EIN: https://preview.uxpin.com/34b79c33c3e7f858ed533bcba5759c73521ac4af#/pages/77615508/simulate/sitemap?mode=i.

It should go before "Physical Address of Employer's Main Establishment" and after "Has the Employer’s name(s) changed since its last application?"

**Comment by EStriegel** [comment]
Closed since #469 includes the addition of the EIN question
