### ISSUE TITLE
As a vendor developer, I would like to ensure AngularJS & Angular components can work side-by-side

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#226]
This story is dependent on #185 

**side-by-side definition:** 
In lieu of #185 (c):
(c1) Allow AngularJS components to be upgraded so they can work in both AngularJS and Angular 4 pages.
(c2) Allow Angular 4 components to be downgraded so they can work  in both Angular 4 and Angular JS pages.

**Tasks**
1) Modify selected existing AngularJS component work in both AngularJS page as well as  Angular 4 page us using the links from #185.
2) Modify existing "Hello World Angular"page to contain this AngularJS component.  
3) Create/Modify one Angular 4 component using links from #185 (esp. hackernoon link).
4) Create a test AngularJS page "Hello World AngularJS" that contains the new Angualr 4 component.

**Acceptance Criteria:**
i) Demonstrate "Hello World Angular" Angular 4 page with Typescript from #185 works correctly with the AngularJS component & the Angular 4 component.
ii) Demonstrate "Hello World AngularJS" AngularJS page works correctly as well with the AngularJS component & the Angular 4 component.
iii) Provide documentation as to the steps needed to write/update the AngularJS component (to upgrade) and Angular component (to downgrade).

**Comment by brendansudol** [comment]
I believe this is done and can be closed
