### ISSUE TITLE
As a vendor developer, I must setup DB2 server

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#233]
**TODO:**
Setup DB2 server. (environments both Integration/QA)

DB Server: DB2 10.5.  (credit to @mgwalker : You can download Db2 Express-C for free. For ease of installation and configuration, I'd suggest the Db2 docker image for development, rather than mucking about with settings directly on dev machines. 

Data Studio (client) free version is also available for managing DB. 

**Acceptance Criteria**:
- [x] Full stack devs can connect to DB@ instances (Integration/QA)
- [x] Provide documentation as to the steps needed to setup DB2 server (own laptop/ docker image).

**Comment by mgwalker** [comment]
Just to clarify, is this related to the vendor setting up their development environment?  And thus the documentation would be so future developers can easily get going, correct?  The production environment will, of course, be WHD's responsibility.

**Comment by mmurthydol** [comment]
@mgwalker Correct Greg. Thanks for the clarification.
