### ISSUE TITLE
As the WHD certification team, I would like to receive the employer's submitted application.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#235]
Can be received via email or some other means acceptable to business (email for now).

Subject should include 1) Name of employer and 2) State listed on the employer screen > physical address of the main establishment (e.g. "14C Online Application Submission: Employer Name, State")

Body of the email should match the content that is sent to the employer (See resolution on #166)

The email should include a copy of and/or link to the same application (with all attachments) that was sent to the Employer in the confirmation email in #167.

**Comment by phirefly** [comment]
Subject should include 1) Name of employer and 2) State listed on the employer screen > physical address of the main establishment (e.g. "14C Online Application Submission: Employer Name, State")

Body of the email should match the content that is sent to the employer

**Comment by mmurthydol** [comment]
Done as part of agile flow.
