### ISSUE TITLE
As an Employer, I would like to enter Wage Data with ease

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#244]
As an Employer  I would like to enter data with ease.

## Acceptance Criteria
TODO

#### Functionality
- [ ] TODO Groom story based on UX design provided by #210 (populate acceptance criteria, tests, 508, etc.)
- [ ] Implement the functionality as provided by the UX design #210

#### Accessibility
- [ ] TODO
- [ ] all wage data text boxes can be reached by keyboard navigation
 - [ ] all text boxes have the appropriate type attribute
 - [ ] all text boxes have appropriate labels

**Comment by EStriegel** [comment]
Closed in favor of #345.
