### ISSUE TITLE
As a disabled user I would like HelpText functionality to be accessible so that I may use help text to fill out the application.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#248]
Current application has a "?" icon on various pages when clicked provides help text. This feature is not accessible (not 508 compliant).

There is a separate story #177 that adds the actual help text using this feature.

## Acceptance Criteria
- [ ] The HelpText feature needs to be 508 compliant on all pages and for all occurrences. 
#198 contains requirements for accessibility.

#### Functionality
N/A.

#### Accessibility
See acceptance criteria above.

**Comment by jmmcnj** [comment]
closing out due to rest of tasks being taken care of in another user story
