### ISSUE TITLE
Initial User Research

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#256]
- [x] Identify certificate holders for reach out [Liz]
- [x] Execution of reach out (email to cert holders, scheduling of interviews) [Liz]
- [x] Update prototype (new account creation flow & employee wage data) [Shannon]
- [x] Research plan (goal of test, questions, etc.) [Shannon]

**Comment by mgwalker** [comment]
Combined effort between @simplyshang and @EStriegel.

**Comment by simplyshang** [comment]
Here's the preview link for the prototype: https://preview.uxpin.com/264dcdbecf4bb9ceb62a5d0c3cbf5d51ab77d62b#/pages/76009155/simulate/no-panels

To view the usability test plan, click on "Documentation" in the top navigation after the preview loads.

Note: The above was reviewed morning of 10/10 with Liz, Raphy, Leslee
