### ISSUE TITLE
Client-side logging

### ISSUE THREAD

**Issue by mgwalker** [18F/dol-whd-14c#259]
All errors must be logged to an application error log using the error API.  A visual notification must be displayed upon catching an error. Error info must include a tracking number and a phone number (to be provided) for the end user to follow up.  All client errors - there should be no unhandled errors.

Error UX (and actual contact phone number etc details) are known through #156, #160.  For purposes of this story error info must provide security neutral information for all users.  For development environment, it must provide additional details (dev environment setting must be configurable without needing a code change - config files &/or query string. Need discussion with AIS/18F about providing details).

There are two aspects to this story:
Needs discussion with WHD/18F/AIS. Related to #188.

1) Client side: Builds on top of server side using http://jsnlog.com/
Client side handled/unhandled javascript errors will be written to the server using Error API. 
Security considerations need to be met. (TODO: what to do with errors from unauthenticated user?)
@davoodharun @dciceman David: Will need to add an extra column in error API, to signify if error occurred on the client/server side.
Harun: error info sent must include, page name, error context incl. page data. We can talk about the specs.  

Acceptance criteria: 
- [x] Demonstrate client side Java Script errors are logged on the server side & error notification is displayed.

**Comment by jmmcnj** [comment]
Need validation before acceptance, run manual test and create test script to run on build

**Comment by mmurthydol** [comment]
@davoodharun Harun, could you please verify what happens if client side error occurs, specifically the scenario doesn't occur. Scenario: client side error is logged to server, server api throws an error, client side now catches this error, and the cycle continues. We want to ensure that if the server error is in response to logging client side error, client side global handler must not go in to a loop.
