### ISSUE TITLE
Error API

### ISSUE THREAD

**Issue by mgwalker** [18F/dol-whd-14c#260]
All errors must be logged to an application error log.  All server side application errors including unhandled exceptions must be logged with specific error info using NLog to a DB2 database. Please refer to link below & discuss with WHD/18F prior to implementation. Can also write to a file.

https://www.codeproject.com/articles/1028416/restful-day-sharp-request-logging-and-exception-ha

> **Notes for the future**: Ideally app is built in .Net Core (not at time of writing), and pattern as shown below will be written so that error logging can be moved to cloud using Azure/AWS APIs.
.Net core logging: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging?tabs=aspnetcore1x

Acceptance criteria: 
- [x] logs errors it receives
- [x] unit tests covering this will show in code coverage totals

**Comment by jmmcnj** [comment]
@dciceman to get past unit test coverage then move to review/QA
