### ISSUE TITLE
Setting Up Baseline Documents for Accessibility Remediation

### ISSUE THREAD

**Issue by mgwalker** [18F/dol-whd-14c#261]
Acceptance criteria:
- [x] Create pa11y scans for each screen
- [x] Create Accessibility Criteria Status spreadsheet
- [x] Create new docs/a11y directory in repository for scans and spreadsheet

**Comment by jmmcnj** [comment]
lacking spreadsheet to date, needs to be updated in a pull request

**Comment by ltsheu** [comment]
Spreadsheet added in PR #288. The spreadsheet is available here:
https://github.com/18F/dol-whd-14c/blob/sprint/1/docs/a11y/DOL14c-Accessibility-Remediation.xlsx

**Comment by jmmcnj** [comment]
Can this one be closed, its 1 of 2 and the other one is already in progress, is this ok to be closed?

**Comment by mgwalker** [comment]
@jmmcnj Can you link the other one here?  It seems reasonable to me that if two issues capture the same thing, we should close one to keep the backlog cleaner.

**Comment by jmmcnj** [comment]
@mgwalker yeah I think I screwed this one up, I confused this with the other accessibility story for the App info page.  This is just the baseline and report which I think is complete.  @binwang89 am I correct, can this be closed?

**Comment by binwang89** [comment]
@mgwalker I reviewed this spreadsheet yesterday,  based on @ltsheu , she is still working on it.  I am not sure if the spreadsheet completed included in this user story or not.

**Comment by ltsheu** [comment]
@mgwalker @binwang89 This user story was for creating the spreadsheet and adding it to the repository. That work is complete, so this story may be closed. Ongoing updates to the spreadsheet will be captured in the remediation user stories.
