### ISSUE TITLE
Design UX for file upload validation notification

### ISSUE THREAD

**Issue by mgwalker** [18F/dol-whd-14c#262]
Design/prototype new upload validation notification.  notification needs to be defined and implemented in prototype.  design to be then handed to front end developer to implement html/css.  

- [x] Design/Prototype for upload validation notification
- [x] @EStriegel validate generic notification to user for error/validation
- [x] hand over finished design/prototype to front end for implementation

**Requirements**:
Allowed file types: .docx, .pdf, .jpg, .jpeg, .png., .xls, .csv, .doc
Individual file upload limit: 5MB
Error message needed for invalid type and/or size

###Acceptance Criteria
- [ ] completed and approved design/prototype
- [ ] verbiage should be approved by DOL

See #197

**Comment by simplyshang** [comment]
Here's the link w/the demo: https://preview.uxpin.com/53dd8414eb43fb96a93df5c6be44df3e071db3d7#/pages/76431985/simulate/sitemap

It's with the file upload under the Prevailing Wage Data section.

**Comment by EStriegel** [comment]
Moving to `Done`.  Implementation story is #197.
