### ISSUE TITLE
As a User I would like to be able to upload valid file (types/sizes) attachments through a Rest API.

### ISSUE THREAD

**Issue by mgwalker** [18F/dol-whd-14c#263]
Please implement per requirements below. App currently doesn't validate for said file types/sizes below. API config/C# files need to be modified to not allow larger than default attachments through AJAX calls. 

**Requirements**:
Requirements are part of the epic #290 this issue belongs to.

**Acceptance Criteria**:
- [x] Supported file types/sizes are configurable (web.config, comma/| delimited; ex: jpg|jpeg|png|pdf)
- [x] Web API supports method SupportedFileTypes that returns supported file types in a format usable by Angular.
- [x] Demonstrate only valid types/sizes are allowed.
- [x] Demonstrate app doesn't work for invalid types/sizes.
- [x] Demonstrate (1) & (2)  for corresponding API  (server side validation).
- [x] checks actual file/memory length before writing to server side
- [x] finalize size limit number and add to config
- [x] limit file type to pdf only

**Comment by jmmcnj** [comment]
Validate the tests on this feature

**Comment by mmurthydol** [comment]
@dciceman David, I think this code is merged in to main right?

**Comment by dciceman** [comment]
@mmurthydol Yes, the server side code has been merged.
