### ISSUE TITLE
Create Azure VM template

### ISSUE THREAD

**Issue by mgwalker** [18F/dol-whd-14c#264]
Provide Azure Resource Manager (ARM) template that mimic the AIS Integration server. 
Document the steps needed to install. 
Setup all tiers including 
 - API
 - UI 
 - Database

## Acceptance Criteria

- [x] ARM Template
- [x] PowerShell to deploy the template
- [x] Document for manual steps

**Comment by jmmcnj** [comment]
steps are documented and templates have been created, need to have handoff discussion with WHD and then move to Reviewed/complete

**Comment by jmmcnj** [comment]
@davoodharun and @mmurthydol is this ok to be closed, the discussion has happened I believe, has the PR been merged yet?
