### ISSUE TITLE
Update design prototype for Registration & Wage Data

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#283]
Preceded by User Story #256. Feedback below from review meeting on 10/10: 

#### Updates to Design Prototype

- [x] Add tool tips/help text to each form group on the slide out panel
- [x] Add a link to reach out & get help in the page so it is highly visible to users (this will also be available globally, but intentionally duplicating it in this instance to support users)
- [x] Move the "Successfully Save User" feedback to the top of the panel, above the heading "Add New Employee" when a user choses "Save and Add Another Employee".
- [x] Fix typo on Home page: "Application"
- [x] Add screen from DOL's public website for 14c. Use screenshot w/one active link so a user can simulate starting where they currently find 14c information and discovering/navigating to the new 14c application from there.

v2 Update
- [x] Revised Registration workflow; have users register only themselves first, then after email verification, they can provide employer details at the dashboard screen before beginning an application.

#### Updates to Usability Test Plan 
- [x] Ask users if managing multiple accounts is something they would need or find useful
- [x] Update scenario for Registration (user starts w/the DOL WHD 14c info page vs the application home page)
- [x] For each tester, know the number of employees they have. We'll ask users to enter in 5 employees, and want to be able to communicate "That was only 10% of the total amount of employees you would have to enter" to help them better gauge their LOE for the data entry work.
- [x] To Do: discuss internally and determine if we will provide demo data in the format of a spreadsheet for users to work off of during usability tests (to emulate how they might perform data entry in the real world)

#### Research To-Do
- [x] Connect with the one known user that manages multiple accounts (this should probably be its own user story, but wanted to capture it here for discussion during sprint planning) Note: Raphy called & they agreed to meet; Liz will be sending out an email to setup a testing session (to be done in Sprint 3).

#### Accessibility
- Not applicable for the design prototype

**Comment by simplyshang** [comment]
v1
https://preview.uxpin.com/961898dc08968d62cb4ca7daa62189716df298f7#/pages/76424754/simulate/no-panels

v1
https://preview.uxpin.com/672cf976db56fb446c1f954281636202590530cb#/pages/76425541/simulate/sitemap

**Comment by mmurthydol** [comment]
@simplyshang The login workflow (registration) story & wage data visual design story must be split and added to two different epics. i.e. #283 must be split if work not already finished. If finished, please provide the visual design specs for each under respective epics. Thanks!

**Comment by simplyshang** [comment]
@mmurthydol I'm on it! This story should be closed. But there are new stories I am working on now for planning this afternoon, based on conversations w/ @EStriegel this week. Among them, I'll be including the next steps for Registration & Wage Data (independent of one another) so we can assign & tackle appropriately.

**Comment by EStriegel** [comment]
Implementation story #417.  Moving to `Done`.
