### ISSUE TITLE
As a user, I would like the registration process to follow the new workflow

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#284]
As an employer I would like a better/more functional employer registration, that follows the below defined workflow/process

#### Functionality

- [ ] Register new employer screen (step 1)
- [ ] Register new employer screen pre-population (nice to have)
- [ ] Register new admin screen (step 2)

#### Accessibility
- [ ] ac 1
- [ ] accessibility criteria 2
- [ ] etc.

**Comment by phirefly** [comment]
User testing in progress week of 10/23. Requirements will be available for Sprint beginning 11/8.

**Comment by EStriegel** [comment]
Completed and closed.
