### ISSUE TITLE
Fix newly arrived tests in build process to baseline for new functionality

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#286]
As an admin/release manager, I would like the application to not deploy to Integration if any tests fail

## Acceptance Criteria
Builds are not pushed upon failure and pushed upon success of all tests
#### Functionality

- [x] Running through all existing tests and validating passed before building
- [x] Fail of builds will stop deployment into Integration

**Comment by mgwalker** [comment]
@davoodharun @jmmcnj Can one of you add some detail to the description on this chore?  It's not clear what it's for just from the title, and I'm a little concerned about what happens at sprint review in a couple of weeks when we get sidetracked for a couple minutes remembering what it includes.

**Comment by EStriegel** [comment]
@mmurthydol Can you confirm this is done?

**Comment by phirefly** [comment]
@mmurthydol ping on this. Can you verify and then move to `Done`? Thank you!
