### ISSUE TITLE
As a user, I would like a user friendly system error displayed

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#291]
As any end user, I would like an informative/user friendly error to display.

Error (web api, javascript) might occur (a) from user loading the page or (b) from user clicking on a button.
for (a), error should be highlighted at the top of the page 
for (b), error should be highlighted near the button.

Error message is based on Java script Exception (or) API error message that is returned. Both client side dev and server side dev need to ensure that the error message that is returned must be detailed only for "developers" and not end users. There should be a generic catchall message that is end user friendly (should contain a correlation ID returned by the error API; catchall message to be approved by business).
@EStriegel Need verbiage for a generic catchall error. Ex: An unspecified error occurred. Please contact dol... with this tracking number ....

Tasks
- [x] UX tasks
- [ ] meeting 1 hour - Liz/Raphy/Madhu/Shannon
- [x] does not include implementation will be on subsequent - creart user story for this

## Acceptance Criteria
- [ ] Display the error to the user (maybe in a `<p>` tag for now - visual design included in #160; helpful from a visual design perspective to be able to see the text on the page)

#### Functionality
- [ ] Finalize general error display

#### Accessibility
- [ ] Scan and remediate thru pally

**Comment by simplyshang** [comment]
@phirefly @EStriegel I think we can use this story for the Error pages; not sure if it had a different purpose, but it's a little vague at the moment. If you guys agree I can move it into Sprint 5 Tentative.

**Comment by simplyshang** [comment]
Prototype link for error pages: https://preview.uxpin.com/fa79f052ecaa5fb5c3f2e134550c33aa4613a12b#/pages/78408010/simulate/sitemap?mode=i
