### ISSUE TITLE
As a user, I want breadcrumbs

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#292]
As a [type of user] I would like [functionality, behavior, etc.] so that [a particular task or need that is satisfied by the functionality or behavior]

Also related to #193 ; 

## Acceptance Criteria
- [ ] meet DOL requirements

#### Functionality

- [x] Please see this DOL link for breadcrumb implementation expected by DOL standards.
https://www.dol.gov/agencies/ebsa/workers-and-families/childbirth-and-adoption
Click on the menu, sub-menu items to observe breadcrumb behavior.

- [x] functionality criteria 2
- [x] etc.

#### Accessibility
- [ ] meet DOL accessibility requirements (story??)
- [ ] accessibility criteria 2
- [ ] etc.

**Comment by phirefly** [comment]
Since this is the UI story, QA will have to wait until https://github.com/18F/dol-whd-14c/pull/434 is pulled into Awaiting Acceptance.

**Comment by mmurthydol** [comment]
@davoodharun  This story  #292 (breadcrumbs) is also related to #193 (DOL banner page reqs)
Shannon's Ux Spec outlines the "white" band and breadcrumb placement. https://preview.uxpin.com/48170bbaf1be987c1ab6af96c6c56e1b719ca1de#/pages/76592113/simulate/sitemap?mode=i
Please see attached document that provides the latest info for breadcrumbs implementation on what to display for breadcrumbs.

Wonder if this story can be delegated to the other Ux Dev?

- [ ] Implement missing "white band" in DOL header template:  that includes "Share" and "was this helpful" clickable links. WHD resources were provided for these to recreate the look. 
- [ ] Place breadcrumbs *after* "White" band. : Shannon's specs (click on DOL Launch page) show the placement.  Attached document has a screenshot as well. 
- [ ] Implement breadcrumb links as noted in the attached document. From 14c perspective, most clickable links in breadcrumbs are external to 14c links (=> static links) except for the "14c Home".  
- [ ] Please make the static links configurable so they can be changed without touching code.

**Comment by mmurthydol** [comment]
@jmmcnj @EStriegel @phirefly This story is currently awaiting acceptance but needs some work. This shouldn't take much time and Harun can probably have Steven work on. Would be good to get this done before Dec 13th from QA and SOL perspective. Thanks

**Comment by mmurthydol** [comment]
@davoodharun Moved this from "Awaiting acceptance" to "In Progress" due to the comments listed above.  Please direct Steven (or Steve?) to work on this. Thanks.
