### ISSUE TITLE
Add Instructions to Assurances Page

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#300]
[WH-226 eform instructions - Assurances.docx](https://github.com/18F/dol-whd-14c/files/1379940/WH-226.eform.instructions.-.Assurances.docx)

**Comment by jmmcnj** [comment]
@EStriegel will validate upon successful entry to the application, @davoodharun will work with Liz to get onboard

**Comment by EStriegel** [comment]
@jmmcnj This looks good to me.

**Comment by phirefly** [comment]
Verified by @EStriegel. Moving to `Closed`
