### ISSUE TITLE
Add Instructions to Application Info Page

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#301]
[WH-226 eform instructions - Application Info.docx](https://github.com/18F/dol-whd-14c/files/1379944/WH-226.eform.instructions.-.Application.Info.docx)

@ltsheu Should this be moved into Ready to Start or In Progress?

**Comment by ltsheu** [comment]
I will assign it to myself and move to In Progress. Thanks!

**Comment by ltsheu** [comment]
These text edits completed with PR #310. Moving this to Review/QA.

**Comment by jmmcnj** [comment]
@EStriegel will validate upon successful entry to the application

**Comment by EStriegel** [comment]
@ltsheu One small edit - there should not be a space between 14 and (c) under the first question, "What type of application is this?"

**Comment by ltsheu** [comment]
Hi @EStriegel -- I have made the small edit that you requested on the Application Info page. I removed the space between 14 and (c). It's ready for your review!

**Comment by EStriegel** [comment]
Hi @ltsheu - The small edit looks good.  However, only the first sentence of instructions are showing up under "Hospital/Residential Care Facility (Patient Workers)" and "School Work Experience Program (SWEP)".

**Comment by ltsheu** [comment]
@EStriegel The instructions are fixed on Application Info page. Please confirm (you might have to refresh browser).

**Comment by EStriegel** [comment]
@ltsheu Looks good!

**Comment by EStriegel** [comment]
Moving to Done per my review on 11/1.
