### ISSUE TITLE
Add instructions to Employer Info page

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#302]
[WH-226 eform instructions - Employer Info.docx](https://github.com/18F/dol-whd-14c/files/1379952/WH-226.eform.instructions.-.Employer.Info.docx)

**Comment by ltsheu** [comment]
@EStriegel Employer Page instructions are ready for your review! 😄

**Comment by EStriegel** [comment]
Moving to `Done` per my review on 11/1.
