### ISSUE TITLE
Add Instructions Wage Data Page

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#303]
[WH-226 eform instructions - Wage Data.docx](https://github.com/18F/dol-whd-14c/files/1379954/WH-226.eform.instructions.-.Wage.Data.docx)

**Comment by suprenant** [comment]
From grooming, it looks like we'll carry this over to Sprint 4.

**Comment by ltsheu** [comment]
Waiting for PR #414 to be merged, then this will be ready for DOL review.

**Comment by ltsheu** [comment]
@phirefly  The Wage Data page edits are ready for review.  URL: https://dol-whd-section14c-int.aisdemos.com/#!/section/wage-data

**Comment by EStriegel** [comment]
@ltsheu The instructions look good - wondering if we can italicize the words that were italicized in the word document.  They are:

**Hourly Wage: “How many workers did the employer pay hourly?”**
Provide the total number of workers paid an _hourly_ subminimum wage rate at any time during the most recently completed fiscal quarter.

**HOURLY, PREVAILING WAGE SURVEY: “Experience Worker Wage Provided”**
The wage rate collected from each source should be the hourly rate paid to _experienced_ (not entry level) workers who do not have disabilities that affect productive capacity. An experienced worker is a worker who has learned the basic requirements of the work to be performed, ordinarily by completion of a probationary or training period. Typically, an experienced worker will have received at least one pay raise after successful completion of the probationary or training period. 

**PIECE RATE: “How many workers did the employer pay on a piece rate basis?”**
Provide the total number of workers paid on a _piece rate_ basis that resulted in a subminimum wage at any time during the most recently completed fiscal quarter. 

**PIECE RATE, PREVAILING WAGE SURVEY: “Experienced Worker Wage Provided”**
The wage rate collected from each source should be the hourly rate paid to _experienced_ (not entry level) workers who do not have disabilities that affect productive capacity. An experienced worker is a worker who has learned the basic requirements of the work to be performed, ordinarily by completion of a probationary or training period. Typically, an experienced worker will have received at least one pay raise after successful completion of the probationary or training period.

**Comment by ltsheu** [comment]
@EStriegel  I have added the italics. Please review again. Thanks!

**Comment by EStriegel** [comment]
Looks good.  Moving to `Done` per my review on 11/20.
