### ISSUE TITLE
Add Instructions to Work Sites & Employees Page

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#304]
[WH-226 eform instructions - Work Sites & Employees.docx](https://github.com/18F/dol-whd-14c/files/1379957/WH-226.eform.instructions.-.Work.Sites.Employees.docx)

**Comment by ltsheu** [comment]
I would like to wait until #344 and #345 are complete before beginning the text updates. Marking as blocked by those two stories.

**Comment by ltsheu** [comment]
Hi @EStriegel and @phirefly!  Now that the "Add Employee" form fields have been redesigned, and will be in a side panel, do we still need the "Show me an Example" link next to the "Add Employee" button? In the Instructions document for Work Sites and Employees, the "Show me an Example" link shows a screenshot of the old design.

**Comment by ltsheu** [comment]
@EStriegel Please provide updated text for the following in the Employees tab: 
"We’ll need collect specific information for each employee. See detailed instructions on employee information"

**Comment by EStriegel** [comment]
@ltsheu Updated text is below.  The link to expand for instructions should be "Click here for detailed instruction on the required work information."

@simplyshang Since the screenshots are fresh on mind, tagging you in case you need this update for the prototype.

-------------
Information is needed about each specific worker who was employed at this work site at any time during the most recently completed fiscal quarter and received subminimum wages.  

Click here for detailed instructions on the required work information.

**Comment by ltsheu** [comment]
@EStriegel The instructions on Work Sites and Employees are ready for your review! 
https://dol-whd-section14c-int.aisdemos.com/#!/section/work-sites

**Comment by EStriegel** [comment]
Complete.  Moving to `Done`
