### ISSUE TITLE
Add Instructions to WIOA Page

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#305]
[WH-226 eform instructions - WIOA.docx](https://github.com/18F/dol-whd-14c/files/1379959/WH-226.eform.instructions.-.WIOA.docx)

**Comment by ltsheu** [comment]
@EStriegel The instructions have been added to the WIOA page, ready for your review!

**Comment by EStriegel** [comment]
@ltsheu The instructions look good.  I noticed that you added "WIOA Worker Verified" above the dropdown where they answer yes/no/not required.  I agree that we need something there, but can we change it to "Yes/No/Not Required"?  Thanks!

**Comment by ltsheu** [comment]
@EStriegel I updated the text to "Yes/No/Not Required".

**Comment by EStriegel** [comment]
@ltsheu Thank you!

**Comment by EStriegel** [comment]
Moving to `Done` per my review on 11/1.
