### ISSUE TITLE
List all required links in DOL standard footer

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#317]
Defect related to links not populated in #208 

## Acceptance Criteria

- [x] All footer links must be displayed as seen in https://www.savingmatters.dol.gov/ 
- [x] Footer display must be identical to what is seen on the link above (attachment provided for convenience)
- [ ] It was discovered that the current 14c header and footer did not use the templates provided by DOL. **Another user story will be created to update the header and footer to match DOL templates. #349**  

#### Accessibility
1. Keyboard Accessibility
 1.1 An interactive element or function can be accessed or activated by keyboard
 1.2 keyboard "trap" not found
 1.3 if non-standard keyboard commands are needed and they are documented
 1.4 TITLE provides information and equivalent information is found through text or visual context
 1.5 The visual focus can be determined at all times.
 1.6 focus always appears on the element it is programmatically on.
 1.7 if focus remains in the modal dialog box until the box is closed.
 1.8 if focus moves to revealed content OR a description of the content change is provided.
 1.9 the tab order is logical
3. Web: Links and User Controls
Links and/or user controls must have meaningful names that describe the unique destination, function, and/or purpose of the control for assistive technology.
[ ] 3.1 All links have a unique and meaningful description.
[ ] 3.2 All scripted elements have a unique and meaningful description.

**Comment by ltsheu** [comment]
Footer updated and merged with Pull Request #321. Moving to Review/QA.

**Comment by jmmcnj** [comment]
@binwang89  will validate and then approve to move to Review/QA

**Comment by ltsheu** [comment]
I have created another User Story to address the Header/Footer template issues. #349

**Comment by binwang89** [comment]
@ltsheu I have reviewed the footer links, they looks good.
