### ISSUE TITLE
C#: Use exception builders instead of functions that just throw

### ISSUE THREAD

**Issue by mgwalker** [18F/dol-whd-14c#327]
The `BaseApiController` class provides a set of methods that create and throw exceptions.  Gathering all of the exception creations into one place instead of having the same code scattered around is a great idea.  However, there's one gotcha - where those methods are used, the flow control is not obvious.  For example:

```C#
if (statuses == null)
{
    NotFound("Statuses not found");
}
return statuses;
```

A develop who is not familiar with the `NotFound` method might thing that `return statuses;` is called in every case.  The flow control does not obviously terminate `if (statuses == null)`.  An alternative approach that might make the flow control more obvious would be for the methods in `BaseApiController` to just construct and _return_ exceptions rather than also throw them.  E.g.:

```C#
protected ApiDataException NotFound(string message)
{
    return new ApiDataException((int)HttpStatusCode.NotFound, message, HttpStatusCode.NotFound);
}
```

...which would then be used like this:

```C#
if (statuses == null)
{
    return NotFound("Statuses not found");
}
return statuses;
```

An additional benefit is that the stack trace will be accurate - the throw will happen where `statuses` is null, rather than inside the helper method.  The "exception builder" pattern is also in [Microsoft's best practices guide](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#use-exception-builder-methods).

Other thoughts and ideas welcome!

**Comment by mmurthydol** [comment]
Accounted for milestone 1.
