### ISSUE TITLE
Web: Re-enable test coverage metrics

### ISSUE THREAD

**Issue by mgwalker** [18F/dol-whd-14c#330]
#325 updated the webpack config to fix tests, which had the side effect of disabling code coverage metrics.  The coverage instrumentation was interfering with the lint output, causing a lot of false positives.  We should find a different way to gather coverage metrics so we can have them, but without causing the lint to show errors.

## Acceptance Criteria

- [ ] no lint errors
- [ ] all tests pass
- [ ] coverage report generated

**Comment by mmurthydol** [comment]
@mgwalker Hey Greg,  I believe you take care of this story. Correct? If so, please close. If not please advise. what remains.

**Comment by mgwalker** [comment]
Yep!
