### ISSUE TITLE
Update HTML Patterns in the Library Page

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#333]
As a developer I would like the components library page to reflect current HTML patterns for the application, so that I may understand or use a pattern when needed.

https://dol-whd-section14c-int.aisdemos.com/#!/v4/ui-library

- [x] Update form component patterns in /DOL.WHD.Section14c.Web/src/v4/ui-library.component.html (see acceptance criteria below)
- [x] Change the Heading for this page from "UI Library for 508 Testing" to "UI Pattern Library for 14(c) Application"

## Acceptance Criteria

- [ ] The library page should demonstrate how each form component looks when rendered in the browser
- [ ] The library page should include a code/markup snippet for each form component
- [ ] The library page may include usage notes where needed
- [ ] If variations of a form component exist, they should also be represented in the library page, with their corresponding code snippets

**Comment by ltsheu** [comment]
The UI Library Page is ready for review. It is best viewed in the Chrome browser.
https://dol-whd-section14c-int.aisdemos.com/#!/v4/ui-library

**Comment by mmurthydol** [comment]
PR merged: https://github.com/18F/dol-whd-14c/pull/468

**Comment by mmurthydol** [comment]
Awaiting acceptance:
- [ ] @ltsheu Note at the top to use Chrome/Firefox to view this page (not IE)
- [ ] Need some updates from @davoodharun on what to do for Angular side of things.

**Comment by ltsheu** [comment]
@mmurthydol I have added the Note to the top of the Pattern Library. This change will show on INT after PR #479 is merged.

**Comment by EStriegel** [comment]
@mmurthydol Are you still waiting for the two items above to be completed?  Suggest moving to `In Progress`, if so.

**Comment by binwang89** [comment]
@EStriegel OCIO 508 tester is working on this page with other 14c application pages.

**Comment by jmmcnj** [comment]
completed
