### ISSUE TITLE
Create flow charts to evaluate the pros/cons of different approaches for Registration Workflow

### ISSUE THREAD

**Issue by simplyshang** [18F/dol-whd-14c#341]
Quickly draft flow charts for the registration workflow to capture the different approaches that have been discussed to help suppor the business discussion about the best approach for Milestone 1. 

Approaches discussed:

- [x] Having user create an account AND register an employer before accessing the system
- [x] Having user create an account, verify via email, then prompt them to register an employer on the Dashboard before they complete an application for the first time
- [x] Having user create an account, verify via email, and NOT register an employer (allow users to create applications for any employer, and only collect Employer info from the actual application)

Will attached flow charts when completed.

**Comment by simplyshang** [comment]
Think we're settled on the process for milestone one (Option 2)[https://app.zenhub.com/files/68946896/d43c6623-5a6a-41b8-87f0-26d040748237/download](https://app.zenhub.com/files/68946896/d43c6623-5a6a-41b8-87f0-26d040748237/download), but here are the workflows that were discussed:

**Comment by jmmcnj** [comment]
we have settled on workflow changes describe in option 2 above

**Comment by jmmcnj** [comment]
completed and referenced under login workflow epic to be implemented for tracking purposes

**Comment by phirefly** [comment]
Moving to `Done` per completed user research
