### ISSUE TITLE
As an applicant, I would like the system to tell me which fields are required for submission

### ISSUE THREAD

**Issue by simplyshang** [18F/dol-whd-14c#342]
As an applicant, I would like the system to tell me which fields are required for submission

#### Functionality

- [x] create design for required fields, diff between required and not

#### Accessibility

Prototype task; color contrast is black text on white background. Color contrast passes WCAG 2.0 AA at 21.

#### QASP requirements

These requirements are taken from the [Quality Assurance Surveillance Plan](https://github.com/18F/bpa-DOL-WHD-14-c/blob/master/solicitation_documents/QASP.md#40-performance-requirements-summary)

*Requirements for development removed*

**Comment by suprenant** [comment]
This struck me as I was doing some testing yesterday. It seems like we are marking fields as required currently but not showing those requirements to users until after they first attempt to submit the form. Seeing these required fields in advance would certainly seem helpful.

**Comment by simplyshang** [comment]
Reference #98

**Comment by phirefly** [comment]
@simplyshang Do you know if this is referring to the global requirements? If so, have we captured the validations when adding individual employees to a work site?

**Comment by phirefly** [comment]
^^ Referring to the comment we heard during user testing on 11/29.

**Comment by simplyshang** [comment]
This prototype contains the additions for required fields: https://preview.uxpin.com/d217c031c2dafec225a80652ee085d04ccafc106#/pages/78317778/simulate/sitemap?mode=i

**Comment by simplyshang** [comment]
Since the majority of fields are required, text will be added to alert users that all "fields are required unless indicated as optional". This should be below the heading of each page of the application:
![all-unless-optional.png](https://images.zenhubusercontent.com/57e6f0e395e42b6c5ba9656c/dff93002-f47a-459e-bca8-6af0d05fb12f)

Here's an example of a field labeled as optional:
![optional-field.png](https://images.zenhubusercontent.com/57e6f0e395e42b6c5ba9656c/aa21b159-9eaa-48f8-91b7-9f437d11b70d)

**Comment by simplyshang** [comment]
@phirefly I did make a recommendation in the research summary for the issue you mentioned that we saw during that usability test. It's slightly different than required fields, because the user needs to know how to handle each field in that question. Here's a screen shot:
![rec.png](https://images.zenhubusercontent.com/57e6f0e395e42b6c5ba9656c/4c612d5c-e789-4f58-ac90-77bb8bf3f60b)

**Comment by mmurthydol** [comment]
@EStriegel Liz, please verify Shannon's visual design. Not sure if there us an  implementation story for this. If not, we need an implementation story creating before closing this one. If writing implementation story we probably should go through visual design together.

**Comment by EStriegel** [comment]
Completed.  Moving to `Done`
