### ISSUE TITLE
How to tell or direct users how they can make a PDF for file upload

### ISSUE THREAD

**Issue by simplyshang** [18F/dol-whd-14c#343]
Since the application will only accept PDFs as a file upload for Milestone 1, we should probably provide some type of text or verbiage to help a user understand how to convert/create a PDF file from an existing document.

To-Do:
- [x] Look for any patterns or practices currently in use by other applications or sites to help inform the design decision

**Comment by simplyshang** [comment]
Point users to this support page from Microsoft with instructions on creating a PDF for all office products, versions 2007, 2010, 2013, 2016 & iOS: https://support.office.com/en-us/article/Save-or-convert-to-PDF-d85416c5-7d77-4fd6-a216-6f4bf7c7c110

**Comment by simplyshang** [comment]
![pdf-instructions.png](https://images.zenhubusercontent.com/57e6f0e395e42b6c5ba9656c/201c53cd-c37f-405b-9f2b-221c67eb6153)

**Comment by simplyshang** [comment]
@mmurthydol can you confirm that we'll be accepting .jpg, .jpeg & .png along w/PDFs? I think we discussed this before, and issue #290 confirms, but just want to double-check I have the accepted file types correct. Thanks!

**Comment by mmurthydol** [comment]
@simplyshang That is correct from implementation perspective. However in terms of wording in UI we want to let users know that word/excel docs can be saved as pdf to be able to upload to our application. In addition, some of help text can provide the actual steps. 
Thanks :)

**Comment by jmmcnj** [comment]
just need confirmation from DOL security that external link is approved on an external DOL website from @binwang89

**Comment by binwang89** [comment]
@jmmcnj @simplyshang Per WHD Security ISO, There is not issues with external user linking to Microsoft site for information.   However, our deputy director think we need a page “in between” that says you are leaving a government website".

**Comment by simplyshang** [comment]
@binwang89 Yes, we discussed this with the team. Greg suggested using the CGI that provides the "in between" page as seen in DOL's footer template: https://github.com/18F/dol-whd-14c/blob/sprint/3/DOL.WHD.Section14c.Web/src/v4/dol-footer.component.ts#L56

We tested it, and it worked well. Using the CGI will not increase the development effort, so all agreed this was the best approach. Here's an example:

**Comment by binwang89** [comment]
@simplyshang @mgwalker sounds good to me.

**Comment by binwang89** [comment]
@mmurthydol looping Madhu, please see above CGI recommendation from provided from Greg.

**Comment by EStriegel** [comment]
@mmurthydol Please confirm the CGI recommendation above.  Can be closed when you approve.

Raphy has created #471 for implementation.

**Comment by mmurthydol** [comment]
@phirefly CGI above will work for this purpose and for any other external links from the application.
