### ISSUE TITLE
Usability Testing - Sprint 3

### ISSUE THREAD

**Issue by simplyshang** [18F/dol-whd-14c#347]
As a [type of user] I would like [functionality, behavior, etc.] so that [a particular task or need that is satisfied by the functionality or behavior]

#### Planning & Setup

- [x] Respond to volunteers with consent form and requesting availability (@EStriegel)
- [x] Schedule sessions and send out Skype meetings (@simplyshang) 
- [x] Create usability test script (@simplyshang)
- [x] Create demo spreadsheet for users to reference for the data entry scenario
- [x] Create demo verification email to simulate the real registration process

#### Testing Sessions
- [x] 10/26/17, 10am - 11am
- [x] 10/27/17, 9am - 10am
- [x] 11/06/17, 12:30pm - 1:30pm

#### Accessibility
- Not applicable to this user story

**Comment by EStriegel** [comment]
Testing completed. Moving to `Done`
