### ISSUE TITLE
Create an Error Page for Employer Registration

### ISSUE THREAD

**Issue by simplyshang** [18F/dol-whd-14c#350]
For usability test scheduled 10/27/17, 9am-10am, we want to gauge a user's reaction to discovering there is already an existing account for their employer. 

As part of the ongoing research around the best approach for the Login & Registration Workflow. Want to identify any potential pitfalls in users creating an account for their employer and acting as an admin.

#### Functionality

- [x] Usability Tester will receive an error message telling them the Employer has already been registered after attempting to Register them upon first log-in. 

##### Color and Contrast

> Color dependence is using color as the sole means to convey information. There must be contrasting colors/shades at a ratio of 4.5:1 for discerning between background and foreground content.

- [x] if color is used but is not the only method to provide information.
- [x] if the contrast ratio is 4.5:1 or greater when comparing all background and foreground colors.

#### QASP requirements

Not required for UX Prototype updates.

**Comment by simplyshang** [comment]
Here's the link for full prototype (we used to this for the usability test): https://preview.uxpin.com/48170bbaf1be987c1ab6af96c6c56e1b719ca1de#/pages/76592113/simulate/sitemap?mode=i

**Comment by phirefly** [comment]
User tests with this are complete. Moving to `Complete`
