### ISSUE TITLE
[placeholder] Global helpdesk visuals

### ISSUE THREAD

**Issue by suprenant** [18F/dol-whd-14c#381]
Global access to help, for both technical support and reaching a SME about questions regarding the application.

Prototype link for placement of Help link (in system navigation), and a view of the Help page: https://preview.uxpin.com/5955e8a6afd15529d8967c143dbba46439f251ba#/pages/77595079/simulate/sitemap

**Comment by jmmcnj** [comment]
Create Implementation associated User Story before final review/closeout

**Comment by mmurthydol** [comment]
@EStriegel Liz, please verify Shannon's visual design. Not sure if #571 is the implementation story for this. If not, we need an implementation story creating before closing this one. If writing implementation story we probably should go through visual design together.

**Comment by EStriegel** [comment]
#571 is implementation story.  Moving to `Done`
