### ISSUE TITLE
Wage Data Page: Help buttons do not work in Piece Rate view

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#387]
Wage Data Page:
1) The help buttons do not function in Piece Rate view - they do not open the help text. They work fine in Hourly view.
2) The "Show Help for All Items" link does not function.

**Duplicate IDs are most likely causing this issue. The Hourly fields/buttons and Piece Rate fields/buttons use the same IDs.**

## Acceptance Criteria

- [ ] Help buttons should work throughout the Wage Data page, in both Hourly or Piece Rate view
- [ ] The "Show Help for All Items" link should toggle all help text on the page. 

#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

##### Keyboard Accessibility

- [ ] An interactive element or function can be accessed or activated by keyboard
- [ ] keyboard "trap" not found
- [ ] if non-standard keyboard commands are needed and they are documented
- [ ] TITLE provides information and equivalent information is found through text or visual context
- [ ] The visual focus can be determined at all times.
- [ ] focus always appears on the element it is programmatically on.
- [ ] if focus remains in the modal dialog box until the box is closed.
- [ ] if focus moves to revealed content OR a description of the content change is provided.
- [ ] the tab order is logical

##### Web: Forms

> Web forms include controls (checkboxes, radio buttons etc.), and editable content (text input, select options etc.).

- [ ] all form fields and their instructions and cues have HTML (‘Label for’ and ‘ID’ are used or TITLE is descriptive) or ARIA for association.
- [ ] All 'Label for' and 'ID' are valid code pairs.
- [ ] All form instructions that are provided by mouse over are available onscreen.
- [ ] All ARIA form fields have a NAME property that contains all of the instructions.
- [ ] All ARIA form fields have correct Role, State, and Value properties.
- [ ] All form controls identify their purpose. (Check if there are multiple form controls with the same visual label).

##### Web: Links and User Controls

> Links and/or user controls must have meaningful names that describe the unique destination, function, and/or purpose of the control for assistive technology.

- [ ] All links have a unique and meaningful description.
- [ ] All scripted elements have a unique and meaningful description.

#### QASP requirements

These requirements are taken from the [Quality Assurance Surveillance Plan](https://github.com/18F/bpa-DOL-WHD-14-c/blob/master/solicitation_documents/QASP.md#40-performance-requirements-summary)

- [ ] at least 90% code coverage
- [ ] no linting errors
- [ ] deploys successfully
- meets security requirements
  - [ ] static scan
  - [ ] OWASP ZAP
  - [ ] false positives documented

**Comment by EStriegel** [comment]
Confirmed help buttons function.  Moving to `Done`

**Comment by binwang89** [comment]
@EStriegel I tested it in QA site, the help link for piece rate is working now.
