### ISSUE TITLE
Spike: Data Schema for Login Workflow

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#391]
All new tables in the application will use following pattern below. Existing tables touched by login workflow will conform to this pattern as well (considering implementation cost to make change)

- [ ]  David do not address this entry. Keeping the spec for future.
    Identity columns (Private/Public).  @dciceman David, let's discuss naming, and other stuff here.
   - All major tables will have a private numeric identity column that will have a clustered index & 
     obviously unique. All joins will be based on this private identity column (value generated by the 
     database). 
     -  Name: <TableName>Id. Example: Employers table will have an EmployerId Identity column. 
           - Existing tables that use "Id" UUID & publicly exposed columns must be documented to rename 
             at an opportune time.
   - A public GUID/UUID based unique UUID/GUID column will be supported when API calls need to 
     expose an Id to the outside world. (value generated by the API). 
     - Name: <TableName>Id. Example: Employers table will have EmployerId column. 

  - [ ] There are many to many relationships in the DB schema (though milestone 1 only supports 1 to 1 
    relationships) between Users <--Many-to-Many --> Employers  <--Many-to-Many --> Applications
  - [ ] UX will use ApplicationId as a basis to work with the 14C application (unlike using EIN in Phase 1) - 
     supported by API changes. UX needs to keep track of currently logged in user, currently associated 
     employer, current application being worked on. Given Application's Id, DB schema can tell which 
    Employer's Id this Application belongs to. API routing must be mindful of impacts of schema changes 
    and application behavior on API routing.
  - [ ] Employers table will contain employer account registration Info EmployerInfoes table contains 
     Form Data.
  - CertificateNumber <-- @dciceman Ok for milestone. Certificates table may be in future milestones.
  - LegalName
  - EIN
  - PrivateId  <-- @dciceman  Remove PrivateId from BaseEntity.cs
  - CreatedBy
  - CreatedAt
  - LastModifiedBy
  - LastModifiedAt
  - AddressId  (@dciceman not PhysicialAddress or PhysicalAddress; Believe we have an Address Table)

- [ ] Audit columns for Identity Framework tables (other tables already have these).
  - LastModifiedBy
  - LastModifiedAt
  - CreatedBy
  - CreatedAt

- [ ] Users table (discounting existing Identity Framework supported columns) contains 
  - FirstName
  - LastName
  - Audit columns as specified above
  - Identity columns as specified above (non GUID Identity column, unique GUID column)

- [ ] UserLogins, UserRoles, UserClaims, Roles
  - If not already must contain the User's Id (non GUID Identity) column.
  - If not already must contain appropriate data for that table.

 - [ ] OrganizationMemberships Table (same a Join Table for Users & Employers)
   - IsPointOfContact (used to be IsAdmin)
   - ApplicationId <-- Not here? or here to keep track of who worked on the application??
   - EmployerId (should join to Employer's Identity column ideally)
   - UserId (should join to User's Identity column ideally)
   - Someday Join table should be aptly renamed UserEmployer 

 - [ ] ApplicationSaves seems to acting as the EmployerApplication Join table along the lines of 
        OrganizationMemberships above? Also acting as Applications table? Something not right? 
  - EmployerId  <-- not Employer
  - ApplicationId 
- [ ] ApplicationSubmissions - ApplicationSave's Id is passed by UX upon ApplicationSubmission.  This Id will = ApplicationSubmissions Id column (C# ctor for ApplicationSubmissions must not generate GUID. API should assign accordingly in web method. 
- [ ] David, ok for this milestone if you decided to just go with CertificateNumber column in Employers table. Certificates table needs to exist by itself. Employers table will have a Foreign Key to Certificates table.
       Certificate right now is 14C, but it could be other types of certificates. This table will become a core 
       feature in future milestones with added columns, and other supporting tables. Look up this table to 
       see if Certificate already exists. 
 - [ ] doesn't quite belong here but related to schema changes. All API methods need to support 
        "applicationId" instead of "EIN" in its routing & post. Need authorization code on Web methods 
        based on applicationId (not hasClaims("EIN") in C-Sharp.

**Comment by dciceman** [comment]
The following database tables need to be updated in order to support the new Login Workflow.

Database Schema Update
-  Users
    - Add FirstName
    - Add LastName
    - LastModifiedBy
    - LastModifiedAt
    - CreatedBy
    - CreatedAt
- UserClaims
    - LastModifiedBy
    - LastModifiedAt
    - CreatedBy
    - CreatedAt
- UserLogins
    - LastModifiedBy
    - LastModifiedAt
    - CreatedBy
    - CreatedAt
- UserRoles
    - LastModifiedBy
    - LastModifiedAt
    - CreatedBy
    - CreatedAt
- Employers
    - CertificateNumber
    - LegalName
    - EIN
    - PrivateId
    - CreatedBy
    - CreatedAt
    - LastModifiedBy
    - LastModifiedAt
    - PhysicialAddress
- OrganizationMemberships
    - Rename IsAdmin to IsPoc
    - ApplicationId
    - Employer
- ApplicationSaves
    - Employer
    - ApplicationId

**Comment by mmurthydol** [comment]
@dciceman Closing the issue. Changes from here go in to login workflow API.
