### ISSUE TITLE
Create Login Workflow related API

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#392]
Could be separate stories if someone wants to manage...

## Functionality
- [x] Modify Login Page related Web AP (Remove EIN)
- [x] Ensure no changes to User Account Registration Web API; if not modify
- [x] Create Employer Account Registration Web API  (Modifications to User Table - see blocker data schem story. Changes to Identity management code.

## Acceptance Criteria
 - [ ] Authorization/secure
 - [ ] Error/activity logging
 - [ ] Routing should be specific for user/employer account management
 - [ ] ...

**Comment by jmmcnj** [comment]
awaiting small edit then merge
