### ISSUE TITLE
Write Email Web API - As an Employer/Cert Team member I need ability to receive email 

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#393]
#### Functionality

- [ ] Refactor existing code that sends email to be a separate WebAPI
- [ ] Email API methods must support To, From, CC, Subject, Body, Attachments - as outlined in the user stories. TODO - populate info here from those stories. 
- [ ] Call email web api from application submit web api method.

TODO - add this to appropriate epic.

**Comment by EStriegel** [comment]
Completed and closed.
