### ISSUE TITLE
Implementation - User Account Registration page

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#397]
**Please Note: with the change in the design from last week's working session, we will not need to change the layout/functionality of User Account Registration.** *This is pending feedback & approval as of 11/15.*

Direct link to prototype page for User Account Registration: https://preview.uxpin.com/dbef3aaee7fc9fac51dc1d087e1f9180f3610ab3#/pages/78406870/simulate/sitemap

For reference, here is the full prototype for the Registration Workflow, beginning with the Flow Chart: https://preview.uxpin.com/dbef3aaee7fc9fac51dc1d087e1f9180f3610ab3#/pages/78406867/simulate/sitemap

[content edited by @simplyshang 11/15]

Harun begins it, Leslie drops accessible patterns

## Acceptance Criteria

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

#### Functionality

- [ ] User Account Registration Page - redesigned from UXpin link, reuse views from existing login page - Harun/Leslie 
- [ ] accessiblity testing
- [ ] unit tests

#### Accessibility
Accessibility per #198

**Comment by ltsheu** [comment]
@davoodharun Here are feedback message patterns for Register An Employer. The CSS for this will be merged with PR #402.

SUCCESS FEEDBACK

![feedback-success](https://user-images.githubusercontent.com/31778248/32622271-5acbef54-c550-11e7-959f-56e1c0db55a7.png)

```
  <div class="dol-feedback-success">
    <p class="dol-feedback-message">
      <strong>Your Account Has Been Created</strong>
    </p>
  </div>
```

ERROR FEEDBACK

![feedback-registration-error](https://user-images.githubusercontent.com/31778248/32622301-723706b0-c550-11e7-9a4c-8fbb49dd5be0.PNG)

```
  <div class="dol-feedback-error">
    <p class="dol-feedback-message">
      <strong>We've run into a problem.</strong>
    </p>
  </div>
```

**Comment by phirefly** [comment]
@simplyshang This doesn't appear to have a visual design yet. Please add. Thank you!

**Comment by simplyshang** [comment]
@phirefly Added links; also note about the pending change (as posted in Slack).

**Comment by EStriegel** [comment]
@binwang89 Can you confirm accessibility part of this story?  Can be moved to `Done` if acceptable.
