### ISSUE TITLE
User Research Findings

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#406]

**Comment by simplyshang** [comment]
Last usability test will be on 11/29; will wait until that test is completed and then summarize all the results at one time. Will review in Sprint 5.

**Comment by simplyshang** [comment]
PDF of research summary: [https://app.zenhub.com/files/68946896/07d88883-dd4e-4317-8e43-fcca4a34721c/download](https://app.zenhub.com/files/68946896/07d88883-dd4e-4317-8e43-fcca4a34721c/download)
