### ISSUE TITLE
As an Applicant, I would like a user friendly form web application for the 226/a - Design

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#41]
Requirements:
UX Design/Assets
Collection of Data, basic version section by section
Follow physical form flow and data requirements
[Proposed WH226.pdf](https://github.com/18F/dol-whd-14c/files/494082/Proposed.WH226.pdf)
[Proposed WH226A.pdf](https://github.com/18F/dol-whd-14c/files/494092/Proposed.WH226A.pdf)

Acceptance Criteria:
PO review and approval of designed Wireframes on 226/a forms

**Comment by jmmcnj** [comment]
Requirements:
UX Design/Assets
Collection of Data, basic version section by section
Follow physical form flow and data requirements
[Proposed WH226.pdf](https://github.com/18F/dol-whd-14c/files/494082/Proposed.WH226.pdf)

Acceptance Criteria:
Start new application, step by step (based around section) following section order from paper forms

**Comment by simplyshang** [comment]
[DOL14c-Wireframes-v2.pdf](https://github.com/18F/dol-whd-14c/files/516221/DOL14c-Wireframes-v2.pdf)
