### ISSUE TITLE
Implementation - Login page for login workflow

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#416]
**Please Note: with the change in the design from last week's working session, we will not need to change the layout/functionality of Log in.** 

Direct link to prototype page for Log in: https://preview.uxpin.com/dbef3aaee7fc9fac51dc1d087e1f9180f3610ab3#/pages/78406869/simulate/sitemap

For reference, here is the full prototype for the Registration Workflow, beginning with the Flow Chart: https://preview.uxpin.com/dbef3aaee7fc9fac51dc1d087e1f9180f3610ab3#/pages/78406867/simulate/sitemap

[content edited by @simplyshang 11/15]

#### Accessibility
See #198  for Accessibility requirements

**Comment by phirefly** [comment]
@simplyshang This doesn't appear to have a visual design yet. Please add.

**Comment by simplyshang** [comment]
@phirefly Added links; also note about the pending change (as posted in Slack).

**Comment by EStriegel** [comment]
@mmurthydol Can you confirm that this was pushed to Integration, but not QA?
