### ISSUE TITLE
Implementation - Employer Registration page for login workflow

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#417]
Direct link to prototype page for Employer Registration: https://preview.uxpin.com/dbef3aaee7fc9fac51dc1d087e1f9180f3610ab3#/pages/78406877/simulate/sitemap

For reference, here is the full prototype for the Registration Workflow, beginning with the Flow Chart: https://preview.uxpin.com/dbef3aaee7fc9fac51dc1d087e1f9180f3610ab3#/pages/78406867/simulate/sitemap

[content edited by @simplyshang 11/15]

As a company admin I would like to register an employer to facilitate the submission of a 14c application

## Acceptance Criteria
- [ ] Frontend form validation. 
Repurpose the EIN validation that exists, adhering to format example `XX-XXXXXXX`
Cert number to adhere to format example `12-34567-H-890`
- [ ] Submit to API
- [ ] Handle success (@simplyshang to determine landing page)
- [ ] Handle failure: go to the `Employer Registration Error` page (see UXPin)

#### Accessibility
see #198 for accessibility 
 
> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by phirefly** [comment]
@simplyshang Do we know what happens when clicking `What if the Employer's legal name changed since its last application?`?

@EStriegel may have insight into the content if it doesn't exist already.

**Comment by phirefly** [comment]
@EStriegel, can you confirm the format for Cert numbers provided in the example `12-34567-H-890`

**Comment by phirefly** [comment]
Confirmed with Data and the O+M vendor that the validation for cert number is `dd-ddddd-c-ddd`, where `d` is a digit and `c` is a letter character.

**Comment by EStriegel** [comment]
@mmurthydol Can you confirm that this was pushed to Integration, but not QA?

**Comment by mmurthydol** [comment]
@EStriegel This was pushed to integration before the pause (=> code merged to integration). We should close this story . Cert Validation defect is already created.
