### ISSUE TITLE
UI Implementation - 2FA page for login workflow

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#418]
@dciceman #203 contains the specs. Madhu and David went through specs together.

- [x] Page for entering verification code
- [x] Content necessary e.g. "Verification code was sent. Please enter..."
- [x] Resending verification code
- [x] Additional content: Contact DOL with issues

@simplyshang will confirm this is ok from a ux perspective.

- [x] call between @simplyshang @dciceman @binwang89 after sprint planning session to review flow
- [x] @dciceman to provide flow, screen shots and email verbiage to @simplyshang 
- [x] @simplyshang will provide lean response based on @dciceman artifacts provided
- [x] @dciceman to consult with @davoodharun on angular routing

#### Accessibility
See #198 for accessibility

**Comment by davoodharun** [comment]
@simplyshang do we have a prototype for these pages? @mmurthydol do we need prototypes for these new pages?
