### ISSUE TITLE
CSS Implementation - Wage Data Styling

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#425]
This is a continuation of #344 and #345, remaining styling work. 

As an employer I would like to use Wage Data with styling so that my user experience is optimal

UX designs:
https://preview.uxpin.com/107df641f3eac499a1e03532bab2b062fbaecd4c#/pages/77134368/simulate/sitemap?mode=i > `Add Employee - Panel Open`

## Acceptance Criteria
Slider
- [ ] General styling
- [ ] Help link styling using the current pattern

Main page, See UX design: `Add Employee - Done`
- [ ] Help link buttons
- [ ] Chat button
- [ ] Show More Details button
- [ ] Text sizes
- [ ] Sort buttons
- [ ] Data table button styling
- [ ] Search, which was added and not on UXPin needs freedback from @simplyshang 

#### Accessibility
Accessibility per #198

**Comment by ltsheu** [comment]
Waiting on updated styles for datatables components from @simplyshang.

**Comment by ltsheu** [comment]
@phirefly and @EStriegel  The CSS updates are ready for your review on Work Sites & Employees page. 
https://dol-whd-section14c-int.aisdemos.com/#!/section/work-sites
