### ISSUE TITLE
Bug: Prevailing wage survey questions are visible before a PW method is chosen

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#439]
The prevailing wage survey box is visible before a PW method is chosen (nothing should appear until a method is chosen).  This occurs for both hourly and piece rate screens.

--------------------------
![image](https://user-images.githubusercontent.com/19496579/33037006-2ca4a1a0-cdfe-11e7-855e-fb93df314697.png)

**Comment by davoodharun** [comment]
@EStriegel I am not experiencing this. @ltsheu, @mmurthydol, @mgwalker, @jmmcnj can any of you confirm this is still an issue?

**Comment by ltsheu** [comment]
@davoodharun I suspect it would only happen if the user has not filled out the form yet -- such as a brand new application, where the radios are not selected yet? I cannot reproduce it with my current account because my application is in progress and the radio already selected.

**Comment by mmurthydol** [comment]
@davoodharun Liz is out till next wednesday. I would hold off till she is back and confirms that she can repro the issue. 

@EStriegel Liz When you get a chance could you please repro the issue and update the story and alert Harun (please close the story if cannot repro). 

Thanks!

**Comment by davoodharun** [comment]
@EStriegel were you able to revisit this?

**Comment by EStriegel** [comment]
@davoodharun I still see the error on my application (in that no radio button is selected, but the prevailing wage questions are still visible).  I suspect this happened because I toggled my "in-progress" application from renewal application (with a radio button selected) to initial application (which doesn't display the Wage Data screen) and then back to renewal application (shows no radio button selected but prevailing wage questions still visible).  

To Leslee's point, I cannot see what a brand new application looks like.

**Comment by EStriegel** [comment]
Moving to `Closed` based on the explanation above.
