### ISSUE TITLE
Update Assurances page to capture separated First Name and Last Name

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#440]
As an applicant I would like to be able to enter my name separately as `First name` and `Last name` so that the system data collection is optimal.

## Acceptance Criteria

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

#### Functionality

- [ ] Split `Name` into `First name` and `Last name`

#### Accessibility
See #198 for Accessibility requirements

**Comment by mmurthydol** [comment]
There a couple of other stories #490 in the backlog for Sprint 7. Closing this one
