### ISSUE TITLE
IE browser: Top navigation items cannot be triggered with Enter key

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#448]
## Bug Description

In the IE browser, the top navigation items (Assurances, Application Info, etc) cannot be triggered with the Enter key. The Enter key works for these items in Chrome.

This is a keyboard accessibility issue.

## Acceptance Criteria

- [ ] In IE and all browsers, the Enter key can be used to trigger Top Navigation items.

**Comment by EStriegel** [comment]
@binwang89 Can you label this bug (ciritical/major/minor)?

**Comment by binwang89** [comment]
done.

**Comment by binwang89** [comment]
@ltsheu tested it by using IE, and it looks fine. I will move it to "Awaiting Acceptance". Thanks
