### ISSUE TITLE
'Add a Source Employer' needs focus management

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#449]
## Bug Description

Page: Wage Data
https://dol-whd-section14c-int.aisdemos.com/#!/section/wage-data

1. Under **Which method did the employer use to determine the Prevailing Wage for the job or contract identified above?**, choose **Prevailing Wage Survey**
2. Click **Add a Source Employer**
3. Press the Tab key
4. Bug: The Tab order skips the entire **Add a Source Employer** form and goes to the next tabbable item after the **Add a Source Employer** form. 

This is a keyboard and screen reader accessibility issue.

## Acceptance Criteria

- [ ] If the **Add a Source Employer** button is clicked (or Enter key is pressed), focus should move to the **Source Employer Name** text field.
- [ ] If the **Cancel** button is clicked (or Enter key is pressed), focus should move back to the **Add a Source Employer** button.
- [ ] If the **Save Source Employer** button is clicked (or Enter key is pressed), focus should move back to the **Add a Source Employer** button.
- [ ] If the **Edit** button is clicked for a Source Employer (or Enter key is pressed), focus should move to the **Source Employer Name** text field.
- [ ] If a user **deletes** a Source Employer, focus should move back to the **Add a Source Employer** button.

**Comment by EStriegel** [comment]
@binwang89 Can you add a label to this bug (minor/major/ciritcal)?

**Comment by binwang89** [comment]
@ltsheu @davoodharun I put this issue at the top one at the backlog and should be pulled to sprint 7.

**Comment by binwang89** [comment]
@mmurthydol , this is Javascript/Angular part, we need input from @davoodharun .

**Comment by binwang89** [comment]
@ltsheu @davoodharun I  tested this user story and it looks good, I will move it to Acceptance.  Thanks for the works.
