### ISSUE TITLE
Create Pattern Library Page for Form Components

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#455]
As a developer I would like a catalog of markup snippets to use as a reference when adding form fields, help buttons, help text, etc.

**THIS IS A DUPLICATE OF #333**

**Comment by mmurthydol** [comment]
@ltsheu Leslee, thought you are working on this in Sprint 5??

**Comment by ltsheu** [comment]
@mmurthydol #455 is a duplicate of #333. I accidentally created it, and then Shannon pointed out that we already have #333. So I marked #455 as a duplicate. Please close #455. Thanks.

**Comment by mmurthydol** [comment]
@ltsheu Thanks for the response. Missed seeing the description. In future please feel free to close the issue - more than ok :)
