### ISSUE TITLE
Bug: Accessibility: 508: Each page needs a unique identifier in the <title> tag

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#456]
**Issue identified by DOL accessibility tester:** There is no meaningful page title in plain language. 

This refers to the `<title>` tag. Currently the `<title>` tag says "DOL WHD Section 14(c)" for each page of the application. The page names should also be represented in the `<title>`.

## Acceptance Criteria

- [x] Assurances `<title>` should be: **Assurances | DOL WHD Section 14(c)**
- [x] Application Info `<title>` should be: **Application Info | DOL WHD Section 14(c)**
- [x] Employer `<title>` should be: **Employer | DOL WHD Section 14(c)**
- [x] Wage Data `<title>` should be: **Wage Data | DOL WHD Section 14(c)**
- [x] Work Sites & Employees `<title>` should be: **Work Sites & Employees | DOL WHD Section 14(c)**
- [x] WIOA `<title>` should be: **WIOA | DOL WHD Section 14(c)**
- [x] Review and Submit `<title>` should be: **Review and Submit | DOL WHD Section 14(c)**
- [x] Additional pages in the application should follow this `<title>` pattern

**Comment by binwang89** [comment]
@ltsheu @stevenmyket this issue has been changed from "In Progress" to "Awaiting Acceptance", did someone review/test this issue before moved it to Awaiting Acceptance?

**Comment by binwang89** [comment]
@ltsheu @stevenmyket  I have tested it in QA site, (i have issue to access the INT).  please see below screenshots for each page with title information. 

![image](https://user-images.githubusercontent.com/25330625/34840615-8d7d5b2c-f6d3-11e7-9644-cc3cfca0291e.png)
![image](https://user-images.githubusercontent.com/25330625/34840640-9ee90fa0-f6d3-11e7-9513-d14950455ace.png)
![image](https://user-images.githubusercontent.com/25330625/34840670-b4dd3fde-f6d3-11e7-8324-168db3c03df2.png)
![image](https://user-images.githubusercontent.com/25330625/34840694-c675cc02-f6d3-11e7-9aa9-bf2e4322a8e7.png)
![image](https://user-images.githubusercontent.com/25330625/34840714-d6020e88-f6d3-11e7-95a5-ffa1d46645a4.png)
![image](https://user-images.githubusercontent.com/25330625/34840760-f79dd0b8-f6d3-11e7-88ee-3e0d3a9b9b2e.png)

**Comment by binwang89** [comment]
When tested in QA site, found below issue, when use the "Next" button  to next page, 
the title for the previous page is still show up. In  this example, when tab the next button to WIOA page, the title still show "Work Site and Employee"

![image](https://user-images.githubusercontent.com/25330625/35943617-9cce4438-0c27-11e8-9237-2c45bcdd86ce.png)

**Comment by binwang89** [comment]
I just re-tested it and found out i can reproduce the same issue by using the mouse. however, it does has accessibility impact and i will create a separated user story for this issue.  I will move this user story back to waiting acceptance.

**Comment by phirefly** [comment]
`Review and Submit` says `Review`

**Comment by phirefly** [comment]
See QA comments above. Moving back to `In Progress`

**Comment by mmurthydol** [comment]
i think harun mentioned this was done. If you can verify please @phirefly

**Comment by binwang89** [comment]
@mmurthydol @EStriegel Tested in INT site, I don't think the issues have been resolved. please see below screenshot,  the unique identifier still not showing in each web page tab, it only show on the url. 
![image](https://user-images.githubusercontent.com/25330625/36733815-bfe49c42-1b9f-11e8-965d-7e6239e88d22.png)

**Comment by phirefly** [comment]
@mmurthydol See my note above after my QA... 

Review and Submit says Review

The following pages don't have titles:
Dashboard
Account
Help

**Comment by NathayaMDOL** [comment]
Hi @EStriegel  / @binwang89,
The unique title has been added to each page, please see the screenshot below and let me know if any title name needs changes before I push to Dev environment. 
note: branch name "whd-aqa-456-nmankong-508-title-tag"

![login](https://user-images.githubusercontent.com/40499717/42961385-a7d72d36-8b5c-11e8-8448-d6cd85d689a7.PNG)
![review submit](https://user-images.githubusercontent.com/40499717/42961428-bbba5e22-8b5c-11e8-8ea0-acca5853b841.PNG)
![dashboard](https://user-images.githubusercontent.com/40499717/42961438-c06e8466-8b5c-11e8-9d8b-48c717259009.PNG)
![account](https://user-images.githubusercontent.com/40499717/42961440-c235c610-8b5c-11e8-95a0-c5eca976be1f.PNG)
![manage users](https://user-images.githubusercontent.com/40499717/42961446-c5c7b4be-8b5c-11e8-864d-11a946978543.PNG)
![help](https://user-images.githubusercontent.com/40499717/42961450-c813c6b8-8b5c-11e8-8c18-c011d160c2fe.PNG)

**Comment by binwang89** [comment]
@EStriegel @mmurthydol  The title looks good, however some breadcrumb is not match the link/title.

**Comment by NathayaMDOL** [comment]
Hi @binwang89 ,
Per our discussion on Friday, The breadcrumbs and page header have been changed. Please see screenshots below.
![456-change account-bc](https://user-images.githubusercontent.com/40499717/43085243-7a49d9cc-8e68-11e8-8b1d-8021e9279b54.PNG)
![456-change manageusers-bc](https://user-images.githubusercontent.com/40499717/43085244-7a615a66-8e68-11e8-917f-ccd2b7076c9c.PNG)

Thanks,
Nathaya

**Comment by binwang89** [comment]
@NathayaMDOL the screenshots looks good, please push the code to DEV, i will testing it again.  Thanks

**Comment by NathayaMDOL** [comment]
@binwang89, All changes have been pushed to Dev.

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
