### ISSUE TITLE
Text Edits from OMB Screenshots

### ISSUE THREAD

**Issue by simplyshang** [18F/dol-whd-14c#469]
In preparing the screenshots for the OMB review, there were some areas of the application where text changes were made. These need to be incorporated into the application.

This prototype has the text edits, identified by callouts w/yellow borders: https://preview.uxpin.com/d217c031c2dafec225a80652ee085d04ccafc106#/pages/78317778/comment/sitemap?mode=i

#### Functionality

- [ ] Make text edits as indicated in the attached PDF.
- [x] Story #509 
- [x] Story #532 
- [x] Story #552 
- [x] Story #214 (also specified as part of text edits)

#### Accessibility

N/A to this task as it's only for text edits.

**Comment by EStriegel** [comment]
@simplyshang Our PRA folks have asked that the OMB control number, expiration date and revision date be added to the log-in screen.  Let discuss when the pause is over.

**Comment by EStriegel** [comment]
**Additional edit for Assurances section**

Begin new paragraph at following sentence:
I represent that as set forth in the regulations governing the employment of workers with disabilities, the following conditions exist and will continue to exist:

**Comment by EStriegel** [comment]
See #214 for additional instruction re: addition of the EIN question.  @mmurthydol @stvnrlly

**Comment by EStriegel** [comment]
@stevenmyket I've consolidated other text edit stories into the Acceptance Criteria above.  Let me know if you have any questions.

**Comment by davoodharun** [comment]
Text Edits related to new application workflow (System use, landing page, user login, employer registration etc.) are made in the NewApplicationWorkFlow branch being merged with PR #493

**Comment by EStriegel** [comment]
@davoodharun Happy to discuss!  Moving to `In Progress`

## Remaining text edits:
[Text Edits 1.29.18.xlsx](https://github.com/18F/dol-whd-14c/files/1675004/Text.Edits.1.29.18.xlsx)

-----------------------

I reference a couple screen shots in the spreadsheet.  They are below.

Addition of OMB info under header:
![image](https://user-images.githubusercontent.com/19496579/35529661-aed2753e-04ff-11e8-940f-b9f4a7c475fa.png)

Questions box (link is to the help page):
![image](https://user-images.githubusercontent.com/19496579/35529727-f39a223e-04ff-11e8-841d-9deb3d4adcb8.png)

**Comment by EStriegel** [comment]
@davoodharun Looking at the spreadsheet we had in Slack, and have added additional feedback in doc below.  Main concern is that I'm seeing differences between INT vs. QA sites.

[Text.Edits.2.12.18.xlsx](https://github.com/18F/dol-whd-14c/files/1717681/Text.Edits.2.12.18.xlsx)

**Comment by mmurthydol** [comment]
@EStriegel Liz, not sure whether Harun got these fixes in before POP. Could you please verify? Let's move this to in progress with your notes from QA>

**Comment by EStriegel** [comment]
Missing text edit - On Register Employer page - "What is the most recently held certificate number for the main establishment?" should be "What is the most recently held main establishment certificate?"

**Comment by joebhaktiarDOL** [comment]
https://github.com/18F/dol-whd-14c/pull/672

**Comment by EStriegel** [comment]
Confirmed complete.  Moving to `Done`
