### ISSUE TITLE
Implementation: As a user, I can find how to make a PDF for file upload so that I can have an optimal experience

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#471]
This is the implementation for #343 

As a [type of user] I would like [functionality, behavior, etc.] so that [a particular task or need that is satisfied by the functionality or behavior]

## Acceptance Criteria

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

#### Functionality

- [ ] functionality criteria 1
- [ ] functionality criteria 2
- [ ] etc.

#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by mmurthydol** [comment]
@phirefly @davoodharun This is a story that can be done by Steven under Haru's direction.

**Comment by simplyshang** [comment]
@mmurthydol @phirefly @davoodharun Just an FYI, I included the link we needed in the text edits and was just showing Steven, so hopefully that can act as a point of reference for this, too.

**Comment by EStriegel** [comment]
Adding to `Sprint 6 (tentative)` since this work is a part of the text update story (#469)

**Comment by phirefly** [comment]
Verified with @EStriegel and @binwang89. Moving to `Done`
