### ISSUE TITLE
Bug: Clicking on the `Account` link on the dashboard results in the browser hanging

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#472]

**Comment by phirefly** [comment]
When complete, please unblock #206 and notify @EStriegel

**Comment by davoodharun** [comment]
@phirefly after discussing with a few other people, we don't actually have a working account page. I think that page is in progress. The account link was still broken though. I fixed it to how it was working earlier  by linking it to the changePassword page. A few of the routes were broken after moving routes out of the main app.js file.

**Comment by EStriegel** [comment]
Confirmed Account link takes user to Change Password page in QA.  Moving to `Done`
