### ISSUE TITLE
UI - As a user, I would like my Full Name to be captured as First Name, Last Name to prevent data quality issues

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#490]
related to #491 

## Acceptance Criteria

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

#### Functionality

- [x] Assurances (#440)
https://preview.uxpin.com/d217c031c2dafec225a80652ee085d04ccafc106#/pages/78317797/simulate/sitemap

- [x] Application Info - Application Contact Person
https://preview.uxpin.com/d217c031c2dafec225a80652ee085d04ccafc106#/pages/78317799/simulate/sitemap

- [x] Wage Data - Hourly - Prevailing Wage Survey: Source Employer
https://preview.uxpin.com/d217c031c2dafec225a80652ee085d04ccafc106#/pages/78317802/simulate/sitemap

- [x] Wage Data - Piece Rate - Prevailing Wage Survey: Source Employer
https://preview.uxpin.com/d217c031c2dafec225a80652ee085d04ccafc106#/pages/78317805/simulate/sitemap

- [x] WIOA - List Workers 
https://preview.uxpin.com/d217c031c2dafec225a80652ee085d04ccafc106#/pages/78317826/simulate/sitemap

#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by EStriegel** [comment]
Confirmed complete.  Moving to `Done`
