### ISSUE TITLE
API - As a user, I would like my Full Name to be captured as First Name, Last Name to prevent data quality issues

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#491]
see #490 for all places where full name is being split to first/last name. Ensure that all API/DB calls/columns are changed accordingly.

## Acceptance Criteria

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

#### Functionality

- [ ] Ensure no API/DB contain Full Name, but split to First Name, Last Name.
- [ ] Document/Communicate any missing specs so UI story can be changed accordingly as well.
#### Accessibility
N/A

**Comment by EStriegel** [comment]
Moving to `Done` - #490 is complete, and #651 captures remaining work.
