### ISSUE TITLE
UI: As an employer I would like to upload *all* current SCA wage determinations

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#495]
Related to #496 

## Acceptance Criteria

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

#### Functionality
- [x] Perform  client side validation to ensure only one attachment is allowed for all attachment types except for SCA attachments for the Employers section *only*!!! SCA attachments for Wage Data section Hourly, Wage Data Section Piece Rate should *only* allow *single* attachments. Please view image below for where these SCA attachments are.
________________________________________

Employer Section:
User must be allowed multiple SCA uploads if they answer yes to, “Does this employer currently hold any contracts covered by the McNamara-O’Hara Service Contract Act (SCA)?”
![image](https://user-images.githubusercontent.com/25183303/36003794-8244992e-0cfd-11e8-8d27-1344b7a66180.png)
________________________________________

Wage Data Section / Hourly:
User is only provided single upload if they answer “SCA Wage Determination” to, “Which method did the employer use to determine the prevailing wage for the job or contract identified above?”

![image](https://user-images.githubusercontent.com/25183303/36003820-983879da-0cfd-11e8-97e3-d89973684b3a.png)
________________________________________

Wage Data Section / Piece Rate:
User is only provided single upload if they answer “SCA Wage Determination” to, “Which method did the employer use to determine the prevailing wage for the job or contract identified above?”
![image](https://user-images.githubusercontent.com/25183303/36003851-ba44b728-0cfd-11e8-8f75-a61df197e534.png)

- [x] show all the uploaded SCA documents
- [x] Do not allow multiple uploads for other attachment types. @EStriegel please confirm this requirement by removing this note to you :)
- [x] Each uploaded SCA document must support the same functionality as a single SCA document (delete, messaging, etc.)
- [x] API changes to accomodate multi-file upload
- [x] changes to pdf gen to accomodate multi-file upload
>**NOTE**: UI for the feedback message is noted in user story #197 

#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by davoodharun** [comment]
@EStriegel, can we confirm the following criteria for acceptance?

```
Do not allow multiple uploads for other attachment types. 
```

**Comment by jmmcnj** [comment]
Ready for merge waiting on login workflow merge final, @davoodharun 

@dciceman will test pdf upload/api any changes

Before PR/merge - end to end test

**Comment by mmurthydol** [comment]
Moved to in progress. Requirement omission defect that needs to be fixed.

**Comment by EStriegel** [comment]
Verified complete.  Moving to `Done`
