### ISSUE TITLE
API: As an employer I would like to upload *all* current SCA wage determinations

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#496]
Related to #495 
This story blocked by  #190 

## Acceptance Criteria
- [x] Support #495 requirements

#### Functionality
- [x] Implement (?internal? generic?) API upload method that supports multiple file uploads. @dciceman Discuss with Madhu. Unless File API is componentized, not possible to support generic multiple file upload method.
- [x] Implement an API upload method that supports multiple uploads for SCA attachment type, & single upload for all other attachment type.
- [x] Multiple attachments need to be shown in the consolidated PDF that is generated.
- [x] Update DB schema as necessary. @dciceman Talk with Madhu about DB schema (attachments table, attachment type, allow single/multiple attachments, etc.)
- [x] In the Attachment Upload Web API Method: Perform API method validation to ensure only one attachment is allowed for all attachment types except for SCA attachments for the Employers section. SCA attachments for Wage Data section Hourly, Wage Data Section Piece Rate should only allow single attachments.
- [x] Create an Attachment Table with following columns: Integer/Long Identity column, GUID for Attachment-Id, Blob(5MB) column to store the Pdf Blob. This table is to be used in future implementation to replace file attachments with table blobs.

#### Accessibility
N/A

**Comment by dciceman** [comment]
Duplicate task. #495 - As an employer I would like to upload *all* current SCA wage determinations
