### ISSUE TITLE
Bug: Wage Data show duplicate breadcrumbs 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#497]
Bug Description
In  the 14c application, there are duplicate breadcrumbs displayed in Wage Data page. 

## Acceptance Criteria

Please remove the 2nd breadcrumbs from the page. 

![duplicate breadcrumbs](https://user-images.githubusercontent.com/25330625/34062412-74a6e61e-e1ba-11e7-94c0-37c4295a7b7b.JPG)

**Comment by phirefly** [comment]
@binwang89 will verify this is an IE bug

**Comment by binwang89** [comment]
@phirefly it is happening in Both IE/Chrome, INT/QA site both.

**Comment by davoodharun** [comment]
@binwang89 this is an easy fix. I will create a pull request shortly. I've assigned myself the issue and added an estimate

**Comment by binwang89** [comment]
@davoodharun sounds good.

**Comment by EStriegel** [comment]
Confirmed fix has been made.  Moving to `Done`
