### ISSUE TITLE
Bug: Slider clears out completed employee fields based on previous employee entry 

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#499]
- [ ] Sabrina Steel, Chrome, TCFW09, Step 7: When user gets to Review/Submit page, message indicates error on Worksite and Employees section.  Errors are within employee data and show empty fields that user did already complete.  System seems to be clearing out completed fields. 

EXAMPLE ONE: Empty fields are: "Average earnings per hour for this employee", "prevailing wage rate for the job identified" and "productivity measure/rating for job described above" (error for missing hourly rating, even if n/a piece rate is still selected).

EXAMPLE TWO: Empty fields are: "Average earnings per hour for this employee", "prevailing wage rate for the job identified" and "commensurate wage rate for the job identified".

Error is a loop - System continues to clear out data.  Unable to submit application.

- [ ] Helen Applewhaite, IE, TCFW09, Step 7: When user gets to Review/Submit page, message indicates error on Worksite and Employees section.  Errors are within employee data and show empty fields that user did already complete.  System seems to be clearing out completed fields. 

Employee #1: Empty fields are: "Average earnings per hour for this employee", "prevailing wage rate for the job identified", "productivity measure/rating for job described above" and "commensurate wage rate for the job identified".

Employee #2: Empty fields are: "prevailing wage rate for the job identified" and "productivity measure/rating for job described above" 

Employee #3: Empty fields are: "Average earnings per hour for this employee", "prevailing wage rate for the job identified", "productivity measure/rating for job described above" and "commensurate wage rate for the job identified".

Employee #4: Empty fields are: "prevailing wage rate for the job identified" and "productivity measure/rating for job described above" 

Employee #5: Empty fields are: "Average earnings per hour for this employee", "prevailing wage rate for the job identified", "productivity measure/rating for job described above" and "commensurate wage rate for the job identified".

**Comment by binwang89** [comment]
tested at QA site, and it looks good, I have submitted the application.
