### ISSUE TITLE
Bug: As a user, I would like application to provide default values to fields that do not apply to me. 

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#500]
Usability must be based on principle of least surprise. User shouldn't have to enter data for fields that do not apply to them. 

- [ ] Sabrina Steel, Chrome, TCFW11, 3: Application does not indicate that user should enter 0 for 
      categories (CRP, Hospital, SWEP, Business) where they do not employ ww/d.  Error occurs on 
      review/submit if categories are left blank.
- [ ] Eliminate similar errors in other places TODO @EStriegel where else do we find this pattern.
- [ ] Application must let user know clearly which fields are required and disable fields with default values 
       for the fields user is not responsible to enter data.

**Comment by EStriegel** [comment]
Closing - #469 implements this change.
