### ISSUE TITLE
Bug: Phone number & Certificate number fields aren't Validating correctly.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#502]
- [x] Previous certificate number should only allow xx-xxxx-#-xxx options S, H, E, P only - xxx.
       Syntax: 12-34567-H-890 (options: S, H, E, P)
- [x] Validate phone number allowing common phone syntax. 123-345-6789, (123)-345-6789, etc. Common validation RegEx expressions must be available on the web. Ask Harun as needs be. Or do some thing simple if RegEx expression validation is not implemented.

~~Update help fields of the fields to display allowed syntax~~

**Comment by EStriegel** [comment]
@davoodharun Does not appear that either of the above requirements have been completed.  Moving to `In Progress`

![image](https://user-images.githubusercontent.com/19496579/36117558-1a2c83ca-1008-11e8-843b-b43581b0887c.png)

-------
![image](https://user-images.githubusercontent.com/19496579/36117590-37bc5ad2-1008-11e8-8b38-c2b3d7e37786.png)

**Comment by EStriegel** [comment]
@davoodharun @mmurthydol What we need is for the certificate number field on the "Register an Employer" page to be identical to how the application behaves for the certificate number question on the Application Info section (must answer yes to "Has this employer ever previously held a 14(c) certificate?" to see the certificate number field).  Screenshot also below.

![image](https://user-images.githubusercontent.com/19496579/36162592-deb8b5d6-10b4-11e8-9c76-5fc58cea5b84.png)

**Comment by PrabhakarThummalaDOL** [comment]
@EStriegel 
Fixed the problem. 
(I'll give a demo.)

**Comment by PrabhakarThummalaDOL** [comment]
@binwang89 @EStriegel Please test this.

**Comment by binwang89** [comment]
@PrabhakarThummalaDOL @EStriegel I tested both certificate and telephone number, they look good. 
please see below screenshots:
![image](https://user-images.githubusercontent.com/25330625/40952623-ef6dfeb2-6849-11e8-9909-f547837a7328.png)

![image](https://user-images.githubusercontent.com/25330625/40952637-fe6f57e4-6849-11e8-824b-abfca7e5b312.png)
