### ISSUE TITLE
Bug: A null data table row is created after creating an employee

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#503]
- [x] Add a cancel button to fix the problem. Rest of items below do not apply.
- [ ] AIS Dev: Please look at this defect if problem was reproduced by DOL, If not please alert DOL.
- [ ] DOL: DIT: Reproduce the error @binwang89: Michelle, please work with Troy. Troy's existing application should *not* be removed from the DB. We want to reproduce the error on someone else's account (or a new email account). May be Troy is the best person to reproduce this error and record the steps.  

- [ ] DOL: DIT: @binwang89 Please add your notes here if problem reproduced or not. And then assign this story to Harun. If problem not reproduced, discuss internally to close story or not. 

- [ ] AIS Dev: Defect confirmed if gone past previous two steps. Fix the defect. Most likely there is a hidden field that might be creating other defects?

**Comment by jmmcnj** [comment]
need to address button to cancel, where it should be placed and what the text should be on the buttons - meeting to follow with @davoodharun @simplyshang and @EStriegel

**Comment by EStriegel** [comment]
Complete.  Moving to `Done`
