### ISSUE TITLE
Bug: Review and Submit page - Submit button is enabled and active when validation errors are present on the page

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#504]
- [ ] Michelle, Chrome, TCFW-10, Step 8: Review and Submit page - Submit button is enabled and active when validation errors are present on the page.

**Comment by phirefly** [comment]
@mmurthydol Check with David to verify the server side is implemented

**Comment by EStriegel** [comment]
Screenshot from 3/6/18

![image](https://user-images.githubusercontent.com/19496579/37051311-173c12a0-2144-11e8-94f4-2eef13afab0d.png)

**Comment by EStriegel** [comment]
@NathayaMDOL Please discuss with @PrabhakarThummalaDOL 

Button should be disabled until all sections are completed.

**Comment by NathayaMDOL** [comment]
This issue has been fixed. Please see screenshot below.
Branch "whd-aqa-504-nmankong-reviewsubmitpage-sectionnotcompleted-disabledsubmitbtn"

![504-disabled submit button](https://user-images.githubusercontent.com/40499717/43146404-2d1adc2e-8f2f-11e8-82f2-642232516a48.png)

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
