### ISSUE TITLE
Bug: Review and Submit page - The Next Button must not be present and only "BACK" button must be presented.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#505]
- [ ] DOL: @EStriegel to confirm placement of buttons and document here. 
- [ ] AIS: Steve please work with Harun if fix not obvious. Should be straight forward.
- [ ] Michelle, Chrome/IE, TCFW-10, Step 8: Review and Submit page - The Next Button should not be there after the "Public Burden Statement", Remove "Next" from Review section and bring "BACK" button above Public Burden statement.

**Comment by binwang89** [comment]
@mmurthydol @EStriegel please see the screenshot below for this error. 
![image](https://user-images.githubusercontent.com/25330625/35004202-2f4ab3ae-fabd-11e7-9a68-7017f01f52cd.png)

**Comment by joebhaktiarDOL** [comment]
https://github.com/18F/dol-whd-14c/pull/672

**Comment by EStriegel** [comment]
Confirmed complete.  Moving to `Done`
