### ISSUE TITLE
Error on Review Submit page sends user back to Work Sites & Employees page without highlighting the specific table with the error.

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#507]
Visual examples provided by @simplyshang on 1/12:

https://preview.uxpin.com/da3326850f708e4e85d1e563c60e4f277fd2eee1#/pages/79393716/simulate/no-panels?mode=i

1. Work Site Table - indicates error on a work site
2. Work Site Table - indicates error on an employee
3. Work Site Table - indicated error on both a work site & Employee
4. Employee Table - indicates which specific employee has error(s)

----
Story also related to: #8; Please review story 8 as well prior to working on this story (pertains to missing validation). Specifications for this story were discussed in 1/11 meeting. Spec below can be safely ignored.

@EStriegel This is a generic problem in our current design/implementation not just for the error reported below. We need an implementation simple and acceptable enough for milestone 1. Option 2 is cheapest. Reviewed code for Option 3.  

This story is also related to #501. Ideally both stories wish could be done for milestone 1.  We can't afford to implement this story for milestone 1 either except for option (2). Hard choices to make...

Our implementation options:
1. Do nothing
2. Provide a generic simple header message on each page that outlines all the hidden clicks where data could be potentially needs to be validated
3.  The whole kaboodle - How we should have designed/implemented validation in the first place :
  - [ ] Every pop up (not page) must not allowed to be closed if all the required fields are not provided. 
  - [ ] Every page must indicate all the required fields with a "*" even if they are all the fields.
  - [ ] Every page upon clicking "Next" or "Previous" must display/list Summary Validation errors for that 
         page (top when arriving to that page &/or bottom when leaving from that page). Each field also 
         must indicate missing validation with appropriate highlighting and/or additional text. Application 
         must include verbiage for the user to understand they are allowed to move across pages.
  - [ ] On the submit/review page, validate information must continue to display. 
  - [ ] Reviewed code. Looks like Angular Validation service contains validation functions per page. Yay 
         but time consuming nevertheless. These validation methods can be used to write validation errors 
         per page as outlined above. 
        
**Steps to duplicate**:
1. Leave this question blank: `Which method did the employer use to determine the PW for the job or contract identified above?`
2. Click to Review and Submit
3. View the issue

`Case TCFW08, Step 4`

**Comment by EStriegel** [comment]
![image](https://user-images.githubusercontent.com/19496579/34219823-75ff6f08-e580-11e7-9010-2e22f0519684.png)

**Comment by EStriegel** [comment]
Completed.  Moving to `Done`
