### ISSUE TITLE
Implementation: Indicate required fields within the application

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#509]
Implementation for #342 

Since the majority of fields are required, text will be added to alert users that all "fields are required unless indicated as optional". This should be below the heading of each page of the application:
![image](https://user-images.githubusercontent.com/19496579/34690750-5330ab10-f488-11e7-9acf-185059061fb1.png)

Here's an example of a field labeled as optional:
![image](https://user-images.githubusercontent.com/19496579/34690756-57f5fa2e-f488-11e7-927c-1f34e688ed06.png)

**Comment by mmurthydol** [comment]
done as part of #469
