### ISSUE TITLE
Bug: Email - TCRW-02/3, When entering a email. Email is case sensitive

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#512]
@EStriegel This defect can cause various application support issues and is well worth fixing. The API effort isn't worth much. UI effort is not high either. (Steven can do the work I believe).

Bug Description:
Email -   When entering a email. Email is case sensitive

For UI/Harun
- [x] Update Zip code field to only allow 5 digits. 
  
For API/David
- [x] All API methods must convert email to lower case before processing any logic. This step is for API/David.
- [x] @mmurthydol to provide list: user email, employer name, address, EIN
- [x] Store email in all lower case when storing to the database. Will naturally occur as a consequence of above step.

Screenshot:

![image](https://user-images.githubusercontent.com/25330625/34227383-ed5108fe-e59a-11e7-9f82-85ebbb6e2f24.png)

**Comment by mmurthydol** [comment]
DOL following up with DB2 whether DB can be configured to be not case-sensitive. Solution will depend on how db is configured.

**Comment by binwang89** [comment]
Tested and looks good now.  I moved it to "done".
