### ISSUE TITLE
Bug: TCFW-10/2, System allows entering preceding spaces (e.g., in front of the email address, and other fields).

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#514]
Bug Description:
TCFW-10/2, System allows entering preceding spaces (e.g., in front of the email address, and other fields).

Especially fields used for registration (user email, employer name, address) must not have this problem.
With those fields, problem is critical. 

**Acceptance Criteria**
- [x] Trim **all** the text fields in *all* pages in the application for blanks/tabs (prefix, suffix, between words)
- [x] API methods must do the same

**Comment by dciceman** [comment]
Duplicate task. #512 - Email - TCRW-02/3, When entering a email. Email is case sensitive
