### ISSUE TITLE
Bug: TCFW-10/3, Employer > Employer Information:  System is not validating the Zip Code field. I entered all zeros intead of entering numbers (e.g., 20024). 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#515]
Bug Description:
Employer > Employer Information:  System is not validating the Zip Code field. I entered all zeros instead of entering numbers (e.g., 20024).

**Comment by mmurthydol** [comment]
Deferred. Cannot validate zip code till we hook up to address validation service.
