### ISSUE TITLE
Bug: UI must ensure a new application is not created if one is already in progress

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#517]
This functionality is most likely in the process of being implemented with the new login workflow.

#### Functionality

- [x] UI uses an API call that returns all applications/status for the currently associated employer for the logged in user. Use an API to get a list of employers associated with the logged in user if necessary.
- [x] Display application info for the said employer as follows:
       - each row of data in data table will contain, "Employer ID", "Employer Name", "Application Creation Date", "Application Last Update Date", "Application Status", "Action" 
- [x] "Action" column must contain an action button as described below.
       - All applications from the previous calendar years must display "Download application" button if 
          submitted successfully. Harun, Ask DOL what should happen for other application status states.
          @EStriegel How does business treat applications from previous years that have not been 
           submitted? Or submitted but not processed by CPS?
       - For current calendar year, if application is in progress must display "Continue with application" else 
          "Create New Application" 

#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by binwang89** [comment]
just tested in INT, i can create a new application when there is one already in progress. 
please see the below screenshot
![image](https://user-images.githubusercontent.com/25330625/35643004-ec7ec2fe-0692-11e8-824c-72e0738514d4.png)

**Comment by EStriegel** [comment]
Confirmed.  Moving to `Done`
