### ISSUE TITLE
Bug: Name of PDF attachment is not descriptive

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#518]
Currently the file name is Concatenate.Pdf and not descriptive. This makes it hard for the cert team.
Shouldn't take too long to implement.

## Acceptance Criteria
- [ ] File name must use following syntax: section-14c_<employer-name-with-hyphens>_<submission-date-with-hyphens>
Ex: section-14c_Myles-Cleaners_2017-07-29

**Comment by EStriegel** [comment]
Completed and closed.
