### ISSUE TITLE
As an Applicant, I would like a user friendly "Assurances Section" within the 226/a form

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#52]
Descripition:  Following the approved wireframes, develop the section for "Assurances" performing the following tasks.  Will not include e-signature, will be addressed in user story #44  

Tasks:
- [ ] Implement UI based on Wireframes v2
- [ ] Implement Data Modeling to support the Section of the form
- [ ] Implement the Services/API layer to support the SEction of the form

Acceptance Criteria: Review of section within 226/a form web application follows look and feel as dictated from wireframes, Technical review will meet standards as defined in QASP following 18f guidelines

**Comment by simplyshang** [comment]
Wireframes for this section:
[DOL14c-Wireframes-v2_Assurances.pdf](https://github.com/18F/dol-whd-14c/files/521954/DOL14c-Wireframes-v2_Assurances.pdf)
