### ISSUE TITLE
As an Applicant, I would like a user friendly "Application Info" Section within the 226/a form

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#53]
Descripition:  Following the approved wireframes v2, develop the section for Application Info performing the following tasks.  Does Include the instructions within the section as well as expanded areas within section, does not include validation #6  , conditional logic #9 

Tasks:
- [x] Implement UI based on Wireframes
- [x] Implement Data Modeling to support the Section of the form
- [x] Implement the Services/API layer to support the SEction of the form

Acceptance Criteria: Review of section within 226/a form web application follows look and feel as dictated from wireframes v2, Technical review will meet standards as defined by QASP and 18f guidelines

**Comment by simplyshang** [comment]
Wireframe for this section: 
[DOL14c-Wireframes-v2_Assurances.pdf](https://github.com/18F/dol-whd-14c/files/521910/DOL14c-Wireframes-v2_Assurances.pdf)
