### ISSUE TITLE
Add "Show Help for All Items" link to employee data slider

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#531]
Add link to this page:

![image](https://user-images.githubusercontent.com/19496579/34417250-715cdb3e-ebc5-11e7-8934-d1bbb511d7eb.png)

 - [ ] Ensure all help text items are open ONLY on slider and NOT on main page

**Comment by binwang89** [comment]
tested it, looks good 
![image](https://user-images.githubusercontent.com/25330625/35641488-52dda79a-068e-11e8-9fb4-65d2f859d370.png)
