### ISSUE TITLE
PDF Edits

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#534]
- [x] For every yes/no question throughout the application, the PDF should mirror the applicant's answer (currently showing true/false).  

- [x] Create a unique name for each generated PDF - "14c Application Submission_ER Name_State Abbreviation_Calendar Year of Submission"

- [x] Employer Section: Remove "Not Provided" that appears under question, "Provide the number of workers with disabilities employed at subminimum wages for the most recently completed fiscal quarter in each of the following categories:" 

- [x] Employer Section, Government Contracts: Fix conditional logic error.  When applicant answers either "No" or "No, but intend to within the next two years", the two subsequent questions should not show in the PDF (What is the total number of current SCA-covered contracts under which workers with disabilities are employed and earning subminimum wages? and Attach copies of all current SCA Wage Determinations for those contracts on which workers with disabilities are employed and earning subminimum wage.)

- [x] Wage Data Section: In response to the question, "How did the employer pay subminimum wage rates to workers with disabilities in the most recent fiscal quarter?", when an applicant chooses only one type of payment (hourly or piece rate (not both)), the PDF is still showing both sets of questions with “Not Provided” as the answer for each question of the payment type not selected.  

- [x] Wage Data Section, Prevailing Wage Survey option, Add a Source Employer: Include labels for each field in PDF

- [ ] Work Sites & Employees, Work Site Employees: Do not allow rows to break across pages. (We are not going to work on this issue per Madhu)

**Comment by mgwalker** [comment]
Preventing page breaks within elements might be possible with the [`page-break-inside` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-inside) set to `avoid`.

**Comment by EStriegel** [comment]
@dciceman Hi David - In the sample PDF you submitted on 1/9, the only edit I cannot confirm is: "Wage Data Section, Prevailing Wage Survey option, Add a Source Employer: Include labels for each field in PDF"

In the sample PDF, 'SCA Wage Determination' is the response to "Which method did the employer use to determine the prevailing wage for the job or contract identified above?".  In order to confirm, the answer would need to be 'Prevailing Wage Survey' and a couple source employers would need to be entered.

**Comment by EStriegel** [comment]
Confirmed all edits completed.  Moving to `Done`
