### ISSUE TITLE
Employee Data Sliding Panel - Close button text

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#538]
Work Sites & Employees page > Click "Add Employee" to open sliding panel.
https://dol-whd-section14c-int.aisdemos.com/#!/section/work-sites

**Bug found by OCIO tester:**
The ( X ) close icon hidden text should say something more meaningful, such as "Close Add Employee Panel". (Currently it just says "Close")

**Comment by ltsheu** [comment]
These changes were completed earlier today. Waiting for PR #547 to be merged.

**Comment by ltsheu** [comment]
@binwang89 These changes are complete and ready for review. Please note that the text changes are screen-reader only. Sighted viewers will still see an "X" for the close button in the sliding panel.

**Comment by binwang89** [comment]
@ltsheu I have reviewed the accessibility tree screenshot in your email and i have moved this user story to next pipeline. Thanks.
