### ISSUE TITLE
Employee Data Example Panel - Meaningful Links

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#539]
Work Sites & Employees page > Click "Show Me an Example" to open Example sliding panel.
https://dol-whd-section14c-int.aisdemos.com/#!/section/work-sites

**Bug found by OCIO tester:**
The Link Content should be unique and meaningful. Example One (example of what?)

**Suggested solution:**
Add additional screen reader-only text to the "Example One" and "Example Two" toggle links to clarify what view is being toggled. Use `<span class="hide">` for screen reader only text.

**Comment by ltsheu** [comment]
These changes were completed earlier today. Waiting for PR #547 to be merged.

**Comment by ltsheu** [comment]
@binwang89 These changes are complete and ready for review. Please note that the text changes are screen-reader only. Sighted viewers will still see "Example One" and "Example Two". Use screen reader testing tools to see the added text.

**Comment by binwang89** [comment]
@ltsheu I have reviewed the accessibility tree screenshot in your email and i have moved this user story to next pipeline. Thanks.
