### ISSUE TITLE
Error Messages - Color Dependence

### ISSUE THREAD

**Issue by ltsheu** [18F/dol-whd-14c#540]
**Pages affected:** ALL

**Bug found by OCIO tester:** 
The error messages are in red, causing attention to the fields that need to be completed. Suggest adding a star for color-blind people. 

- [x] Per discussion with Liz, the existing exclamation point icon will be used instead of a star

**Comment by binwang89** [comment]
@ltsheu Please provide the estimate for this issue. Thanks

**Comment by ltsheu** [comment]
@binwang89 This bug is ready for review. I added an exclamation point icon to the form field error messages.

**Comment by binwang89** [comment]
@ltsheu the INT site is not available and Harun is working on it.  I only looked at the QA site. 
the QA site is also show the red color with exclamation point.  If that is what you have changed, that is fine and i will move it to next pipeline. 
![image](https://user-images.githubusercontent.com/25330625/34807890-2f0316ba-f659-11e7-9fc6-2a6b080fcb4b.png)

**Comment by ltsheu** [comment]
This update was for form field error messages when reviewing the form. Here is a screenshot an error message with the new exclamation point icon.

![formfielderrormessageicon](https://user-images.githubusercontent.com/31778248/34832644-773acccc-f6bb-11e7-8b3d-719b96e4a083.png)

From the Review & Submit page, click on any "Edit Responses" button to go to each page and see the error messages with the new (!) icon.

**Comment by binwang89** [comment]
@ltsheu Since i can't login to INT site, the screenshot that you sent to me has demo the remediation.  
Thank you very much.
