### ISSUE TITLE
Application yes/no questions should display answers as yes/no

### ISSUE THREAD

**Issue by davoodharun** [18F/dol-whd-14c#541]
## Acceptance Criteria

- [ ] All yes/no questions should display answers as yes/no and NOT true/false on all datatables

**Comment by mgwalker** [comment]
I don't recall offhand how the data tables populate, but this might be a good place for a new filter that takes a bool and returns a string `yes`/`no`?

**Comment by phirefly** [comment]
Began testing this and ran into an Employer Registration issue: https://gsa-tts.slack.com/archives/C70SH3Q1M/p1518209311000401

**Comment by EStriegel** [comment]
Confirmed complete, moving to `Done`
