### ISSUE TITLE
Bug:The Link Content should be unique and meaningful

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#546]
#537 -  the default button names must be changed to a custom string in the Data Tables initialisation JS code. Based the estimation from @davoodharun,  it looks like just updating text.  @davoodharun please work on it. 
#538 -  it would take less than 1 hour. @ltsheu please work on this one 
#539  – it would take less than 1 hour. @ltsheu please work on this one.

**Comment by ltsheu** [comment]
These items are all complete and waiting for PR #547 to be merged.

**Comment by ltsheu** [comment]
@binwang89 This epic is complete and ready for review. The associated tasks have been completed. #537, #538, #539.

**Comment by binwang89** [comment]
@ltsheu I have reviewed the accessibility tree screenshot in your email and i have moved this user story to next pipeline. Thanks.

**Comment by phirefly** [comment]
@binwang89 I'm assigning to you to do QA on this.

**Comment by binwang89** [comment]
tested done, moved to next pipeline.
