### ISSUE TITLE
As an Applicant, I would like a user friendly "Wage Data" Section within the 226/a form

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#55]
Descripition:  Following the approved wireframes v2 (see attached wireframe pages), develop the section for "Wage Data" performing the following tasks.  Does include the instructions for the section, does not include #9, and the validation from user story #6 and also the file upload user story #15 

Tasks:
- [ ] Implement UI based on Wireframes
- [ ] Implement Data Modeling to support the Section of the form
- [ ] Implement the Services/API layer to support the SEction of the form

Acceptance Criteria:  Review of section within 226/a form web application follows look and feel as dictated from wireframes v2, Technical review meets QASP standards from 18F

**Comment by simplyshang** [comment]
Wireframes

Scenario 1: User makes a single choice (either Hourly or Piece Rate), and then chooses Prevailing Wage Survey for wage determination method:
[DOL14c-Wireframes-v2_WageData_Single_PrevailingWageSurvey.pdf](https://github.com/18F/dol-whd-14c/files/522115/DOL14c-Wireframes-v2_WageData_Single_PrevailingWageSurvey.pdf)

Scenario 2: User chooses both, and then chooses Alternate Wage Data for wage determination method under Hourly:
[DOL14c-Wireframes-v2_WageData_Double_AlternateWageData.pdf](https://github.com/18F/dol-whd-14c/files/522116/DOL14c-Wireframes-v2_WageData_Double_AlternateWageData.pdf)

Scenario 3: User chooses both, and then chooses SCA Wage Determination for wage determination method under Piece Rate:
[DOL14c-Wireframes-v2_WageData_Double_SCAWageDetermination.pdf](https://github.com/18F/dol-whd-14c/files/522118/DOL14c-Wireframes-v2_WageData_Double_SCAWageDetermination.pdf)
