### ISSUE TITLE
Bug:  Work Site Expanded View

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#551]
**Acceptance Criteria**
- [x] Fix work site data table & any/all other data tables that  display Boolean values as Yes/No instead of true/false.
- [x] Work site data table: reorder the fields (Work Site Type at the top) and fix answer for that field (Type of Establishment instead of "27"). 
- [x] Please ensure the worksite data table visually/verbally conforms to the UX spec

Current work site expanded view:
![image.png](https://images.zenhubusercontent.com/57e9239095e42b6c5ba972b8/7498672c-e48d-4961-a8e1-f022e488644d)

Should look like this:
https://preview.uxpin.com/dbef3aaee7fc9fac51dc1d087e1f9180f3610ab3#/pages/79282437/simulate/no-panels?mode=i

**Comment by mmurthydol** [comment]
@EStriegel Is the defect that we need Yes/No instead of true/false?

**Comment by EStriegel** [comment]
@mmurthydol @davoodharun Yes, one of the defects is yes/no instead of true false.  There is also the need to reorder the fields (Work Site Type at the top) and fixing the answer for that field (Type of Establishment instead of "27")

**Comment by EStriegel** [comment]
Story not complete, screenshot below.
- Expanded view has fields in incorrect order.
- Yes/No should be capitalized

![image](https://user-images.githubusercontent.com/19496579/36613060-535ec5b2-18a6-11e8-8b23-9232ccd13ae8.png)

**Comment by NathayaMDOL** [comment]
The story has been fixed and completed, screenshot below. 
![image](https://user-images.githubusercontent.com/40499717/42713607-0c61e924-86be-11e8-8d8b-a983278248d8.png)

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
