### ISSUE TITLE
Text Edit: Review & Submit page

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#552]
Replace:
"We've checked your responses from each section to make sure there were no errors or missing information before submission."  

with: 
"We’ve checked each section to make sure you did not leave any required fields blank.  It is your responsibility to make sure that all of the information you provided is complete and accurate; failure to do so may delay the processing of the application or result in the application being denied."

**Comment by EStriegel** [comment]
@simplyshang I've assigned this to you so the update can first be made to the prototype for the OMB screenshots.

**Comment by mmurthydol** [comment]
done as part of #469
