### ISSUE TITLE
As an Applicant, I would like a user friendly "Work Sites and Employees" Section within the 226/a form

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#56]
Descripition:  Following the approved wireframes v2 (see attached wireframe pages), this will look different for 1 worksite versus many, develop the section for "Work Sites and Employees" performing the following tasks.  Does include the instructions for the section, does not include #9, and the validation from user story #6 and also the file upload user story #15
Tasks:
- [ ] Implement UI based on Wireframes
- [ ] Implement Data Modeling to support the Section of the form
- [ ] Implement the Services/API layer to support the SEction of the form

Acceptance Criteria:  Review of section within 226/a form web application follows look and feel as dictated from wireframes v2, Technical review meet QASP standards from 18F

**Comment by simplyshang** [comment]
Wireframes for this section:
[DOL14c-Wireframes-v2_WorkSitesAndEmployees.pdf](https://github.com/18F/dol-whd-14c/files/522123/DOL14c-Wireframes-v2_WorkSitesAndEmployees.pdf)
