### ISSUE TITLE
Provide Admin page support to manage confirm email, password reset problem

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#560]
## Acceptance Criteria

- [x] Currently when user doesn't click on email confirmation link before link expires, user will have to reach out to application support/help desk to be able to log in to the system. Upon verification, system administrator should be able to through the application resend confirmation email &/or enable the EmailConfirmed column in the Users table. 

Once logged in as a system administrator, admin page is visible that lists all the users and their roles. UI could be modified to add a (a) resend confirmation_email button (b) occassionally users still do not receive email. In this case, as an escalated next step, an additional button is provided to update the db column for the user in question. After application support verification steps of course.

The other alternative is to perform this step outside of the application through an application support change management process and update the DB directly through a patch script. 

- [x] Often users forget their password and it needs to be reset. Again after verification steps admin application will log in as system administrator to reset the password through the admin page UI. 
In the grid, on the row for the user, clicking on "Reset password" will popup a modal (Ok, cancel) with textbox x 2  (for new password). Must display the user name/email in the popup. 
Questions (may be for future): Should an email be sent?  How should password be communicated?

- [x] Users might not receive their 2FA authentication code email. Need a button to resend email; Need a button that will generate an authentication code that can be verbally specified to the user by the app support team. @dciceman added this requirement after sprint planning. Might update points accordingly.

- [x] Create "Deleted", "Disabled" boolean/bit columns in Users Table through EF Code First and ensure that all usages of Users  *inside* Web API methods will be filtered out throughout the application code. 

- [ ] Any existing WebAPI method/s that returns all users (only sysadmin role can do this today), or all users of an employer (admin role in future) must support method parameters to return all/filtered out user list. The only known instance is probably in the Admin dashboard page currently.
          #77  should address this requirement. 
#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by binwang89** [comment]
@mmurthydol Tested in both QA/INT, the whole admin page is not working.  using admin role user name/password to login, take me to change password page ( expected to land on the admin dashboard page). Clicked on the dashboard link on the top redirects to login page, resulting in  a loop.
