### ISSUE TITLE
Visual Design - Landing/Dashboard page for new login workflow

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#568]
Create a mock up (or make actual changes to the page) based on the image below and the changes suggested under acceptance criteria.

![image](https://user-images.githubusercontent.com/25183303/35018608-6bd3c800-faf0-11e7-8534-0cabc5527463.png)

## Acceptance Criteria
- [x] @EStriegel to provide actual verbiage for header titles, button names and confirm when done.
- [x] Delete "Register a New Employer"
- [x] Add Header to data table (Header Title:  "Submitted Applications"). 
- [x] Add two buttons "Start a New Application" and   "Continue Application" placed above data table of submitted apps. Please note while designing, an additional third button will be placed (now/in future) to "Clear Application and Continue". 
- [x] Reorder columns to start with Employer Name / EIN / Address columns (rather than starting with EIN).
- [x] Remove time from created/modified columns. Just show date.
- [x] Ensure data table style on this page is consistent with other data tables in the application.
- [x] Change "Last Modified" header to "Date Submitted"

#### Accessibility
> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by EStriegel** [comment]
@simplyshang @ltsheu One thing I would like to discuss before design/implementation is how we show/label the "Clear Application" button.  I'm thinking it shouldn't be as easy as starting/continuing an application, as that could cause a user to inadvertently clear an application.

**Comment by mmurthydol** [comment]
@EStriegel There should be a popup (behavior similar to Deleting uploaded attachments) with verbiage about implications from this action along with ok/cancel (whatever we are calling them) buttons.

**Comment by ltsheu** [comment]
The design and placeholder work is done, however it will be part of a PR associated with #569. Therefore I'm moving this user story to blocked until #569 is integrated.

**Comment by phirefly** [comment]
Waiting forhttps://github.com/18F/dol-whd-14c/pull/630 to test once we have the ability to register an employer

**Comment by EStriegel** [comment]
@davoodharun Missing two acceptance criteria - 
- Remove time from created/modified columns. Just show date.
- Ensure data table style on this page is consistent with other data tables in the application.

Moving to  `In Progress`
