### ISSUE TITLE
Implementation - Landing/Dashboard page for new login workflow

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#569]
Implement the landing/dashboard related changes (per #568 & whatever is left over from that story). 

Please note landing page for milestone 1 pertains itself to one employer associated with the logged in user. 

## Acceptance Criteria
- [x] Data table must *only* list applications in submitted state. That means, Action button will only be providing "Download" option in the data table.
- [x] Remove "Created At" column from the data table
- [x] "Create New Application" logic: Is enabled when application associated with the employer is neither in submitted state *nor* in "in progress" state. Confirm with business if it is OK to create a new application in this scenario (IT thinks it is desirable and a workaround for employers to submit a corrected application).  @EStriegel : Input needed.
- [x] "Continue Application" button logic: Is enabled when application associated with the employer is in progress. 

#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by EStriegel** [comment]
@mmurthydol Re: the following criteria - "Create New Application" logic: Is enabled when application associated with the employer is neither in submitted state nor in "in progress" state. Confirm with business if it is OK to create a new application in this scenario (IT thinks it is desirable and a workaround for employers to submit a corrected application). 

My input:  The "Create New Application" button should become available to a user when an application is not "in progress".  The current system will not have a status past "submitted" (no DOL staff will be changing status after review/issuance in milestone 1) and therefore all previously submitted applications will all remain in "submitted" status.  Further, from a process standpoint, if a user needs to submit an amended application, the certification team will ask for any additional documentation to be mailed/faxed to Chicago.

Let me know if you want to discuss further or if I should adjust the AC.

**Comment by ltsheu** [comment]
@davoodharun Just a reminder, as we discussed, the width issues with the data table are most likely due to it being hidden and then shown. If you employ columns.adjust() it would hopefully fix this issue. https://datatables.net/reference/api/columns.adjust()

**Comment by phirefly** [comment]
Waiting for https://github.com/18F/dol-whd-14c/pull/630 deploying to test after we can register an employer

**Comment by EStriegel** [comment]
@davoodharun Missing one of the Acceptance Criteria (Remove "Created At" column from the data table).  See additional design updates needed in #568.  Moving to `In Progress`.

**Comment by mmurthydol** [comment]
@EStriegel Liz, could you please check one more time in case this was fixed and story left in progress? Thanks

**Comment by EStriegel** [comment]
Completed.  Moving to `Done`
