### ISSUE TITLE
As an Applicant, I would like a user friendly "WIOA" Section within the 226/a form

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#57]
Descripition:  Following the approved wireframes, develop the section for "WIOA" performing the following tasks.  Does include the instructions for the section, does not include #9, and the validation from user story #6 and also the file upload user story #15 

Tasks:
- [x] Implement UI based on Wireframes
- [x] Implement Data Modeling to support the Section of the form
- [x] Implement the Services/API layer to support the SEction of the form

Acceptance Criteria: Review of section within 226/a form web application follows look and feel as dictated from wireframes v2, Technical review meets QASP standards from 18F

**Comment by simplyshang** [comment]
Wireframes for this section:
[DOL14c-Wireframes-v2_WIOA.pdf](https://github.com/18F/dol-whd-14c/files/522131/DOL14c-Wireframes-v2_WIOA.pdf)
