### ISSUE TITLE
Knowledge Transfer: Run 14c in DOL Dev environment

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#570]
#Work with mostly Harun. Will pick and choose which of these to work with for the best path forward.

## Acceptance Criteria

- [x] Web application builds & deploys without Web Pack errors in AIS Jenkins. 
       node, npm: which versions; eliminate errors: node-gyp, node-sass, python; update modules as 
       necessary. 
       Basically do enough to ensure newer versions won't kill us in the future but most importantly to 
       move towards getting this to work in DOL environment.
- [x] Web application builds & deploys to DOL Jenkins without errors. 
- [x] Web application runs fine (register, login, submit application). 
- [x] Web app can call web api, 14c web api  can call pdf api/email api
       CORS is setup; utf-8 included in ajax calls; etc.
- [x] Sync Jenkins scripts on AIS side to reflect DOL DevOps/Jenkins
       Web API is not based on locahost:3344 like URLs?
       DB projects are added to Jenkins

## Other tasks for transition

- [x] Verify availability of existing Azure environments post performance

**Comment by EStriegel** [comment]
@mmurthydol Is this a task for Sprint 0?

**Comment by mmurthydol** [comment]
Yes

**Comment by EStriegel** [comment]
Completed per @mmurthydol.  Closed.
