### ISSUE TITLE
Help Screen Implementation:  Follow guidance from UX prototype

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#571]
https://preview.uxpin.com/5955e8a6afd15529d8967c143dbba46439f251ba#/pages/77595079/simulate/sitemap

Dependent on content from #156

**Comment by mmurthydol** [comment]
Most likely this page doesn't work.

Message from Harun: 
realizing now that there is a high probability that the help page will not work as expected. I forgot David made edits to the env.js file that I need to reflect in Jenkins and the env.js file in the deploy folder

**Comment by EStriegel** [comment]
Help Page is functional, but seems to be missing the DOL email address and phone number.  

Note - both the phone number and email address are placeholders until we figure out the app support process.

**Comment by mmurthydol** [comment]
Not for AQA

**Comment by mmurthydol** [comment]
@EStriegel @binwang89 Please test when you can.
