### ISSUE TITLE
Bug: New login workflow user registration page validation errors display at page load time

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#576]
All the fields display validation errors at page load time even before the user had a chance to enter data.

![image](https://user-images.githubusercontent.com/25183303/35135927-4740ae4e-fcae-11e7-9fb4-25c04a06f21d.png)

## Acceptance Criteria
- [ ] @EStriegel and @simplyshang Please review requirements below.
- [ ] Given that password fields are validated at the field level (unlike the rest of the application which probably validates at the page level - see #507), validation on this user registration /login page must occur after user focus enters and leaves the control, and only then the validation error for that control must be displayed.
- [ ] If there is any validation error on this page, "Register" button must not be enabled. 
- [x] Server side API Register method also must enforce the same client side validation logic. In other words, hackers must not be able to register a user with invalid data using the API method. This last requirement will be fulfilled by @dciceman 

#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by davoodharun** [comment]
@mmurthydol this was my fault -- I forgot to remove this. It is removed in #581

**Comment by phirefly** [comment]
@simplyshang @EStriegel I just noticed this still needs your feedback. Sounds like a reasonable solution.

**Comment by simplyshang** [comment]
@phirefly I agree with the approach. @davoodharun did the placement of the validation message get corrected? It should be between the label and input, and not below the input. 

Here's an example:
![example-validaiton](https://user-images.githubusercontent.com/1373592/35405529-70bd18b8-01d4-11e8-93eb-464a395b373e.png)

**Comment by binwang89** [comment]
tested in INT. it is okay now. 
![image](https://user-images.githubusercontent.com/25330625/35643479-6b82420a-0694-11e8-93a7-b1a6d1a03f8d.png)

**Comment by EStriegel** [comment]
Complete.  Moving to `Done`
