### ISSUE TITLE
Bug: New login workflow: User registration Account confirmation message is missing

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#577]
When a user registers and clicks on the confirmation email link, user is redirected to the login page. However there is no visual clue that the user's account is confirmed. 

## Acceptance criteria ##
- [x] Per Ux specification for login workflow, upon clicking on the confirm email link, user must be directed to an "Account confirmed" page (via the banner page). On the account confirmation page, there is a link when clicked user be redirected to the login page. 

- [x] @dciceman Not sure if Account Confirmed page has been created or not. Will need to speak to @davoodharun. Please include me to shadow when you make this change for KT or in conversation/s with Harun. Thanks.

Uxpin UX specification link that shows the design for account confirmation page: fohttps://preview.uxpin.com/d217c031c2dafec225a80652ee085d04ccafc106#/pages/78317784/simulate/sitemap?mode=i

- [ ] Please note banner page is a precursor to all entries in to 14c from a security perspective regardless of which way we enter the application. The banner page was not part of the Ux spec as it wasn't defined separately.  @EStriegel FYI. 

- [ ] DOL header/footer required
- [ ] Needs 508 compliance

**Comment by davoodharun** [comment]
This was a bug that came about after new login workflow implementation. The account crated dialog existed previously but was inadvertently disabled with the work for the new workflow. I have fixed this issue in #581

**Comment by mmurthydol** [comment]
Thanks Harun for the fix and also the explanation (that helps!) :)

**Comment by EStriegel** [comment]
User does not currently see the banner when clicking on the link in email confirmation.  Believe this is a security requirement.  Moving to top of backlog. @mmurthydol

**Comment by mmurthydol** [comment]
@EStriegel You meant  banner page correct? Could you also please check if DOL header/footer are missing? I expect that as well.
@binwang89 Michelle, could you please check if this page is 508 compliant if not already?
Thanks

**Comment by EStriegel** [comment]
@mmurthydol So when you create create a user, and click the confirmation link, it takes you to the account confirmed page.  There's a link to log-in, which takes you back to the landing page.  My understanding is that when the user clicks the confirmation page, they need to see the banner page before the account confirmed page.  (The current banner page that you see when you open the QA link has the header/footer)
