### ISSUE TITLE
Login Workflow: 14c pages display EIN instead of Employer name

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#578]
@dciceman please include Madhu when scoping this work with Harun and when making the change.

@EStriegel Please include a screenshot or a Ux UxPin spec.
 
#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by dciceman** [comment]
@EStriegel Can you please send me a screenshot for this change?

**Comment by EStriegel** [comment]
Confirmed Employer name shows instead of EIN at top of application pages.  Moving to `Done`
