### ISSUE TITLE
Bug: Error on submission for some users though validation is all green.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#587]
Not for all users: All validation green on submission page but receive a 400 error on submission. 

Didn't work for: EIN 94-9499499 Pierce.Steven@dol.gov INT environment
Worked for: @dciceman & others...

![image](https://user-images.githubusercontent.com/25183303/35460296-83df7836-02b1-11e8-9585-924079007221.png)

## Acceptance Criteria
- [ ] Submission must work for all users.
- [ ] Verify errors are logged in the error log when this scenario occurs. And verify activity log.

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

#### Functionality
- [ ] functionality criteria 1
- [ ] functionality criteria 2
- [ ] etc.

#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by phirefly** [comment]
@EStriegel and myself will try and duplicate

**Comment by phirefly** [comment]
Recommended AIS not work on this until we confirm and duplicate the issue

**Comment by jmmcnj** [comment]
Harun Initial REview: submission error when validation was passed, only happened to Steve and he happened to be the only system to experience Data Table Error from #590

**Comment by EStriegel** [comment]
QA before we close.  Should test with Renewal applications with a few work sites and multiple employees per work site.

**Comment by EStriegel** [comment]
Cannot recreate.  Successfully submitted application with 3 work sites and multiple employees per work site.  Moving to `Closed`
