### ISSUE TITLE
Employer registration successful page related issues 

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#588]
When a user registers an employer and employer registration is successful, following issues to be addressed. 

## Acceptance Criteria
- [x] It is not clear to the user what to do next. There should be a button that when clicked on will take the user to the dashboard page. 
     Button Text: "Continue to Dashboard" unless changed by @EStriegel.
- [x] Using the browser back button on this page must redirect user to the dashboard (not to the employer registration) page. Possible there is a hidden redirect from employer registration page to dashboard page.

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

#### Functionality

- [ ] functionality criteria 1
- [ ] functionality criteria 2
- [ ] etc.

#### Accessibility

> **NOTE**: Remove any accessibility criteria that don't apply to this user story.  For the full list of accessibility requirements, see [issue #198, Fully Accessible Experience](#198).

**Comment by EStriegel** [comment]
Complete.  Moved to `Done`
