### ISSUE TITLE
Bug: Submission screen language

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#591]
- [x] Verbiage on submission screen must be as specified below.
- [x] 1-800-DOL-HELP must be configured (must have entry in env.js)
- [x] "Return to Dashboard" button must be green
-------------------------------------------------------------------------------------------------------------------
Success!

Your application has been submitted.

You will receive an email confirming this submission with a PDF attachment of your submitted application. If you do not receive the email confirmation within an hour, please call our support desk at 1-800-DOL-HELP.

**Comment by jmmcnj** [comment]
Liz - to provide an update on language within this issue if not correct on screen as it is today

**Comment by EStriegel** [comment]
@davoodharun Updated submission page language below:


-----
Success!

Your application has been submitted.  

You will receive an email confirming this submission with a PDF attachment of your submitted application.  If you do not receive the email confirmation within an hour, please call our support desk at 1-800-DOL-HELP.

green `Return to Dashboard` button

**Comment by joebhaktiarDOL** [comment]
Need more clarification regarding '1-800-DOL-HELP must be configured (must have entry in env.js)'

**Comment by mmurthydol** [comment]
@EStriegel @binwang89  Please test when you can.

**Comment by binwang89** [comment]
@EStriegel @PrabhakarThummalaDOL it looks good

![image](https://user-images.githubusercontent.com/25330625/40953104-3c7dc5fa-684c-11e8-8191-54307b643eec.png)
