### ISSUE TITLE
Bug: password Rgv@178! did not work for Chrome but  worked for IE 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#592]
bug description:
Password Rgv@178! did not work on Chrome but worked on IE. Different results from different browsers with the same password. Test Case : TCRW-01
IE- 
![image](https://user-images.githubusercontent.com/25330625/35534763-7eaed7c0-050f-11e8-9e3c-f1f5af6ee643.png)

google chrome - 
![image](https://user-images.githubusercontent.com/25330625/35534976-204a9b0a-0510-11e8-872f-b6ab62ef82cd.png)

**Comment by jmmcnj** [comment]
Harun: may need to perform deep analysis of password complexity algorithms, seems to possibly have problem with front end analysis related to per stroke password strength versus upon submission only

**Comment by dciceman** [comment]
Verified by Michelle. This is not an issue any more.

**Comment by binwang89** [comment]
I think @phirefly need to test it too before we move it to done.  thanks

**Comment by mgwalker** [comment]
Part of me wants `Rgv@178!` added to a permanent password blacklist now...  kidding but also not kidding.  😛   Also, whoever first tried that password, if they use it anywhere else, they should change it.

**Comment by phirefly** [comment]
Verified on QA. Moving to `closed`. Also, changed the password to be safe. :dancing_men:
