### ISSUE TITLE
Bug: After clicking the agree button on banner, login page opens halfway down the browser

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#596]
Bug description:
After clicking the agree button on banner, login page opens halfway down the page. 
@EStriegel please provide the screenshot or information related to this issue found in QA.

Liz - attempted to recreate, seemed to be one off/anomaly possibly, might be related to screen size, test was performed on small laptop screen at the time

**Comment by jmmcnj** [comment]
Harun - possibly CSS screen resizing issue

**Comment by PrabhakarThummalaDOL** [comment]
Cannot recreate the problem.

**Comment by mmurthydol** [comment]
@EStriegel Please verify that problem doesn't exist. @PrabhakarThummalaDOL wasn't able to repro this defect.

**Comment by EStriegel** [comment]
Cannot recreate.  Moving to `Closed`
