### ISSUE TITLE
Bug: Added a value (tried multiple values) for commensurate wage and received an error without any message. Just an exclamation mark. 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#597]
Bug description:
IE/TCFW-07.  Added a value (tried multiple values) for commensurate wage and received an error without any message. Just an exclamation mark. 

@EStriegel please provide any screenshot for this issue.

**Comment by jmmcnj** [comment]
Liz - maybe related to slider, need to review

**Comment by EStriegel** [comment]
We need to try and recreate.

**Comment by EStriegel** [comment]
Cannot recreate.  Error messages on slider are correct.  Moving to `Closed`
