### ISSUE TITLE
As a Certification Team Member and as an Applicant, I want a system that performs preliminary data validation checks on fields that have predetermined or controlled answers (i.e. dates, rates, etc.), so that proper information is submitted and the certification team member spends more time analyzing the more substantive part of the application.

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#6]
Card #2 is specifying that individual fields have parameters to improve/ensure accuracy (standardized formats for dates, wages, zip codes, phone numbers, etc.) cc: @elizabethstriegel

**Comment by jmmcnj** [comment]
Requirements:
Validation-
masking certain data types, EIN, dates, dollars, zip codes, phone numbers

Form 226
Section 2 b - certificate number
Section 3 - standard address masking
	EIN mask,
	telephone, fax email
Section 4
	address mask
Section 5 -
	a - other letters only 20
Section 6 - 
	number only
Section 7 - 
	a - date time picker
	b - number 5
	c - number 5
Section 8 - 
	c - number - 3
Section 9 -
	a - if yes, number - 5
	b - more characters - 255, description - 255
	c - chart
		1st - name, address, phone number - validation for first column
		2nd - Name and title broken out
		3rd - Date
		4th - 255
		5th - dollars
		6th - 255 text
	c continued
		255 decription, alternate data source used - 255, prevailing wage - dollars , date data retrieved - date
Secditon 10
	open
Section 11
	same rules as 9
Section 12 - description is 255, wage - dollars, standard - number, piece rate paid to workers - decimal up to 5
Section 13 - 
 if checked yes, nummber 5 length
Section 14 - 
	short if checked yes, rent, meals or transportation
Section 15
Section 16 - 
	Name of worker is open, check box for y/n/nr

Form 226a
Section 2 - break down into address
Section 6 - nbumber length of 5
Section 7 - 
	a is text
	b is number - 2
	c is nummber -2 
	d is wage rate
	e is 255 text'
	f is options for acronyms
		if they chooose OT, need blank field - 20 characters
	g wage rate
	h is percentage or decimal
	i is wage rate
	j is number length of 3
	k is yes or no

**Comment by mgwalker** [comment]
@EStriegel I think this one is done and has been for a while?  Should we move it to done?

**Comment by EStriegel** [comment]
@mgwalker Yes, agree it has been completed.  Will move it over.
