### ISSUE TITLE
Research Spike: Review possible implementations of E-signature capability

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#60]
Descripition:  Research e-signature methods for web forms applications

Acceptance Criteria:  Identify acceptable (by DoL) method to implement e-signature capability

**Comment by MrMatt57** [comment]
Possible implementations (or a combination of), ordered in least to most effort/complexity:

    1. Wording on the sumbit page (By submitting this form...)
    2. A checkbox with required check validation for agree to terms.
    3. A text box for the user submitting the form to type their name.
    4. User enters a pin number at the time of signing/submission that was created during registration (similar to a password, proposed by Thomas)
    5. Handwritten digital capture of signature (Docusign or similar)

Considerations:

    1. Is the users identity important?  How can we truly identify it?
    2. Is the solution accessible? (508/WCAG2 compliant)
    3. Does self-contained version of the "contract" need to be preserved/signed?  (PDF or other read-only source).
