### ISSUE TITLE
Bug: Inactivity warning is active on pages where a user is not/was never logged in.  

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#601]
Bug description:
Inactivity warning is active on pages where a user is not/was never logged in.  
@EStriegel please provide the screenshot or information related to this issue found in QA.

**Comment by jmmcnj** [comment]
Harun Initial Review - had it working at one point, should be quick fix

**Comment by binwang89** [comment]
@mmurthydol   I did not see the inactivity warning message before i login to the 14c application. i think we can close it.
