### ISSUE TITLE
Update banner page language

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#615]
**Edit banner page with the below language.  The "Read more details" and "Hide details" functionality should remain the same**

You are accessing a U.S. Government information system that is owned and operated by the Department of Labor. There is no expectation of privacy when accessing this system. The Department of Labor information systems are provided for the processing of official U.S. Government information only, and are therefore, owned by the Department of Labor. Authorized users are responsible for the proper handling of the Government data equipment and resources which they access. Use of this system by any user authorized or unauthorized constitutes a consent to this monitoring, recording, disclosure, and accepts that use of the system is subject to audit by authorized personnel. Fraud and related activity in connection with computers is prohibited by Title 18, U.S. Code Section 1030. Furthermore, this law states that intentionally accessing a computer without authorization or exceeding authorized access and thereby obtaining information from any department or agency of the United States is prohibited and subject to civil and criminal penalties, including (but not limited to), punishment by fine and/or imprisonment. Additionally, DOL may provide law enforcement with any potential evidence of a crime found on aforementioned systems in order for them to investigate such offenses. 

Please do not upload Personal Identifying Information (PII) about your employees to the Section 14(c) Online Application.  PII refers to information which can be used to distinguish or trace an individual's identity, such as their name, social security number, biometric records, etc. alone, or when combined with other personal or identifying information which is linked or linkable to a specific individual, such as date and place of birth, mother’s maiden name, etc.

**Screenshot of current banner page, pre-changes:**

![image](https://user-images.githubusercontent.com/19496579/38100040-384dae82-334a-11e8-9ad4-952d4b3e76eb.png)

-----

![image](https://user-images.githubusercontent.com/19496579/38099963-f3ff816a-3349-11e8-9155-b6f974652d14.png)

**Comment by EStriegel** [comment]
I will provide requirements on how to provide disclaimer.  There are OMB considerations when adding instruction.

**Comment by phirefly** [comment]
TODO: Find out if this is necessary from Security due to final screens already being sent out.

**Comment by phirefly** [comment]
@binwang89 to follow-up with security

**Comment by binwang89** [comment]
@phirefly email sent to Security team (Harry) and asked their input on 3/15.

**Comment by binwang89** [comment]
@phirefly @EStriegel @mmurthydol Security responded on 3/23.  Akosua comments below. in email : "The banner notification language was taken from the CSH Vol 1. So it’s in compliance and acceptable."

If everyone think that is "Okay", I think we can move this user story to "Done".

**Comment by EStriegel** [comment]
Confirmed complete.  Moving to `Closed`
