### ISSUE TITLE
Add link to CFR from Assurances page

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#625]
Logged from 2/2 QA Sessions
Assurances page - link to CFR

**Comment by EStriegel** [comment]
On "Representations and Written Assurances" page, wherever 29 C.F.R. part 525 is, link to https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=2c2c1e5e4f61356b4516a55834d00bfd&r=PART&n=29y3.1.1.1.17

Bolded and italicized below.

-----

I certify that I have read this application and to the best of my knowledge and belief, all answers and information given in the application and attachments are true; that the representations set forth in support of this application to obtain or continue the authorization to pay workers with disabilities at subminimum wage rates are true; and I acknowledge that the authorization, if issued or continued, is subject to revocation in accordance with the provisions of **_29 C.F.R. part 525_**.

I represent that as set forth in the regulations governing the employment of workers with disabilities, the following conditions exist and will continue to exist:

Workers employed under the authority in **_29 C.F.R. part 525_** have disabilities for the work to be performed;
Wage rates paid to workers with disabilities under the authority in **_29 C.F.R. part 525_** are commensurate with those paid experienced workers, who do not have disabilities, in industry in the vicinity for essentially the same type, quality, and quantity of work;
The operations are and will continue to be in compliance with the Fair Labor Standards Act (FLSA), the Walsh-Healey Public Contracts Act (PCA), the McNamara-O’Hara Service Contract Act (SCA), and the Contract Work Hours and Safety Standards Act (CWHSSA), an overtime statute for Federal contract work, as applicable;
No deductions will be made from the commensurate wages earned by a patient worker to cover the cost of room, board or other services provided by the facility;
Records required under _**29 C.F.R. part 525**_ with respect to documentation of disability, productivity, work measurements or time studies, and prevailing wage surveys will be maintained.

**Comment by EStriegel** [comment]
@joebhaktiarDOL @mmurthydol Links are all functional, however we need the formatting to be the same as other links within the application.  See screenshot below:
![image](https://user-images.githubusercontent.com/19496579/37850369-3c706b50-2eb1-11e8-883f-848309c7ca42.png)

**Comment by joebhaktiarDOL** [comment]
@EStriegel I'm not sure exactly what to change and what to change it to? Do you want me to change the link text 29 C.F.R. part 525 to  29 U.S.C. 794g(c) and (e)?

**Comment by EStriegel** [comment]
Confirmed complete.  Moving to `Done`
