### ISSUE TITLE
Bug: Accessibility: 508: Browser Tabs do not update to page name when the 'Next' button is clicked

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#626]
Remediate accessibility issues in all pages in the 14c, according to acceptance criteria noted in #198 

Bug description:
when you click the "Next" button on the page, the title of the browser tab still shows the previous page title. 
For example: Work Sites & Employees still shows as tab name after user has clicked next and is seeing the WIOA page. Screenshot below.
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/43252082-8fb3-4eff-a643-288f1f094fe9)

•	Accessibility acceptance criteria:
15. Page Titles  
[ ] 15.1 There is meaningful page title in plain language.

**Comment by NathayaMDOL** [comment]
Hi @binwang89 ,
This issue has been fixed. The title of the browser tab will show properly when you click the "Next" or "Back" button on the page.
Branch "whd-aqa-626-nmankong-508-updatetitle-browsertab"

Thanks,
Nathaya

**Comment by binwang89** [comment]
@EStriegel @mmurthydol I have walk through it with @NathayaMDOL at her local machine, everything looks good, however, there is one thing that she will need to fix. please see below screenshot:
After click on "Continue Current Application", the landing page  title is not show up on the tab page. 

![image](https://user-images.githubusercontent.com/25330625/43027634-8c0f8290-8c49-11e8-949a-f0a37210b5d7.png)

![image](https://user-images.githubusercontent.com/25330625/43027710-e56e2418-8c49-11e8-8335-72cfc9e7a6c7.png)

**Comment by NathayaMDOL** [comment]
@binwang89 ,
All browser tab title names have been fixed. They will be displayed properly in every step. Please see screenshot (capture just some pages as an example) below.
 
![626-home](https://user-images.githubusercontent.com/40499717/43096952-9ee8e744-8e88-11e8-879d-7ab4b978ce33.PNG)
![626-log in](https://user-images.githubusercontent.com/40499717/43096968-a5ee6442-8e88-11e8-82e6-a8a6e58c8bdc.PNG)
![626-assurance](https://user-images.githubusercontent.com/40499717/43096975-a91c26d6-8e88-11e8-8de0-295c2ee6bc31.PNG)

Thanks,
Nathaya

**Comment by binwang89** [comment]
@NathayaMDOL Thank you,  can you also checking to click on Next button to next page, the top tab title names is also corrrect ?

**Comment by binwang89** [comment]
@NathayaMDOL if click the Next button has been tested, you can push it to DEV. Thanks

**Comment by NathayaMDOL** [comment]
@binwang89 , All changes have been pushed to Dev.

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
