### ISSUE TITLE
Bug: Accessibility: 508: Web: Repetitive Content and Links 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#628]
**Repetitive Content and Links** accessibility issues in the below pages, according to acceptance criteria noted in #198
Bug description:
1. There is no method to skip repetitive content. 
Example: https://dol-whd-section14c-qa.aisdemos.com/#!/changePassword  - once the password is successfully changed, there is no method to skip repetitive content.
2. The skip function does not work properly. 
Example: https://dol-whd-section14c-qa.aisdemos.com/#!/changePassword
https://dol-whd-section14c-qa.aisdemos.com/#!/help
https://dol-whd-section14c-qa.aisdemos.com/#!/
https://dol-whd-section14c-qa.aisdemos.com/#!/employerRegistration
https://dol-whd-section14c-qa.aisdemos.com/#!/forgotPassword
Activating skip function does not bring to main content

please see below screenshot for the correct way for repetitive content and link. User should use tab key to tab to the "Skip to main content" link, then hit "Enter" key to skip the main content,  follow the "Tab key" to the next interactive item on the screen. in this case, the  the focus is at  the "question mark". 
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/885aaaa4-78ec-4e86-a5d3-6dd6f61e79cb)

•	Accessibility acceptance criteria:
13. Web: Repetitive Content and Links - A method must be provided to skip blocks of repeated content or links on Web pages allowing a user to move directly to page-specific content.
[ ] 13.1 There is a method to skip repetitive content.
[ ] 13.2 There is a target for all skip links.
[ ] 13.3 All skip functions work properly
[ ] 13.4 If the relative order of the repeated components is the same as other pages.

**Comment by EStriegel** [comment]
@NathayaMDOL Please discuss with @binwang89

**Comment by binwang89** [comment]
@EStriegel @mmurthydol   I have demo and discussed this issue to @NathayaMDOL in appear.in.

**Comment by binwang89** [comment]
move to ready to start after i talked to @NathayaMDOL

**Comment by NathayaMDOL** [comment]
This issue has been fixed and reviewed with @binwang89.
Branch: "whd-aqa-628-nmankong-508-skiptomaincontent"

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
