### ISSUE TITLE
Bug: Browser upload file box disappeared after user select the option "keep the file" for Deletion. 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#629]
Bug Description:
On Wage-data page, user can delete the file that they uploaded. however, the 
browser  box will be disappeared after they select the option "No, Keep File".
please see below screenshots. 
https://dol-whd-section14c-qa.aisdemos.com/#!/section/wage-data
1. before the file uploaded.
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/38ba29b8-e881-41be-a813-dd789c93dbfc)
2. After the file was uploaded.
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/b1c3e72b-cc38-4b86-b2fa-cf02e74be487)
3. User click the  "Delete"
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/4ef3c665-58ab-4afe-84b6-9c36fb50ccb2)
4. After user click "No, keep file", the browser box was disappeared.
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/28c388e4-75e4-44cf-a0fc-2ad7d575fead)

**Comment by binwang89** [comment]
@davoodharun please make sure all 4 places for file upload in the whole system will be tested.

**Comment by EStriegel** [comment]
Complete - tested all file upload options.  Moving to `Done`
