### ISSUE TITLE
Redirect a user to Employer Registration from Dashboard if no employer exists yet

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#631]
If an employer is not registered, do not allow the user to view the Dashboard. Rather, the user should be directed to the Employer Registration page. This was discovered when trying to click on the `Start a New Application` button on the Dashboard page when no registered employer employer existed.

** Acceptance Criteria **
- [ ] If a user has not yet registered an employer, the dashboard link should not be clickable (maybe not even visible, if possible) and the user should not be able to access the landing page or any other page of the 14c application..
_[Initial question: @EStriegel What should the Ux behavior be if employer not registered? Should the dashboard link be clickable? Should the landing page (if clickable or for that matter any other pages if user added a bookmark) even display?]_

- [ ] High priority from business perspective. Would not want a user to be able to begin/submit an application before registering an employer.
_[Initial question: What should be the priority of this story from a business perspective? This is an important story from IT perspective about not providing access to all other parts of the app when employer not registered employer (except for admin pages which have a different set of rules)]_

- [ ] @binwang89 Could you &/or one of the AQA team book mark or remember the URLs for all 14c pages; create a new user, do not register employer, try to access the bookmark or paste URls for all other pages (like landing page, etc.) ad document whether these pages are visible. And if they are visible document what happens when entering data in the fields and clicking on available buttons (ex: next, upload, etc.).

- @davoodharun If you know any of the answers to above steps, we can discuss what strategy we might consider even if not going into the sprint.

**Comment by binwang89** [comment]
@mmurthydol @EStriegel I have collected all URLs for 14c pages and we will follow the steps that instructed by Madhu for the QA today. 
Login Workflow
https://dol-whd-section14c-qa.aisdemos.com/#!/
https://dol-whd-section14c-qa.aisdemos.com/#!/login
https://dol-whd-section14c-qa.aisdemos.com/#!/dashboard
https://dol-whd-section14c-qa.aisdemos.com/#!/changePassword
https://dol-whd-section14c-qa.aisdemos.com/#!/help
https://dol-whd-section14c-qa.aisdemos.com/#!/employerRegistration

Employer https://dol-whd-section14c-qa.aisdemos.com/#!/section/employer
Wage Data                                                      https://dol-whd-section14c-qa.aisdemos.com/#!/section/wage-data
Work Sites & Employees https://dol-whd-section14c-qa.aisdemos.com/#!/section/work-sites
Review & Submit https://dol-whd-section14c-qa.aisdemos.com/#!/section/review
Pattern library  https://dol-whd-section14c-qa.aisdemos.com/#!/v4/ui-library
Assurances https://dol-whd-section14c-qa.aisdemos.com/#!/section/assurances
Application Info https://dol-whd-section14c-qa.aisdemos.com/#!/section/app-info
WIOA  https://dol-whd-section14c-qa.aisdemos.com/#!/section/wioa

**Comment by binwang89** [comment]
@mmurthydol @EStriegel tested again at QA site today, The system will redirect a user to Employer Registration from Dashboard if no employer exists.  Even i tried to put any web page link at the top and see if the user can go the page ( wage data, work sites & employee....), the system will still direct me back to employer registration page.

**Comment by EStriegel** [comment]
Moving to `Done` per Michelle's above comment.
