### ISSUE TITLE
Clicking 'Register' when registering a new user requires two clicks

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#640]
The first click jumps the page to the bottom of the screen. The second click submits the form.

**Comment by mmurthydol** [comment]
@EStriegel @binwang89  Liz: This is an EZ (== inexpensive) workaround for the annoying and deceptive Register button click problem. Let's discuss and then please test when you can.

**Comment by binwang89** [comment]
@EStriegel @PrabhakarThummalaDOL I tested it again by registration a account (clicked the Register button only one time), and the  account creation message was displayed. please see below screenshot:


![image](https://user-images.githubusercontent.com/25330625/40952822-f7863d20-684a-11e8-8fff-42d2cac1c63c.png)
