### ISSUE TITLE
Update email config

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#647]
Story should be implemented in DOL internal environment. Created #686 to revert back changes.

Use shared team email for cert team as indicated in https://trello.com/c/7bEO1lwF

- [x] In AIS environment, do not make the proposed changes below. Let the email value be test @test.com
       - Not applicable
- [x] update API project web.config appSettings-> Key=CertficationTeamEmailAddress
       value to 14c-submitted-applications@dol.gov in DOL internal environment by using Jenkins 
       configuration.
- [x] update the corresponding test code in DOL internal environment. Once we are in internal DOL environment, consider either removing this test &/or allow the tests to recognize values by environment.
       - Not applicable.

**Comment by PrabhakarThummalaDOL** [comment]
Updated the CertificationTeamEmailAddress value to 14c-submitted-applications@dol.gov.

**Comment by PrabhakarThummalaDOL** [comment]
Updated the CertficationTeamEmailAddress value to 14c-submitted-applications@dol.gov.
Completed.

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
