### ISSUE TITLE
Bug- Missing error message on Work Sites & Employees page

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#653]
@EStriegel Liz, we need to discuss.
Cheaper fix: Just change error message; Defect will downgrade from critical to major/minor
Corrrect fix: The text box and data table should communicate with each other.

The error in this screenshot is that the user has indicated there is only work site, but they have added two work sites.  The system is correct in identifying an error, but it is not providing a specific flag to the "What is the total number of establishments and work sites to be covered by this certificate?" question.

Error message should be,"The number of establishments and work sites reported (1) does not match the number of establishments and work sites entered (2)."

![image.png](https://images.zenhubusercontent.com/57e9239095e42b6c5ba972b8/e1506493-68cf-456c-a110-5007f6c23c0f)

**Comment by NathayaMDOL** [comment]
This story has been fixed and pushed to branch "whd-aqa-653-nmankong-errormsg-worksite-totalnumber". 
![add worksite-error msg](https://user-images.githubusercontent.com/40499717/42889248-f5924956-8a77-11e8-8e47-f9a4b92d53ef.png)

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
