### ISSUE TITLE
Bug: Banner page is missing when clicking on email confirmation link.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#655]
@EStriegel We (you and I) need to discuss this story prior to going to security. Implementing this story is somewhat time consuming. I have a workaround. We can add banner page verbiage equivalent to email itself. That should take care of security concern - at least that would be our pitch. Similar considerations with Reste Password link. 

For any link within an email that takes the user to the online application, the banner page should be the first page the user encounters.

**Comment by EStriegel** [comment]
@mmurthydol The story blocking this bug is `Done`.  Can we unblock?

**Comment by mmurthydol** [comment]
@EStriegel We just had to close blocking the story. Done isn't enough for ZenHub.

**Comment by EStriegel** [comment]
@binwang89 please follow up with Harry as to whether this is required.

**Comment by binwang89** [comment]
@EStriegel , Harry and @mmurthydol  spoked during the standup and received security guidance/confirmation as outlined below.

Any functionality implemented by the application where user receives an email that contains a link to be clicked on, and when user clicks on the link, the user should be redirected to a banner page prior to be redirected to any application page (ex: change password page, email confirmation page).

**Comment by PrabhakarThummalaDOL** [comment]
Fixed.

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
