### ISSUE TITLE
As a developer, I would like to install API development software

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#659]
191, 192, 193
**By OCIO:**
- [x] Visual Studio 2015 Update 3
- [ ] Visual Studio 2017
- [ ] Data Studio & Control Center
**By Developer:**
Look in c:\section14c\tools.
- [ ] DB2 client package
- [ ] IBM DB2 Addin
- [ ] Devart DotConnect
- [ ] DB2 Express-C
- [ ] SMTP dummy server
**- [ ] Verify API is up and running.**

**Comment by EStriegel** [comment]
@mmurthydol confirmed done.  Moving to `Done`
