### ISSUE TITLE
As a developer, I would like to connect to DOL GitLab repository

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#661]
- [ ] Steps similar to #660 but with the DOL GitLab local path: C:\src\mmurthy\whd\section14c-18f
Gitlab path: https://gitlab.dol.gov/whd-dev/section14c-18f
- [ ] Ensure access to GitLab through @binwang89 and as needed with madhu

**Comment by mmurthydol** [comment]
Determined need to access to GitLab from VMs: GitLab internal story is 75

**Comment by EStriegel** [comment]
@binwang89 Please confirm @PrabhakarThummalaDOL & @joebhaktiarDOL are connected to GitLab

**Comment by binwang89** [comment]
@EStriegel @mmurthydol confirmed with Prabhakar and Joe.  they are connected to Gitlab.
