### ISSUE TITLE
As a developer I would like access to DOL 14c Dev environment

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#663]
From the VM:
- [ ] Verify RDP access to Dev Web servers
- [ ] Verify Data Studio access to DOL 14c DB2 Dbs (14c, 14c log)

**Comment by mmurthydol** [comment]
@PrabhakarThummalaDOL verify 191, 192, 193

**Comment by EStriegel** [comment]
@binwang89 Please confirm completed by @PrabhakarThummalaDOL & @joebhaktiarDOL

**Comment by binwang89** [comment]
@EStriegel @mmurthydol confirmed with Joe and Prabhakar.  they have access to DOL 14c Dev
