### ISSUE TITLE
Bug: Profile password change page must work correctly with email info

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#665]
@PrabhakarThummalaDOL Verify state of fix/defect
![image](https://user-images.githubusercontent.com/25183303/36873884-f38b4d32-1d77-11e8-9895-817371050cf7.png)

It is a defect that email-Id is editable. 
(a) Email-ID can be displayed but should be read-only if displayed. 

Question: Does google/live display email-info on password change??

**Comment by EStriegel** [comment]
@mmurthydol Option (a).  Will update the original comment.

**Comment by binwang89** [comment]
move it to Ready to Start

**Comment by binwang89** [comment]
@PrabhakarThummalaDOL i just tested it,  it looks like the issue is still there, please see the screenshot below, when i clicked on the email, the field is still editable.

![image](https://user-images.githubusercontent.com/25330625/41991093-560f34ae-7a12-11e8-9194-f70ee82d153a.png)

**Comment by binwang89** [comment]
sorry, error testing this one, i will put it back to code review.
