### ISSUE TITLE
Bug:  WIOA section, data table not displaying information entered

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#680]
To recreate: 

At WIOA section, click add worker, complete First Name, Last Name and Yes/No/Not Required and click submit.  See screenshot for how data table does not show info input.

![image.png](https://images.zenhubusercontent.com/57e9239095e42b6c5ba972b8/d5224268-9937-405b-a328-d1634bd38022)

**Comment by mmurthydol** [comment]
@EStriegel Could you please list down repro steps so @joebhaktiarDOL can recreate this scenario on his laptop and then assign the story to @joebhaktiarDOL and me again please? Thanks.

**Comment by EStriegel** [comment]
@PrabhakarThummalaDOL Please discuss with @mmurthydol

**Comment by binwang89** [comment]
@NathayaMDOL when it is completed, please make sure test it by IE/Chrome both.  Thanks

**Comment by NathayaMDOL** [comment]
This story has been completed. The screenshot below.
Branch: "whd-aqa-680-wioa-addworker-datatable"
Note: There is 508 datatable issue (on IE only) which needs more time for researching. So I have created the new story #793.

![680](https://user-images.githubusercontent.com/40499717/44878804-df29a680-ac75-11e8-95ce-83857350acee.png)

**Comment by binwang89** [comment]
@NathayaMDOL it looks good 
![image](https://user-images.githubusercontent.com/25330625/45165690-52c23b00-b1c3-11e8-9c26-e5dd796c777d.png)

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
