### ISSUE TITLE
Bug: Session timeout (UI)

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#684]
Bug: 
- [x] Session timeout warning pops up when user is actively completing application.
- [x] Logged out user should not get session timeout pop up dialog user (this includes log-in page/admin).

**Acceptance Criteria:**
Existing behavior must be preserved.
- [x] Popup dialog continues to show after 13 minutes of idle time and after 15 (13 + 2 ) total minutes of idle time session times out.
- [x] Title bar must not change.

**Comment by mmurthydol** [comment]
Moved to in progress. after reviewing code and testing together

**Comment by EStriegel** [comment]
Confirmed and closed.
