### ISSUE TITLE
As an applicant, I would like a user profile page within the online application so that I can change my password.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#69]
Are there other functions that should be within a user profile?  Maybe the ability to update an email address?

For Milestone 1, a simple version of the profile page that displays the user account information & the ability to change a password, along with text for the Registered Employer:
https://preview.uxpin.com/7560d7b8748cecf936982e02cb0dda4371113d92#/pages/77548394/simulate/no-panels

**Comment by jmmcnj** [comment]
@EStriegel Lets break this one down further, we do have a change your password link on the landing page but no profile page yet

**Comment by jmmcnj** [comment]
Descripition:
User clicks on email/account name link in navigation and is takend to a "profile" page that is labled Account and has just the change password link for now

Tasks:
- [ ] Create View for profile
- [ ] Add change password link and Title the View Account

Acceptance Criteria: User clicks on email/account name link in navigation and is takend to a "profile" page that is labled Account and has just the change password link for now
Considerations:
1. Application Status: 
2. Role: Applicant

**Comment by suprenant** [comment]
@simplyshang moving this to In Progress – can you confirm that it is, indeed, in progress?

**Comment by simplyshang** [comment]
@suprenant It's not in progress at the moment. We did discuss this one in the UX grooming session on Monday, but I hadn't assigned myself or put an estimate against it b/c I wasn't sure if it would make it into Sprint 3.

If the priority has changed & I should focus on this, there's time to for me to pivot and do that; just let me know.

**Comment by suprenant** [comment]
@simplyshang OK, we thought that it had started but weren't sure. We'll save this, likely for Sprint 4. So, no change for now – thanks for clarifying.

**Comment by jmmcnj** [comment]
Create Implementation associated User Story before final review/closeout

**Comment by mmurthydol** [comment]
@EStriegel Liz, please verify Shannon's visual design. Not sure if there us an  implementation story for this. If not, we need an implementation story creating before closing this one. If writing implementation story we probably should go through visual design together.
