### ISSUE TITLE
Bug: Email confirmation is not being sent for internal email addresses.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#702]
Email confirmation is not being sent for internal email addresses.

**Comment by mmurthydol** [comment]
resolved through email relay server getting configured correctly

**Comment by PrabhakarThummalaDOL** [comment]
@binwang89  @EStriegel  Please test this.

**Comment by binwang89** [comment]
@PrabhakarThummalaDOL @mmurthydol @EStriegel I have tested the this defect recently by using my dol email account, the result is good. Please see below screenshot for confirmation email sent to my internal email account. 

![image](https://user-images.githubusercontent.com/25330625/40949442-1dc12428-683c-11e8-8487-b8902bb40d2a.png)
