### ISSUE TITLE
Security: Disabled users must reactivate user to login to the system

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#707]
- [x] Disabled users upon login must receive an email stating that their account was disabled due to inactivity (specific message in each case). The text is configurable in web.config. Email subject: "Reactivate Your Account: Department of Labor Section 14(c) Online Certificate Application".
- [x] Display the message on the login page - "Your account has been disabled due to inactivity. Please check your email and follow the instructions to reactivate your account.". Configure the message in web.config.
- [x] Disabled users will access the received email that contains a "activate user" link. By clicking on this link, users will go to a new page (activate user)  where user can (a) enable that user (set DISABLED column to false) (b) reset password.
- [x] Email text (configurable in web.config): 
"Please reactivate your account by clicking this link or copying and pasting it into your browser: <link>"

**Comment by PrabhakarThummalaDOL** [comment]
Completed.

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
