### ISSUE TITLE
Bug: Typos  on the login page that displays password requirements

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#711]
Bug Description:
Typos  on the login page that displays password requirements, The “leter” must be changed to “letter”.  
Please see the screenshot below - 
![image](https://user-images.githubusercontent.com/25330625/41665907-26b741ce-7477-11e8-92aa-01253e861dc2.png)

**Comment by EStriegel** [comment]
Confirmed complete during demo on 7/18
