### ISSUE TITLE
UI - As an applicant, I would like to have "Name of Worker" within the add employee slider to be captured as First Name, Last Name to prevent data quality issues

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#713]
As an aside fixing this in online might be trickier as it affects API + UI layers in some intricate ways.

**Comment by binwang89** [comment]
See story #651 for reference

**Comment by PrabhakarThummalaDOL** [comment]
Closing.
Duplicate. This is covered in #768.
