### ISSUE TITLE
Bug: Typos on the app-info page that displays error message for fax number

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#715]
Bug description:
https://section14cdev.dol.gov/#!/section/app-info

System needs to display the following error message:
"If available, please provide a valid fax number."

please see the screenshot below:  

![image](https://user-images.githubusercontent.com/25330625/41782645-ce0384aa-7608-11e8-957f-794e1e33d677.png)

**Comment by EStriegel** [comment]
Confirmed complete during demo on 7/18
