### ISSUE TITLE
Bug: UI - EIN validation is missing on employer tab.

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#718]
Bug description:
under Employer ( https://section14cdev.dol.gov/#!/section/employer), if user did not enter the EIN information, the system won't not validate this field and no error message display for this required field.

**Requirements**
- [x] Add EIN required validation in validation JS file.
- [x] Add EIN regular expression validation in JS file.
- [x] Please display the following error message:
"Please provide the Federal Employer Identification Number."

Note: Look at the Employer Registration page for EIN.

TODO @mmurthydol Check with data team about pop-up when EIN is different on Employer tab (and in Employer Registration Page)

Please see the screenshots below - 
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/bfad9852-bc2d-4efb-b709-63abe6a0e039)

**Comment by NathayaMDOL** [comment]
EIN number need to be saved in a new column in DB and new story need to be created.

**Comment by NathayaMDOL** [comment]
Hi @binwang89 ,
This issue has been completed. Screenshot below.
FYI: From Madhu email, "we don’t need popup on EIN validation".
Branch "whd-aqa-718-nmankong-ein-validation-onemployertab"

![718-ein1](https://user-images.githubusercontent.com/40499717/43154680-3abbfa52-8f43-11e8-9eaf-d6e3d68f8e91.PNG)
![718-ein2](https://user-images.githubusercontent.com/40499717/43154683-3d00577c-8f43-11e8-9b6c-21f1cbc12d91.PNG)

Thanks,
Nathaya

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
