### ISSUE TITLE
Bug: Typo in the examples that we are providing for John Jones and for Sue Gomez. 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#719]
Bug Description:
Typo in the examples that we are providing for John Jones and for Sue Gomez. 

Should read: “Commensurate wage rate/average earnings per hour for job described above”
Instead of:  “Commensurate wage rate/average earings per hour for job described above”

Steps: 
Add Employees 
> instead of adding the employee info, click Show Me an Example
> select either example > same typo on both.

Fix: fix example content to read “earnings”

please see the screenshot below - 
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/8f096805-6730-4f82-89a3-57fe1f4ce06c)

**Comment by EStriegel** [comment]
Confirmed complete during demo on 7/18
