### ISSUE TITLE
As an applicant, I would like the option to reset my password on the log-in page so that I don't lose access to my account.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#72]

**Comment by jmmcnj** [comment]
@EStriegel This is implemented in the current integration environment, we should take time to break this down to make sure we arent missing anything from the implementation

**Comment by jmmcnj** [comment]
Descripition:


Tasks:
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
- [ ] Task 4

Acceptance Criteria:
Considerations:
1. Application Status
2. Role
