### ISSUE TITLE
Bug: Employee page, radio button should not be default selection.

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#722]
bug description: the radio button should be open for user to make selection and not default to piece rate. 

Steps: 
Add Employees 
> go to field "Productivity measure/rating for job described above"
> The radio button is default to n/a- piece rate

![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/04669023-3b83-4d06-8f16-5fc9b8cbb763)

The radio button selection should not have a default one, please see the below screenshot for 
other radio selection. 

![image](https://user-images.githubusercontent.com/25330625/41827973-82e4ad6a-7800-11e8-9850-83464dc898c8.png)

**Comment by NathayaMDOL** [comment]
This story has been completed and pushed to branch "whd-aqa-722-nmankong-pageaddemployees-radiobutton-productivitymeasure". The fixed are 3 parts, see screenshot below.
1. un-default productivity measure's radio button.
![add employer-productivity measure - no default selection](https://user-images.githubusercontent.com/40499717/42786517-959967e0-8924-11e8-98a3-2679f07e2f0b.png)

2. validation of productivity measure's radio button.
![add employer-productivity measure - radio button validation](https://user-images.githubusercontent.com/40499717/42786525-9a65b4e0-8924-11e8-875c-5beaa9b0bb9b.png)

3. validation of hourly option.
![add employer-productivity measure - hourly validation](https://user-images.githubusercontent.com/40499717/42786530-a2627340-8924-11e8-826d-7a1ff42d1f80.png)

Thanks,
Nathaya

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
