### ISSUE TITLE
Provide screenshots as walk through the 14C Online application

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#723]
please provide  screenshots as you walk through the 14C Online application (banner page, user registration – before/after clicking on register, login as an invalid user, login as a valid user)

**Comment by NathayaMDOL** [comment]
Hi @mmurthydol  and @binwang89 
Please see the attached!
![1 registrationpage](https://user-images.githubusercontent.com/40499717/41875183-17b45462-7898-11e8-9b7c-4adf37d6b47e.png)
![2 fillformregistrationpage](https://user-images.githubusercontent.com/40499717/41875184-17bf5c90-7898-11e8-8d47-d22d70825dc8.png)
![3 afterclickingregister](https://user-images.githubusercontent.com/40499717/41875185-17d3c5f4-7898-11e8-8867-06f879e6ce3e.png)
![4 0 loginasvaliduserstep1](https://user-images.githubusercontent.com/40499717/41875177-176a51e6-7898-11e8-9643-303779e3f341.png)
![4 1 loginasvaliduserstep2](https://user-images.githubusercontent.com/40499717/41875178-17762782-7898-11e8-9b9e-60a289301b2a.png)
![4 2 loginasvaliduserstep3](https://user-images.githubusercontent.com/40499717/41875179-17839700-7898-11e8-9d03-86fe69e5979a.png)
![4 3 loginasvaliduserstep4](https://user-images.githubusercontent.com/40499717/41875180-17908b22-7898-11e8-8f0d-f528941ea5c0.png)
![5 0 loginasinvaliduserstep1](https://user-images.githubusercontent.com/40499717/41875181-179d0e56-7898-11e8-8a9d-d0f065acf256.png)
![5 1 loginasinvaliduserstep2](https://user-images.githubusercontent.com/40499717/41875182-17a935aa-7898-11e8-8951-19964d65caf1.png)

**Comment by mmurthydol** [comment]
@NathayaMDOL Thanks. Could you also provide screen shots for (a) email already exists upon user registration (b) a sample user confirmation email (c) screen shot of the page that you see when you click on confirm link on the email.
Thanks.
@binwang89 Michelle - FYI

**Comment by mmurthydol** [comment]
@NathayaMDOL (d) also the 2FA email (e) change/reset password email (f) reset/change password page when clicking on the link in the email. (g) screen shots from the admin functionality - Prabhakar can point out what needs to be done. Please provide d, e, f and g separately.
@PrabhakarThummalaDOL @binwang89 FYI

**Comment by NathayaMDOL** [comment]
Here are screen shots for (a), (b) and (c)
![a email already exists upon user registration](https://user-images.githubusercontent.com/40499717/41876442-d1b86152-789b-11e8-8f16-65b558786089.png)
![b a sample user confirmation email](https://user-images.githubusercontent.com/40499717/41876446-d4cef9d2-789b-11e8-896a-3aca651175bd.png)
![c screen shot of the page that you see when you click on confirm link on the email](https://user-images.githubusercontent.com/40499717/41876449-d7b70da6-789b-11e8-854f-8ab8dc398686.png)

**Comment by NathayaMDOL** [comment]
Here are the screen shot for d,e,f and g in zip file
[screen shots d, e, f and g.zip](https://github.com/18F/dol-whd-14c/files/2134836/screen.shots.d.e.f.and.g.zip)

**Comment by mmurthydol** [comment]
@NathayaMDOL I need following pictures: 
1)	Page after clicking Edit/View button in User Management
2)	All screen shots for changing password (not the same as reset password).
3)	Session Timeout popup dialog boxes – two of them (a) around 13 minutes popup (b) popup after 15 minutes when session timed out.
4)	Account Lockout screenshot on login page
5)	Disabled user attempts to login – screen shot needed. Notification email to user is not implemented yet though.
6)	Deleted user attempts to login – screen shot needed. Same as above for notification email – not implemented.

@binwang89 @PrabhakarThummalaDOL  FYI.
Thanks,
Madhu

**Comment by NathayaMDOL** [comment]
@mmurthydol ,
The attached zip file is the screenshot of above lists.
[Screenshot 26Jun18.zip](https://github.com/18F/dol-whd-14c/files/2137687/Screenshot.26Jun18.zip)

Thanks,
Nathaya

**Comment by mmurthydol** [comment]
@NathayaMDOL may I have following screenshots
1) After clicking on Edit/View page, could you please uncheck everything except "Email Confirmed".
Thanks

**Comment by NathayaMDOL** [comment]
@mmurthydol , 
![after clicking edit-view admin](https://user-images.githubusercontent.com/40499717/41978800-8e13b8ba-79f0-11e8-81be-4bb42c51ce25.png)
