### ISSUE TITLE
Bug: Email confirmation - Clicking on Hyperlink shows a blank page in IE (Chrome is OK).

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#727]
Please see if this defect can be reproduced.

## Acceptance Criteria
- [x] Test on  IE
- [x] Test on Chrome
- [ ] Madhu to Test on IE if IE behavior works OK on Nathaya's machine.

**Comment by NathayaMDOL** [comment]
Hi @mmurthydol ,
Yes, the defect can be reproduced. After clicking email confirmation on Hyperlink shows a blank page in IE but Chrome is OK.

Thanks,
Nathaya

**Comment by PrabhakarThummalaDOL** [comment]
Closing.
Duplicate of #771.
