### ISSUE TITLE
14C Online Application must only support User and Admin roles

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#730]
## Acceptance Criteria
- [x] Edit/View UI must only display Applicant, System Administrator roles.
- [x] Do not display 2FA check box.
- [x] API code must only support Applicant, System Administrator roles.
- [x] Remove all other roles (except Applicant and System Administrator) from the seed method(s).

**Comment by PrabhakarThummalaDOL** [comment]
Completed. Ready for code review.

**Comment by PrabhakarThummalaDOL** [comment]
Completed.

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
