### ISSUE TITLE
Update license file for section14c.log project

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#735]
- [x] Re-generate the dol.whd.section14c.log.dll.licenses file using commands provided by WHD.
- [x] Use the following commands to generate the .licenses files (for API, DataAccess and Log projects):

"C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\lc.exe" /target:DOL.WHD.Section14c.Api.dll /complist:"C:\Program Files (x86)\Devart\dotConnect\DB2\Enterprise Library\NET4.5\DataAccessQuickStart\CS\licenses.licx" /i:"C:\Program Files (x86)\Devart\dotConnect\DB2\Devart.Data.DB2.dll"

"C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\lc.exe" /target:DOL.WHD.Section14c.DataAccess.dll /complist:"C:\Program Files (x86)\Devart\dotConnect\DB2\Enterprise Library\NET4.5\DataAccessQuickStart\CS\licenses.licx" /i:"C:\Program Files (x86)\Devart\dotConnect\DB2\Devart.Data.DB2.dll"

"C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\lc.exe" /target:DOL.WHD.DOL.WHD.Section14c.Log.dll /complist:"C:\Program Files (x86)\Devart\dotConnect\DB2\Enterprise Library\NET4.5\DataAccessQuickStart\CS\licenses.licx" /i:"C:\Program Files (x86)\Devart\dotConnect\DB2\Devart.Data.DB2.dll"

- [x] and add to  Section14c (a) Log project (b) DataAccess proj (c) API proj (d) Test proj
- [x] Update Referenced Assemblies files to reflect the correct version (copy them  from the installed DevArt DotConnect. Three files.
- [x] Ensure files are copied and updated correctly in Gitlab. Sometimes network connectivity issues cause problems that one or two file content not updated correctly. Can also be true with Migration cs file content.

**Comment by mmurthydol** [comment]
@PrabhakarThummalaDOL Prabhakar, Please document the commands in the description as indicated and then close this story. Thanks!

**Comment by PrabhakarThummalaDOL** [comment]
@mmurthydol  Added the commands to the description and closed the story.
