### ISSUE TITLE
Bug: Typo on error message for "Basis for Conclusion Wage Rate is Not Based on Entry Level Note: Hourly and Per Piece selections."

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#736]
Bug description:
Field: Basis for Conclusion Wage Rate is Not Based on Entry Level
Note: Hourly and Per Piece selections.

Issue: The word ‘basis’ is misspelled. It reads: “Please provide a bassi for conclusion that the wage rate is not based on entry”

Steps:
> Select Wage Data
> Now Select the ‘Piece Rate’ option
> Select ‘Prevailing Wage Survey’
> Add a Source Employer 
> Do not add any information, but click ‘Save Source Employer’ instead.
> click Review & Submit
> Wage Data: select Edit Responses
> Source employer: click Edit
> Error messages display.  Please correct typo.  

Additional Correction:
Add the word ‘level’ at the end. Error message should read:
Please provide a basis for conclusion that the wage rate is not based on entry level.

Note: Please correct both of these issues for the Hourly and the Per Piece options.
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/bfe384f0-1597-4250-be27-4268fcb75010)

**Comment by NathayaMDOL** [comment]
This issue has been fixed. Branch: "whd-aqa-736-737-738-750-751-typo"

![image](https://user-images.githubusercontent.com/40499717/43981826-71cfde74-9cc1-11e8-999e-7043a57d3aca.png)

**Comment by binwang89** [comment]
Tested and looks good. move it Done

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
