### ISSUE TITLE
Bug: Typo on error message for Description of Work Performed on this Job Contract by Workers Paid Sub minimum Wage

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#737]
Bug description:
Field: Description of Work Performed on this Job Contract by Workers Paid Subminimum Wage
Issue: There is a typo in the error message:
The word “Assembly” is misspelled:  the “Hand Assebmly of Boxes (28" x 12").” (see screen shot)

Steps: 
> Select Wage Data
> Now Select the ‘Piece Rate’ option
> Do not enter any info in the following field: 
“Description of Work Performed on this Job/Contract by Workers Paid Subminimum Wages”,
>Click ‘Next’ 
> Click “Review & submit”
> Wage Data: click ‘Edit Responses’
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/f784f718-7a36-4a83-a0f6-c1f8e5ba7709)

**Comment by NathayaMDOL** [comment]
This issue has been fixed. Branch: "whd-aqa-736-737-738-750-751-typo"

![image](https://user-images.githubusercontent.com/40499717/43981528-2ac11670-9cc0-11e8-9045-1daa87d0095e.png)

**Comment by binwang89** [comment]
@NathayaMDOL tested and pass.  Moved to Done

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
