### ISSUE TITLE
Bug: Typo on error message for Provide the commensurate wage rate for the job identified

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#738]
Screen / Page: Wage Data
Field:  Provide the commensurate wage rate for the job identified.
Issue:  typo – the word commensurate is misspelled. Error message reads:
“Please provide the commensurage wage rate for the job identified”

Steps:
> Add Employee
> Done Editing Employee
> Do not enter any info in the above field. Please see screen shot for error message.
Fix: Error message should display as follow:
Please provide the commensurate wage rate for the job identified
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/88d36b43-6254-4c1b-a735-d81a6bb65fc3)

**Comment by NathayaMDOL** [comment]
This issue has been fixed.
Branch: "whd-aqa-736-737-738-750-751-typo"

![image](https://user-images.githubusercontent.com/40499717/43981446-ec1bb9b6-9cbf-11e8-9d40-63207839f8dd.png)

**Comment by binwang89** [comment]
looks good, moved to done

**Comment by EStriegel** [comment]
Confirmed 9/6.  Complete.
