### ISSUE TITLE
Bug: Typo on error message for error message for: PREVAILING WAGE SURVEY FOR WORKERS PAID ON A PIECE RATE BASIS

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#739]
Field: error message for: PREVAILING WAGE SURVEY FOR WORKERS PAID ON A PIECE RATE BASIS

Issue: typo. Error message display: Please indicate if the employer employed workes with disabilities who received subminimum wages and were paid piece rates during the most recently completed fiscal quarter

Steps:
> Go to the following question:
(a) Did this employer employ workers with disabilities who received subminimum wages and were paid piece rates during the most recently completed fiscal quarter?
    O Yes 
    O No
> Do not select Yes or No.  Save the page.
Fix: correct the misspelled in the error message to read:

Please indicate if the employer employed workers with disabilities who received subminimum wages and were paid piece rates during the most recently completed fiscal quarter.

**Comment by NathayaMDOL** [comment]
This issue has been fixed in #749

**Comment by binwang89** [comment]
#749 completed and Done

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
