### ISSUE TITLE
Bug: There is no error message. If checked, then user is required to enter the total number of workers with disabilities. 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#743]
Bug description:
Section:  REPRESENTATIVE PAYEE FOR SOCIAL SECURITY BENEFITS
Field: [  ] Check here if the employer was a representative payee for any worker with disabilities and, as such…

Scenario: The user makes a selection to indicate that ‘yes’.

Issue: There is no error message. If checked, then user is required to enter the total number of workers with disabilities. 

Fix:  When user check this field and does not provide the total number of workers, please display the following error message: 
“You indicated the employer was a representative payee for Social Security Benefits. Please provide the total number of workers the facility was a representative payee for.”

**Comment by NathayaMDOL** [comment]
@binwang89 , This has been fixed. See the screenshot below.
Branch:  "whd-aqa-743-nmankong-errormsg-totalnumber-disabilityworker"
![743](https://user-images.githubusercontent.com/40499717/44803527-b7aadf00-ab8c-11e8-9740-5467e3c514cc.PNG)

**Comment by binwang89** [comment]
@NathayaMDOL it looks good

![image](https://user-images.githubusercontent.com/25330625/45164655-ecd4b400-b1c0-11e8-82e9-f0d5748e5efa.png)

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
