### ISSUE TITLE
Bug:There is no error message for the field Section: CREDITING THE REASONABLE COST OF FACILITIES PROVIDED TOWARD MEETING THE MINIMUM WAGE Field: Type of deduction (i.e., transportation, rent, meals)    

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#744]
Bug description
Section: CREDITING THE REASONABLE COST OF FACILITIES PROVIDED TOWARD MEETING THE MINIMUM WAGE
Field: Type of deduction (i.e., transportation, rent, meals)    
Issue:  There is no error message. if yes, then user needs to type of deduction in the open field. 

Fix: If user does not type anything, then the following error message should display:

“Please provide the type of deduction.”

**Comment by NathayaMDOL** [comment]
Hi @binwang89 ,
For this story, there is an error message and it's showing properly. Can you please confirm if it same field as the screenshot below. Then we can close this ticket.

![image](https://user-images.githubusercontent.com/40499717/44736470-51a35680-aabd-11e8-9121-19cffb2865f1.png)

Thanks,
Nathaya

**Comment by binwang89** [comment]
@NathayaMDOL it looks good 
![image](https://user-images.githubusercontent.com/25330625/45169527-cd8f5400-b1cb-11e8-84cc-7728ffb2954b.png)

**Comment by EStriegel** [comment]
Confirmed on 9/6.  Closed.
