### ISSUE TITLE
Bug: There is no error message for Section: REQUIREMENTS UNDER THE WORKFORCE INNOVATION AND OPPORTUNITY ACT (WIOA)

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#745]
Bug description:
Section: REQUIREMENTS UNDER THE WORKFORCE INNOVATION AND OPPORTUNITY ACT (WIOA)

Field: 
Y/N/NR
  0  Yes
  0  No
0	NR

Issue:  There is no error message. 

Fix:  Please display the following error message:

“Please indicate if the employer reviewed, verified, and maintained documentation showing that the worker received all services and counseling required by WIOA before paying the worker a subminimum wage.”

**Comment by NathayaMDOL** [comment]
This issue has been fixed. See screenshot below.
Branch: whd-aqa-745-nmankong-wioa-errormsg

![wioa -error msg](https://user-images.githubusercontent.com/40499717/44102891-c67e3a8e-9fb8-11e8-9da4-2e60d8eb5a8e.png)

**Comment by binwang89** [comment]
looks good, move it to Done
