### ISSUE TITLE
Bug: "Search" field should not display red frame,  it should not be part of the validation scan.

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#746]
Bug description:
Area: Work Sites & Employees > Add Work Site.
Field: Search field

Issue: Search field should not display red frame
Search button should not have a red frame around it.

Steps: 
Go to Work Sites & Employees >  select Add Work Site > look at the Search field

Fix: it should not be part of the validation scan that is being done

![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/af469c3f-f968-46cd-86b8-6bacca8ccc35)

**Comment by binwang89** [comment]
@mmurthydol could you  please check this user story and provide the acceptance criteria.

**Comment by EStriegel** [comment]
@NathayaMDOL Please discuss with @mmurthydol and @PrabhakarThummalaDOL

**Comment by PrabhakarThummalaDOL** [comment]
@NathayaMDOL  I discussed with Madhu, we can discuss later.

**Comment by NathayaMDOL** [comment]
This issue has been fixed. See screenshot below.
![746-employees](https://user-images.githubusercontent.com/40499717/43342502-dd1bccb8-91b0-11e8-92a6-a5345a01cbf3.png)

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
