### ISSUE TITLE
Bug: No error message. Worker site/employee >Add New Employee  Field: Productivity measure/rating for job described above

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#748]
Bug description:
Area: Worker site/employee >Add New Employee 
Field: Productivity measure/rating for job described above

Issue: No Error validation message

Fix: The following error message should display:

“Please select the productivity measure/rating for job described above.”
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/52569d3b-c771-4c1c-b81b-1e7e61496602)

**Comment by NathayaMDOL** [comment]
Closed! This issue has been fixed in #722 .
