### ISSUE TITLE
Bug: No error message is displaying if you don’t answer this question

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#749]
Bug description:
Field: How many workers with disabilities were paid an hourly subminimum wage during the most recently completed fiscal quarter?
Issue:  No error message is displaying if you don’t answer this question.

Steps: 
> Select ‘Hourly”, but do not enter any info for the following question: How many workers with disabilities were paid an hourly subminimum wage during the most recently completed fiscal quarter?
No error message displays.
> Wage Data > Select Hourly for the first question > Save page > Go to Review & Submit > Wage Data > Edit Responses.

Fix: System should display the following error message:
“Please indicate if the employer paid hourly subminimum wage rates to workers with disab”ilities during the most recently completed fiscal quarter.

![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/b96522d2-141e-46d5-9d64-3bf41366dc2d)

**Comment by NathayaMDOL** [comment]
Hi @binwang89, @EStriegel 
For this issue, there are 2 sections.
1. On Hourly Tab.
2. On Piece Rate Tab.
Do both sections use the same Message? If not can you please provide each error message?

Thanks,
Nathaya

**Comment by NathayaMDOL** [comment]
From @EStriegel  email. 
The error messages for hourly and piece rate.
**For hourly:** 
Please indicate how many workers with disabilities were paid an hourly subminimum wage during the most recently completed fiscal quarter.

**For Piece Rate:**
Please indicate how many workers with disabilities received subminimum wages and were paid a piece rate during the most recently completed fiscal quarter.
![image](https://user-images.githubusercontent.com/40499717/43974062-57e24c5a-9ca7-11e8-9277-00a7ed0d7654.png)

**Comment by NathayaMDOL** [comment]
This issue has been fixed. Branch: "whd-aqa-749-nmankong-wagedata-errormsg-howmanyworkers"
![piecerate](https://user-images.githubusercontent.com/40499717/43974560-f62b2b4c-9ca8-11e8-9555-ff06c8a58323.PNG)
![hourly](https://user-images.githubusercontent.com/40499717/43974561-f639bb76-9ca8-11e8-9c56-7f6a40f62ebd.PNG)

**Comment by binwang89** [comment]
@NathayaMDOL Working fine. Pass and moved to "Done'

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
