### ISSUE TITLE
Deploy Section 14c - OCIO-OASAM Dev  

### ISSUE THREAD

**Issue by johnsonpatrickk** [18F/dol-whd-14c#75]
**OCIO-OASAM Operation Stories**
1. \- [ ] Deploy development virtual machines (Infrastructure Team) - In progress (10/24/16)
   - [x] Windows 2012 Template - In progress (10/24/16)
   - [ ] RHEL 6.8 Template - In progress (10/24/16)
2. \- [ ] Install and configure application IIS 7.5/.Net 4.5
3. \- [ ] Install and configure PostgreSQL 9.x
4. \- [ ] Mirror 18F/dol-whd-14c repository to OCIO Enterprise GitLab repository
   - [x] Auto pull 8F/dol-whd-14c repo every hour
5. \- [ ] Review Section 14c [README specs](https://github.com/18F/dol-whd-14c#3-dotnetcoveragereportzip) 
6. \- [ ] Configure Dev evironment to auto deploy on pull

**Comment by johnsonpatrickk** [comment]
What I did on 10/25/2016:
Installed IIS 8.5.9 with .Net 4.5.2  on Windows 2012 R2
Installed PostgreSQL 9.4 on RHEL 6.8
Installed Web Deploy 3.6 for hosting server

What I plan on doing for 10/26/2016:
Install & configure git client on Windows 2012 R2
Pull Section 14c code from GitHub
Integrate & test 2 methods of auto deploy for .Net 4.5 app
Determine the best practice method for Section 14c app

Issues/blockers:
Multitask between several projects

**Comment by mmurthydol** [comment]
Omid, Greg: Issue can be closed here.
Michelle: Issue created in GitLab for DOL.
