### ISSUE TITLE
Bug : Issue for register an employer page – validation causing submit function.

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#754]
Bug description:
When register an employer, after correct  the errors, hit the "Register Employer" button, the validation will cause the register function not working. User needs to refresh the page, and re-enter all the information to make the registration works again. Please see below screenshots:

Error happen in the registration process
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/e607225e-10ce-4b13-8dd0-03b21af89899)

User correct the error and hit the "Register Employer", nothing happen. 

![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/1fd5ada9-b25d-4c2d-8e76-587ae97e0ede)

**Comment by NathayaMDOL** [comment]
This issue has been fixed and pushed with branch "whd-aqa-627-nmankong-508-keyboard-access-issue"

**Comment by binwang89** [comment]
@NathayaMDOL Tested and Pass.

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
