### ISSUE TITLE
Bug: API - EIN validation is missing on employer tab.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#756]
User should be able to submit section14c applications with different EIN numbers.
- [x] Add new column to employer_info database table.
- [x] Update the API save/submit methods to save/retrieve the EIN number.

**Comment by PrabhakarThummalaDOL** [comment]
@binwang89  @NathayaMDOL 
Please review and add dependency to #718

**Comment by PrabhakarThummalaDOL** [comment]
Completed.

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
