### ISSUE TITLE
Bug UI: Inactivity warning formatting issue

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#757]
Note from Madhu: Add extra spaces in front of the word "Your" to see if that works.

The black exclamation triangle is covering up the word "Your".

![image.png](https://images.zenhubusercontent.com/57e9239095e42b6c5ba972b8/ca685a26-f8de-4a93-9669-cf47ed83f049)

**Comment by NathayaMDOL** [comment]
This issue has been fixed as a screenshot below. 
![757 session time out](https://user-images.githubusercontent.com/40499717/43010186-c513fe22-8c0d-11e8-8e6b-419096fa28e2.png)

**Comment by binwang89** [comment]
@EStriegel @mmurthydol @NathayaMDOL the screenshot looks good to me. i think we can push it to DEV.

**Comment by NathayaMDOL** [comment]
@binwang89 , All changes have been pushed to Dev.

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
