### ISSUE TITLE
Bug: Profile Password change email text box must be highlighted with gray background color

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#759]
- [x] Verify this text box is disabled already
- [x] set background color to standard gray
- [x] Ensure 508 compliance. @binwang89 Should tab to the email textbox or ignore? please let Nathaya know.

**Comment by NathayaMDOL** [comment]
This issue has been completed in story #758 and pushed to dev.

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
