### ISSUE TITLE
As a WHD Security Officer, I would like each User's session to timeout from inactivity set to WHD policies

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#76]
Refer to prototype here for behavior: https://preview.uxpin.com/6dc6e8912fdaeb32cdfefa6e237f0d300d960588#/pages/77031627/simulate/no-panels?mode=i
**Note:** On the first page, click anywhere on the dark modal background to simulate the session expiring. 

Descripition:
In Ref to NIST Control AC-12, The WHD Organiation Defined Perameter (ODP) will be provided so that it can be enforced by the information system - 15 mins of inactivity

TODO WHD Provide clarification on 15 min vs 60 min (DIT); WHD business needs to provide clarification on what should happen with "Application Status". Also what UX behavior do we expect in terms of a popup or something to remind user that session is about to timeout?

Tasks:
- [ ] User session timeout value is configured in web.config and provided to UI through some existing means (API?)
- [ ] Implement web server session timeout
- [ ] Create running task to track timeout
- [ ] Create alert/notification to user at a set interval before the timeout occurs, following 508 standards
- [x] Alert should go by USWDS

Acceptance Criteria:  After 60 minutes of inactivity any logged in user should be automatically logged out and their session should be terminated.  At a set interval before that timeout, alert should be thrown to current logged in user that in x interval (minutes) they will be logged out and their session terminated.
Considerations:
1. Application Status
   WHD Business position: Filled out Application Status values must be saved.
   IT position: Currently Application Status values are saved when moving to the next page. Hence fair to expect values must not be saved. In addition saving values in weird states left by the user is a complex problem and needs workflow/context implementation internally and not recommended.
2. Role: Any logged in User

**Comment by afrimpong** [comment]
Agreed

**Comment by MrMatt57** [comment]
The application currently uses an OAuth Resource Owner Password Credentials flow.   This flow yields an access token for subsequent requests to the API via a bearer authentication header.   The expiration of the token is currently set to 14 days.  After that, the user must log in again.  This duration is configurable in the AccessTokenExpireTimeSpanMinutes parameter.

**Comment by bggordon** [comment]
Can the AccessTokenExpireTimeSpanMinutes parameter be set to 60 minutes? Also, does the information system provide the capability to notify the user prior to the AccessTokenExpireTimeSpanMinutes parameter being enforced?

**Comment by jmmcnj** [comment]
For modern websites Oauth tokens are used with longer expiration periods for flexibilty for mobile devices, setting to 60 minutes will dissuage mobile users from using the application and decrease the functionality.  We could set the AccessTokenExpireTimeSpanMinutes param to 60 minutes but do not recommend for the reason just stated.

**Comment by michellewang89** [comment]
For Section 508 compliance,  we need the system provide the capability to notify the user prior to User's session to timeout from inactivity.

**Comment by mgwalker** [comment]
Wiggling the mouse can count as activity for the purposes of idle timeout.

@MrMatt57 or @jmmcnj: Does the `AccessTokenExpireTimeSpanMinutes` config operate like a sliding window, or is the expiration time set at precisely this number of minutes after the token is created?

**Comment by mgwalker** [comment]
This may go into the next buy and, depending on the complexity, is a candidate for a micropurchase.

**Comment by binwang89** [comment]
The information system prevents further access to the system by initiating a session lock after 15 minutes of inactivity

**Comment by phirefly** [comment]
@mmurthydol 
1. Application status: Filled out information filled in while timed out should be saved. @simplyshang can verify if there's already an auto save in place -- which would support this.
2. Popup: No preference, but can we refer to existing applications in government / best practicies? @simplyshang may have a recommendation.

**Comment by mmurthydol** [comment]
@phirefly More of a DIT related reqs needed. IT can provide recommendation based on existing approved applications + shannon thoughts. No UX  research needed of course. (1) above - need to discuss/consider implications.

**Comment by mgwalker** [comment]
I'll push back on the comment that "No UX research needed."  Even if there's a DIT requirement, any time we're impacting the user experience and thus the usability of the app, I think we should consider user research if the requirement is not *obviously* in line with accepted best practices.  If the requirement is detrimental to usability, we should then try to push up the policy chain and see if we can get it changed.  The only way to really understand the usability impact is user research. 🙂

**Comment by mmurthydol** [comment]
@mgwalker Greg, Like everything else in the project even User Research will be prioritized :)

**Comment by mmurthydol** [comment]
Wanted to note that application is saving the page state behind the scenes

**Comment by simplyshang** [comment]
Prototype for session timeout: https://preview.uxpin.com/6dc6e8912fdaeb32cdfefa6e237f0d300d960588#/pages/77031627/simulate/no-panels?mode=i

Mouse over the page, wait one second, then the session timeout alert will appear.

**Comment by jmmcnj** [comment]
spin off implementation to separate user story and reference this story as dependency @jmmcnj

**Comment by suprenant** [comment]
From grooming – moving this back to In Progress since we gave feedback. @simplyshang if that's not right, please move this to the correct column.

**Comment by simplyshang** [comment]
Please use the most recent prototype link: https://preview.uxpin.com/6dc6e8912fdaeb32cdfefa6e237f0d300d960588#/pages/77031627/simulate/no-panels?mode=i

**Comment by simplyshang** [comment]
Needs an implementation story.

**Comment by jmmcnj** [comment]
Create Implementation associated User Story before final review/closeout

**Comment by binwang89** [comment]
Found the #464 for implementation.
