### ISSUE TITLE
Bug: API - Validate column length for CITY and STREET_ADDRESS1 columns.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#763]
- [x] API: Restrict the column data length to the size of the database column (for Addresses.City and Addresses.Street_Address1).

**Comment by PrabhakarThummalaDOL** [comment]
Completed. Ready for code review.

**Comment by PrabhakarThummalaDOL** [comment]
Completed.

**Comment by EStriegel** [comment]
Confirmed in demo on 8/2.  Closed.
