### ISSUE TITLE
Security: API - Before performing a database retrieve or update operation verify if the logged in user is authorized.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#773]
- [x] Application Controller

1. Submit() *
2. GetApplication() - done
3. GetApplicationsSummary()
4. ChangeApplicationStatus() - done
5. GetApplicationDocument() - done
6. DownloadApplicationDocument() - done
- [x] Account Controller

1. Register()
2. UserInfo() *
3. SetUserEmployer()
4. CreateOrUpdateEmployerApplication() *
5. ResetPassword()
6. VerifyResetPassword()
7. ChangePassword()
8. VerifyEmail()
9. VerifyReactivateAccount()
10. Logout()
11. GetAccounts() - done
12. GetSingleAccount()
13. GetRoles()
14. CreateAccount() - done
15. ModifyAccount() - done
16. PasswordComplexityCheck()
17. SendAuthenticationCode()
18. AccountAdminResendConfirmationEmail() *
19. AccountAdminResetPassword() *
20. AccountAdminResendAuthenticationCode() *

- [x] Attachment Controller

1. Post() ~SubmitApplication *
2. Download() *
3. Delete() *

- [ ] Response Controller

1. Get()

- [x] Save Controller

1. GetSave() *
2. AddSave() *
3. UpdateSave() *
4. DeleteSave() *
5. ClearApplicationData() *

- [ ] Status Controller

1. GetStatuses()

- [ ] SupportedFileTypes Controller

1. GetSupportedFileTypes()

- [x] UserActivity Controller

1. GetCreatedUsers() - done
2. GetUpdatedUsers()- done
3. GetActiveUsers()- done
4. GetInactiveUsers()- done
5. GetDeletedUsers()- done
6. GetUserActivity()- done
7. GetRoleActivity()- done
8. GetRoleLoginActivity()- done
9. GetUserLoginActivity()- done

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
