### ISSUE TITLE
Security Audit Reports: Generate .csv/.xls reports and send them via email to security team.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#774]
Security Audit Reports: Need audit log reports (.csv/.xls format) to be generated on application startup (on a specific date of the month - configurable) and to be send via email to the security team:
- [x] Login/logout Activity Report: 
Report columns: Unique User Info  (email, name), User Role, User Activity (log in, log out), Date (includes time)
- [x] User Creation Activity Report: 
Report columns: Unique Created User Info  (email, name), Unique Created By “System Administrator” User Info (email, name), Date (includes time)
- [x] Active User Report: 
Report columns: Unique Active User Info  (email, name), Active User Role, Date (includes time)
- [x] User Deactivated/Reactivated User Report:   
Report columns: Unique User Info  (email, name), Action (Deactivated/Reactivated), Unique “System Administrator” User Info (email, name), Date (includes time)
- [x] User Deleted/Undeleted User Report:  
Report columns: Unique User Info  (email, name), Action (Deleted/Undeleted), Unique “System Administrator” User Info (email, name), Date (includes time).
- [x] User Role Changes Report:  
Report columns: Unique User Info  (email, name), User roles, Unique “System Administrator” User Info (email, name), Roles (of the user who made the change), Date (includes time).

**Comment by PrabhakarThummalaDOL** [comment]
Completed. Awaiting acceptance.

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
