### ISSUE TITLE
Additional: YourAccount page-UI&URL changes

### ISSUE THREAD

**Issue by NathayaMDOL** [18F/dol-whd-14c#786]
Additional from team.
- [x] Update URL to “youraccount”. Also the top right link and breadcrumb to “Your Account” 
- [x] Font size for “Registered Employer” and “Change Password” should be smaller than both the header we are adding, and the “Section 14(c) Certificate Application” header at the top.
- [x] 2 columns can be styled as follows (as w/ Netflix below): Line header of the “Registered Employer” and “Change Password” in the rounded box. As long as there are no 508 contrast issues, “Registered Employer” and “Change Password” have slightly different background. 

![netflix](https://user-images.githubusercontent.com/40499717/44273460-8f76c400-a20d-11e8-8688-de53aaef09b2.gif)

**Comment by binwang89** [comment]
@NathayaMDOL Please make sure it will meet 508 standards, and pass the test in IE.

**Comment by NathayaMDOL** [comment]
Completed and pushed to Dev. Screenshot below.
Branch: "whd-aqa-786-nmankong-youraccount-ui-url-changes"

![1](https://user-images.githubusercontent.com/40499717/44809032-acab7b00-ab9b-11e8-9d5e-2876aad0927b.png)
![2](https://user-images.githubusercontent.com/40499717/44809035-af0dd500-ab9b-11e8-86e7-14b5e5325e6a.png)

**Comment by binwang89** [comment]
@NathayaMDOL it looks good. 
![image](https://user-images.githubusercontent.com/25330625/45165301-91a3c100-b1c2-11e8-8be6-cab28be5f73e.png)

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
