### ISSUE TITLE
As a WHD Security Officer, I would like the application to audit the execution of privileged functions.

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#79]
Same as #78 

- [ ] Result info must include API route, action method name,  action parameters, datetime, username, user email. TODO Determine order of result, what else needed in result.
 
Descripition:
In ref to NIST Control AC-6(9), AUDITING USE OF PRIVILEGED FUNCTIONS () The information system audits the execution of privileged functions. 

TODO WHD Business/DIT Provide requirements:  **What is the definition of Privileged?**

Note to AIS: Application activity logging alreaday contains this info.  Write an audit API that will return security audit info. 

TODO WHD DIT Need to determine which role is allowed to call this api (System Administrator?)

Privileged account refers to the Administrator account that will be seeded upon creation of the application.  All events performed by the Administrator account, role assignment, etc should be captured in the database for audit purposes.

Tasks:
- [ ] Capture running audit log of Administrator events performed

Acceptance Criteria:  Administrator account will performs some actions and then database tables will be checked to ensure events were captured.
Considerations:
1. Application Status
2. Role

**Comment by afrimpong** [comment]
Agreed

**Comment by jmmcnj** [comment]
Matt please provide what has been done and what is left to complete/close out this issue

**Comment by jmmcnj** [comment]
There are author and date time stamps for every action in the system, in order to create a log of Admin role functions performed DoL would have to create a report that crosses the users account table filtered by admin role against any other tables to query admin role functions performed

**Comment by michellewang89** [comment]
we need to capture every activity ( who, when)  from Admin role functions performed, not only the creation and last modify information.

**Comment by mgwalker** [comment]
This might be accomplished with an `events` type table that has a row for every event instead of capturing creation and last modification directly in the data models.  The report would still be a separate function, but the key is to make sure the data is captured.

This may go into the next buy and, thanks to the way the code was architected, it is also a candidate for a micropurchase.

**Comment by phirefly** [comment]
@mmurthydol can we remove the `WHD Provide requirements` from here? Sounds like this is flushed out -- capture activities of the administrator. Let me know what you think.

**Comment by mmurthydol** [comment]
@phirefly This one needs specification from security; on IT side; no reqs needed from business;

**Comment by mmurthydol** [comment]
same as #78 and hence closed
