### ISSUE TITLE
Bug: Accessibility keyboard Access -- Wage Data

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#790]
Bug Description:
Wage Date, select both hourly/piece rate.  after complete the hourly page, tabbed and clicked on "Next: Add Piece Rate", the piece rate page open,  tab again, the focus on piece rate footer, not in beginning of piece rate page. 

![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/5f473381-457c-4464-87e1-46bd69e30627)

![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/68b3ab49-3ef8-4b88-a804-3b181a4890be)

**Comment by NathayaMDOL** [comment]
@binwang89 ,
This issue has been fixed. After clicking "Next: Add Piece Rate", the focus will be on help"?" button on Piece Rate tab (See screenshot below). This branch is also included fixing entering keyboard access on "Show Help for All Items" button to toggle all help message box.
Branch : "whd-aqa-nmankong-790-wagedata-a11y-keyboard-access"

![image](https://user-images.githubusercontent.com/40499717/45049614-2684ae00-b04d-11e8-9e05-148db4b9b82d.png)

**Comment by binwang89** [comment]
@NathayaMDOL it looks good

**Comment by EStriegel** [comment]
Confirmed 9/6.  Closed.
