### ISSUE TITLE
As a Certification Team Member and a Certification Team Manager, I need a system that will only allow submission of a complete application (i.e. all applicable fields answered and documents attached), so that I can more effectively use time reviewing applications.

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#8]
related to #507
Descripition:
Identified rules for the summary validation, to ensure a complete form is submitted by the Applicant.  All fields presented to the user should have a response except fax number (requires a response/check box).  Prevailing wage surveys, attach an additional sheet if needed (not required)

Tasks:
- [x] apply rules that get fed into User STory #58
- [x] submit form, save data to database, provide user verification statement pre-submit

Acceptance Criteria: User clicks on summary view and submits application. Valid application is saved to the database, invalid application returns errors (not visible/in UI)
Considerations:
1. Application Status
2. Role: Applicant

Card #4 is asking that we only allow complete applications to be submitted (we will have a predetermined criteria defining 'complete'). cc: @elizabethstriegel

**Comment by EStriegel** [comment]
The attached provides more specifics on required fields and how they interact with conditional logic. Let me know if you have any questions.
[14c Form Requirements & Logic.xlsx](https://github.com/18F/dol-whd-14c/files/551813/14c.Form.Requirements.Logic.xlsx)

**Comment by rrefoy** [comment]
Cannot be moved to done until #101 is complete.

**Comment by mgwalker** [comment]
See #92.  I can't verify this behavior.

**Comment by phirefly** [comment]
Per discussion: this does not include logging in by the cert team analyst/manager for milestone 1.

**Comment by binwang89** [comment]
Tested the 14c,  found some required fields still not received an error message when user missed entering the data.  I have put some highlight on the requirements excel provided by @EStriegel 
[14c.Form.Requirements.Logic_07312017.xlsx](https://github.com/18F/dol-whd-14c/files/1188044/14c.Form.Requirements.Logic_07312017.xlsx)

**Comment by EStriegel** [comment]
Could not recreate https://github.com/18F/dol-whd-14c/issues/8#issuecomment-319105938

Moving to `Done`
