### ISSUE TITLE
508 Scan: All 508 issues after 508 testing have been fixed 

### ISSUE THREAD

**Issue by NathayaMDOL** [18F/dol-whd-14c#804]
[https://app.zenhub.com/files/68946896/aeb377cb-4046-4111-a123-a5753fe589c0/download](https://app.zenhub.com/files/68946896/aeb377cb-4046-4111-a123-a5753fe589c0/download)

**Comment by NathayaMDOL** [comment]
Note: For first round 508 fixed has been deployed on 9/21/2018 are included. 
1. DHS Test #3 (Added Label,Id,field,legend), #5 (Added password validation on Create account), #8 (Added Table Header)
2. DHS Test #2 (focus does not remain within a modal dialog box): this issue has been fixed on all pop up except on Attachment File pop up box.
See attached (Highlight issues are remaining issue, Strikeout issues are no need to focus for now)

[508 scan - 14C - round 4 testing - version 2.docx](https://github.com/18F/dol-whd-14c/files/2412175/508.scan.-.14C.-.round.4.testing.-.version.2.docx)

**Comment by binwang89** [comment]
@NathayaMDOL  thanks, i have forwarded to DHS tester for re-test.

**Comment by NathayaMDOL** [comment]
All 508 feedback from Darya email (see attached file) and popup focusing issues have been fixed. There is an issue on Anchor tags without HREF (DHS Test#4) need to investigate and talk @binwang89.

[RE_ remaining 508-Scan issue.pdf](https://github.com/18F/dol-whd-14c/files/2425336/RE_.remaining.508-Scan.issue.pdf)
[508 scan - 14C - round 4 testing - version 2.docx](https://github.com/18F/dol-whd-14c/files/2425334/508.scan.-.14C.-.round.4.testing.-.version.2.docx)

**Comment by NathayaMDOL** [comment]
- For an issue DHS Test#4, A link does not have a unique and meaningful description. 
The fix I have found is using aria attributes for SCREEN READER to read out the meaningful description. References: https://www.levelaccess.com/indicating-link-purpose-aria/
Example: <a href="" aria-label="Close button"............></a>  -->SCREEN READER will read "Close button"

- For testing, @binwang89 recommended using "Ease of Access center tool" from window to test reading. Result: It announces the aria-label value as expected.

- FYI: All issue from Darya 508 testing has been completed except css-off (#1, #6 and #7)
Branch: included the fix in date field branch "whd-aqa-741-nmankong-bug-date-field"

**Comment by binwang89** [comment]
@NathayaMDOL  please create a user story for  CSS-off items and reference to this user story, i will close this one.
