### ISSUE TITLE
As a WHD Security Officer, I would like the system to generate audit records

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#82]
Descripition:
In Ref to NIST Control AU-12, AUDIT GENERATION () The information system: Provides audit record generation capability for the auditable events defined in AU-2 a. at [Assignment: organization-defined information system components]; Allows [Assignment: organization-defined personnel or roles] to select which auditable events are to be audited by specific components of the information system; and Generates audit records for the events defined in AU-2 d. with the content defined in AU-3.

Capture the state in the database for records and in the appropriate format to be analyzed by an analysis logging tool, does this include tooling?, AIS is not providing tooling around logs analysis, could possibly use System Center (MS) or Splunk

Notes from AIS: tool provided by DOL, AIS team to make sure audit records are accessible from within database to the tool that DOL selects to generate reports from the database.

Tasks:
- [ ] No tasks here, tasks to capture audit information in User STories #83 and #84

Acceptance Criteria:
Considerations:
1. Application Status
2. Role

**Comment by mgwalker** [comment]
Since the audit records will be in the database, getting them into a report should be as simple as a SQL query, correct?  That could be an MVP to satisfy this requirement in the immediate term.  Then DOL can massage the query output into their internal tools at some time in the future.  This does not seem like it requires any additional effort from AIS aside from getting audit records into the database.

**Comment by jmmcnj** [comment]
This is then completed based on the comments above will speak to DOL to get this closed out

**Comment by bggordon** [comment]
Agree. This can be closed.

**Comment by binwang89** [comment]
we need to revisit this user story about how we will handle the audit records, or at lease revisit this item in next session.

**Comment by mmurthydol** [comment]
Michelle, This is a story that needs to be captured on non-vendor side (a) OCIO GitLab (b) DIT JIRA
