### ISSUE TITLE
As a WHD Security Officer, I would like the system to capture specific information about audit events being tracked

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#83]
Descripition:
In Ref to NIST Control AU-3, CONTENT OF AUDIT RECORDS () The information system generates audit records containing information that establishes what type of event occurred, when the event occurred, where the event occurred, the source of the event, the outcome of the event, and the identity of any individuals or subjects associated with the event.

Add Created/Updated, User/Timestamp to each record in Db, these pieces of information on audit events are captured and consolidated into User Story #84.  Please defer to that user story, there are no tasks for this user story

Tasks:
- [ ] No Tasks for this user story, see user story #84

Acceptance Criteria: see User Story #84
Considerations:
1. Application Status
2. Role

**Comment by mgwalker** [comment]
This appears to be satisfied by appliedis/dol-whd-14c@f5f29ea with the creation of the `IAuditedEntity` interface and the expansion of the `ApplicationDbContext` class.  Is that correct?

**Comment by afrimpong** [comment]
For #83, 84 & 86 - Employee Name and ID are fields that the events will be associated

**Comment by jmmcnj** [comment]
Is this satisfied through the above referenced code by Greg?

**Comment by bggordon** [comment]
See comments provided for #84 and #86.

**Comment by jmmcnj** [comment]
Closed based on DOL's Decision

**Comment by binwang89** [comment]
capture audit information in User Stories #84

**Comment by mmurthydol** [comment]
Need to reopen. 
Add following audit columns in MS identity implementation: Created, Updated, Username, Timestamp.
These columns were not implemented in Phase 1. MS identity framework provides out of the box functionality for implementing this.
