### ISSUE TITLE
Security: UI - Mask EIN number.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#831]
@NathayaMDOL 
- [x] Mask EIN number.

**Comment by NathayaMDOL** [comment]
This issue has been completed. Using password type to mask the field and have a hyperlink to show/hide EIN number. See screenshot below.

![hideein](https://user-images.githubusercontent.com/40499717/47879043-0f1c3400-ddf6-11e8-9ac0-d3b7e9b4cffe.jpg)
![showein](https://user-images.githubusercontent.com/40499717/47879059-14797e80-ddf6-11e8-97a6-a7d5992dcb98.jpg)

Branch: "whd-aqa-831-nmankong-mask-emplyer-ein-number"

**Comment by NathayaMDOL** [comment]
The request has been canceled. Closed!
