### ISSUE TITLE
As a WHD Security Officer, I would like the system to capture Additional Audit information

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#84]
Descripition:
In Ref to NIST Control AU-3(1), ADDITIONAL AUDIT INFORMATION () The information system generates audit records containing the following additional information: [Assignment: organization-defined additional, more detailed information].

Note: This User story consolidates User STories #83 and #86 into this one
Capture the following information:
Add
Created
Updated
Username
Timestamp

For the following events:
WHD will provide the defined list of auditable events:
1. Employee Name (Not sure how this is an event?)
2. Employee ID (Not sure how this is an event?)
3. Login Date
4. Login Time
5. Logout Date
6. Logout Time
7. Admin activities - Create, modify, delete account and access

Tasks:
- [ ] Create db schema to support capturing the above mentioned data for the above mentioned events
- [ ] Implement the data store of those events

Acceptance Criteria: Db schema will show the events and DOL's reporting tool could be used to pull data and generate reports.
Considerations:
1. Application Status
2. Role

**Comment by mgwalker** [comment]
This looks like it is mostly satisfied by AppliedIS/dol-whd-14c@f5f29ea by adding the `BaseEntity` parent class to the models.

**Comment by afrimpong** [comment]
For #83, 84 & 86 - Employee Name and ID are fields that the events will be associated

**Comment by jmmcnj** [comment]
AIS has implemented the the following actions captured in the system:Add
Created
Updated
Username
Timestamp

but are only addressing the events:Admin activities - Create, modify, delete account and access

**Comment by bggordon** [comment]
Based on the updates made by AIS, this item can be closed.

**Comment by jmmcnj** [comment]
closing based on DOL decision

**Comment by binwang89** [comment]
this item may need to revisit and re-open. the DOL's reporting part to pull data and generate report is not done yet.

**Comment by mmurthydol** [comment]
Need to reopen.  Do not see any audit columns in the DB regardless of what AIS claimed. 

Add following audit columns in MS identity implementation: Created, Updated, Username, Timestamp.
These columns were not implemented in Phase 1. MS identity framework provides out of the box functionality for implementing this.

**Comment by mmurthydol** [comment]
Michelle, 

We need a story on non-vendor side (OCIO/DIT) to provide a report for this data if not this report is not already included in #82

**Comment by mgwalker** [comment]
See the entity base class here:
https://github.com/AppliedIS/dol-whd-14c/blob/master/DOL.WHD.Section14c.Domain/BaseEntity.cs

It adds `CreatedBy`, `CreatedAt`, `LastModifiedBy`, and `LastModifiedAt` columns to every entity class that derives from it, and records when the entity was created and when it was last modified.  I no longer have a VM with the app running so I can't re-verify that the columns are actually created, but I recall seeing them in the past.  So that part of this issue should be resolved.

Rather than re-open this user story, I would suggest creating one or multiple new stories.  We can talk about how to break them down to make them granular and atomic enough to be easy to understand.  I think one of the problems the vendor had was many of these user stories covered an enormous amount of territory and weren't very clear.  (Plus a lot of the security-related stories were pushed on at the last minute.  I appreciate that you're getting in front of them, that should make this second go-around a lot smoother!)

**Comment by mmurthydol** [comment]
Greg, 

Nice to hear from you. Thanks for the response! Sadly, Microsoft Identity Framework entities are not derived from BaseEntity (they have their own, different base class) and as such do not have these fields.

I agree the stories were confusing to wade through. I am all for granular/atomic groomed stories with associated tasks. When we sync up & go through our grooming session, we have a chance to start afresh & create new issues as you suggested.  

For now, "reopen" was a marker for us (Michelle/myself) to remember we need to address these issues & make notes for our grooming session. I am imagining/hoping we'll have a clean project/issue slate to start Phase 2.

**Comment by mgwalker** [comment]
Point well taken about not automatically deriving from `BaseEntity`, and my bad for not finishing that thought.  The other models do explicitly derive from `BaseEntity`.  E.g.:  https://github.com/AppliedIS/dol-whd-14c/blob/master/DOL.WHD.Section14c.Domain/Models/Address.cs#L5

But you said you weren't seeing the columns in the database, so we should definitely take a look at it once a vendor is onboard.

Sorry for the misunderstanding about "reopen."  We're all good!  😄

**Comment by mmurthydol** [comment]
No biggie. Thanks for watching out :) 

The columns for non Identity Framework related schemas are all good (Address through WorkerCountInfoes - strange spelling aside)  in the DB - no need for action on that count!

**Comment by mmurthydol** [comment]
#80 will implement one leftover (logout audit in LoginUsers or UserLogins table). Rest of the work completed.
