### ISSUE TITLE
Remove: EIN on the dashboard

### ISSUE THREAD

**Issue by NathayaMDOL** [18F/dol-whd-14c#842]
Remove the EIN column from the dashboard.

**Comment by NathayaMDOL** [comment]
Completed! The EIN column has been removed. Screenshot below.

![image](https://user-images.githubusercontent.com/40499717/49100064-0118d200-f241-11e8-82fb-b73f304f4bc7.png)

**Comment by binwang89** [comment]
Tested, it looks good
