### ISSUE TITLE
Link DOL seal and US DOL text to DOL URL in Header and Footer

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#848]
- [x]  Link any (a) DOL seal and (b) "United States Department of Labor" text in DOL header to the DOL homepage, which is: https://www.dol.gov/

![image](https://user-images.githubusercontent.com/25183303/49122854-3e528380-f284-11e8-8402-cb7380fe1d39.png)

- [x] Link any (a) The DOL seal and (b) "United States Department of Labor" text in DOL footer to the DOL homepage, which is: https://www.dol.gov/
![image](https://user-images.githubusercontent.com/25183303/49122874-532f1700-f284-11e8-99fc-6df5e91a3d46.png)

**Comment by NathayaMDOL** [comment]
@binwang89 , @EStriegel  This issue has been completed!

**Comment by binwang89** [comment]
@NathayaMDOL @EStriegel I tested it, but it does not working.

**Comment by binwang89** [comment]
@NathayaMDOL @EStriegel it works now. Thanks

**Comment by EStriegel** [comment]
@NathayaMDOL @binwang89 Confirmed.  Issued closed.
