### ISSUE TITLE
Ensure email validation rules are implemented correctly. Use OWASP email validation rule.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#849]
https://www.owasp.org/index.php/OWASP_Validation_Regex_Repository
Email validation regex: 
^[a-zA-Z0-9_+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$]

## Acceptance Criteria
- [ ] Ensure this email validation rule detects Stan's catch. Try this regex on a Web site (do not write a program).
- [ ] Use OWASP email validation rule (client side).
- [ ] Use OWASP email validation rule (server side).
- [x] Stan's text: When you create an account, the validation doesn’t check for the structure of “*@*.*”. Not sure exactly what your validation is, but it should require “TEXT@TEXT.TEXT” – not just “TEXT@TEXT”.

#### Accessibility
N/A

**Comment by PrabhakarThummalaDOL** [comment]
Fixed. 
Now the User Registration Email is validated same as Application Contact Email.

**Comment by binwang89** [comment]
@PrabhakarThummalaDOL @mmurthydol see the screenshot from testing 
![image](https://user-images.githubusercontent.com/25330625/49254992-c063b900-f3f8-11e8-88fb-2c64a6143a77.png)

after i corrected the email address
![image](https://user-images.githubusercontent.com/25330625/49255165-2f411200-f3f9-11e8-8d9f-71e1c9efd6b8.png)

**Comment by PrabhakarThummalaDOL** [comment]
Created a new story #876 for the uncompleted part of the story.
