### ISSUE TITLE
Clicking on ShowPassword must show/hide both passwords

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#850]
Do not create another ShowPassword link (contrary to what you might have heard from me).

Please feel free to assign between yourselves based on workload. Thanks,

**Comment by NathayaMDOL** [comment]
@binwang89 , @EStriegel This issue has been completed!

The changes are applied to pages below
•        Manage Users page (Reset Password)
•        User Registration/Create an Account page
•        Reset Password page
•        Change Password page
•        Reactivate Account page 

![image](https://user-images.githubusercontent.com/40499717/49179606-a0f95d00-f320-11e8-9d61-373c41a3f15b.png)

**Comment by binwang89** [comment]
@NathayaMDOL @EStriegel looks good 
![image](https://user-images.githubusercontent.com/25330625/49181317-0b140100-f325-11e8-8c8b-b3254fa101e1.png)
![image](https://user-images.githubusercontent.com/25330625/49181383-3dbdf980-f325-11e8-95e4-c989f2a87778.png)

![image](https://user-images.githubusercontent.com/25330625/49181587-c472d680-f325-11e8-87da-adc53fa8a600.png)

**Comment by EStriegel** [comment]
Confirmed and closed.
