### ISSUE TITLE
Help email address must be consistent across app

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#851]
- [x] Ensure that all occurrences of 14c-help@dol.gov, 14c-admin@dol.gov are replaced by WHD.14cOnlineApplication.Help@dol.gov

![image](https://user-images.githubusercontent.com/25183303/49127799-c93c7980-f296-11e8-9a2d-90874fb132cc.png)

**Comment by NathayaMDOL** [comment]
@binwang89 , @EStriegel This issue has been completed!

![image](https://user-images.githubusercontent.com/40499717/49179020-5cb98d00-f31f-11e8-9502-2dedf835758a.png)

**Comment by binwang89** [comment]
@NathayaMDOL @EStriegel it looks fine now
![image](https://user-images.githubusercontent.com/25330625/49179808-1cf3a500-f321-11e8-9365-739e7f007e9e.png)

**Comment by binwang89** [comment]
![image](https://user-images.githubusercontent.com/25330625/49179864-3ac10a00-f321-11e8-94be-222585062e7e.png)

**Comment by EStriegel** [comment]
@NathayaMDOL Can you confirm that the correct email address shows when we confirm an account has been created?  I unfortunately have run out of email addresses to check.  :)

**Comment by NathayaMDOL** [comment]
@EStriegel Confirm! All help email address has been replaced with the correct one. 
Ref: #834

**Comment by EStriegel** [comment]
Thanks! Confirmed and Closed.
