### ISSUE TITLE
Your Account Page Defects

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#852]
- [x] Missing an h2 section at top of the page (similar to the updated Help page). Do not need an "hr" element after.
 &lt;legend&gt; &lt;h2&gt; Your Account &lt;/h2&gt;&lt;/legend&gt;
- [x] "Your Account" Page should not be accessed by user when not logged in (like all the other pages in the App).

**Comment by EStriegel** [comment]
@mmurthydol @PrabhakarThummalaDOL @binwang89 @NathayaMDOL 

Seeing an extra change password section.  See screenshot.

![image](https://user-images.githubusercontent.com/19496579/49252561-59430600-f3f2-11e8-837b-812a9fb0c8b2.png)

**Comment by NathayaMDOL** [comment]
fixed! This is already on Prod.
