### ISSUE TITLE
Reset Password Page doesn't compare passwords entered for equality

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#853]
- [ ] When you try to change your password and the Confirm Password field value doesn’t match the New Password field value, there is no validation. The App seems to accept the Password entered in the "Password" field!!!! 
Please use code snippet from User Registration Page which seems to work correctly.

- [ ] The error messages isn’t helpful in this particular error condition. Change the error message in this case to: "New Password does not match Confirm Password.”

- [ ] Make sure all other Change Password pages implement the same functionality as above. 
- [ ] In addition please ensure user registration error message for this error case uses the same text as stated here (if not already).

![image](https://user-images.githubusercontent.com/25183303/49126652-621cc600-f292-11e8-9375-e9dbc82b42b6.png)

**Comment by PrabhakarThummalaDOL** [comment]
The 'new password' and 'confirm password' functionality to be review all the following scenarios:
1. User Registration
2. Change Password (Your Account)
3. Forgot/Reset Password
4. Change Password (from Admin page)
5. Reactivate a User.

**Comment by EStriegel** [comment]
@PrabhakarThummalaDOL 

Please put the new error message in the red box (and delete "An error occurred while resetting your password, Please try again later if the error persists).  We do not need the smaller error message under password.

![image](https://user-images.githubusercontent.com/19496579/49240641-aa8fcd00-f3d3-11e8-8368-e5290a327b44.png)

**Comment by EStriegel** [comment]
@PrabhakarThummalaDOL 

Tested the Your Account page.  Only edit would be to remove the smaller red exclamation point.

![image](https://user-images.githubusercontent.com/19496579/49240893-55a08680-f3d4-11e8-984b-69527a126b6e.png)

**Comment by EStriegel** [comment]
@PrabhakarThummalaDOL User Registration looks good.

@mmurthydol @binwang89 Can you test the below change password occurrences?  Not critical for launch as they are internal.
Change Password (from Admin page)
Reactivate a User.

**Comment by binwang89** [comment]
@EStriegel @PrabhakarThummalaDOL the small error message above the password has been removed. 
however, the smaller red exclamation point is still there. 
![image](https://user-images.githubusercontent.com/25330625/49242767-90f18400-f3d9-11e8-9912-e56f608f4b14.png)
 
![image](https://user-images.githubusercontent.com/25330625/49242808-aebee900-f3d9-11e8-8326-feeb81d6063b.png)

**Comment by binwang89** [comment]
@EStriegel @PrabhakarThummalaDOL  tested it in user registration and where should we show the error message ?  the smaller error message under password ?
![image](https://user-images.githubusercontent.com/25330625/49242944-14ab7080-f3da-11e8-9a34-614763359172.png)

**Comment by binwang89** [comment]
@PrabhakarThummalaDOL @EStriegel tested in Change Password (from Admin page), see below for screenshot 
![image](https://user-images.githubusercontent.com/25330625/49247548-8f2dbd80-f3e5-11e8-9e15-b8a38a374a81.png)
![image](https://user-images.githubusercontent.com/25330625/49247562-981e8f00-f3e5-11e8-8922-c29eacfcfdf3.png)

**Comment by binwang89** [comment]
@EStriegel @PrabhakarThummalaDOL tested it for Reactive account, please see the screenshot below

![image](https://user-images.githubusercontent.com/25330625/49246429-e67e5e80-f3e2-11e8-8d93-a418e7fcef5b.png)

**Comment by binwang89** [comment]
@PrabhakarThummalaDOL @EStriegel tested in  Forgot/Reset Password, please see the result 

![image](https://user-images.githubusercontent.com/25330625/49247221-bfc12780-f3e4-11e8-93f7-1a63500fcefb.png)

**Comment by NathayaMDOL** [comment]
Completed!

**Comment by binwang89** [comment]
@mmurthydol @PrabhakarThummalaDOL @NathayaMDOL  retested the Reactivate a User,  i did not get the email to reset the password last time.

**Comment by binwang89** [comment]
@mmurthydol @PrabhakarThummalaDOL @NathayaMDOL done on testing, i uploaded the latest screenshots for each test case. 
[#853.docx](https://github.com/18F/dol-whd-14c/files/2631042/853.docx)

**Comment by binwang89** [comment]
@NathayaMDOL @PrabhakarThummalaDOL @mmurthydol Re-tested, it looks good now.
