### ISSUE TITLE
Register An Employer page: Help Link doesn't work for logged in user.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#854]
This might potentially be a tricky story. Work on other stories before scoping this one out. 

When you’re logged in but have not completed the “Register An Employer” page, you can’t go to the Help page (https://section14c.dol.gov/#!/help). When you click on Help, the page loads and then re-directs back to the Register An Employer page.

![image](https://user-images.githubusercontent.com/25183303/49125790-5085ef00-f28f-11e8-8d19-3323c17b46f5.png)

**Comment by NathayaMDOL** [comment]
duplicate to #864.
