### ISSUE TITLE
Employer Registration Page Certification Number text box is not wide enough

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#855]
In Microsoft Edge (Windows 10 / ver. 38.14393.2068.0), the full entered establishment certificate number can’t be viewed while you are entering the number because the field is not wide enough due to that “X” that is used to clear the field.

- [x] Please make the textbox field wide enough to allow for problem in Microsoft Edge.
- [x] Test what happens in Chrome F12 using different browser/device types with this one.

![image](https://user-images.githubusercontent.com/25183303/49126405-77452500-f291-11e8-9f39-167144e52141.png)

**Comment by NathayaMDOL** [comment]
Completed

**Comment by binwang89** [comment]
@NathayaMDOL @EStriegel I tested in DEV environment. It looks good now.  Please see below screenshot. 
![image](https://user-images.githubusercontent.com/25330625/49232114-55e35680-f3c1-11e8-9a55-98f083e579ac.png)

**Comment by binwang89** [comment]
move to closed
