### ISSUE TITLE
Data table grid displays "nullN/A" instead of blank

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#857]
WORK SITES AND EMPLOYEES
https://section14c.dol.gov/#!/section/work-sites

After entering a Work Site, the Number of employees is listed as “nullN/A”. 

- [ ] Please display blank instead.

![image](https://user-images.githubusercontent.com/25183303/49127764-ab6f1480-f296-11e8-805d-a4372a323b2f.png)

**Comment by NathayaMDOL** [comment]
Completed

**Comment by binwang89** [comment]
@NathayaMDOL @EStriegel tested it and it looks good, please see below screenshot. I will move it to closed. 
![image](https://user-images.githubusercontent.com/25330625/49232559-300a8180-f3c2-11e8-93e8-601ca495cf56.png)
![image](https://user-images.githubusercontent.com/25330625/49232934-e706fd00-f3c2-11e8-800a-087e94de6d1e.png)
