### ISSUE TITLE
Submit page back button must be hidden after successful submission

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#858]
- [x] back button must be hidden after successful submission.

**Comment by NathayaMDOL** [comment]
Completed

**Comment by binwang89** [comment]
@NathayaMDOL @EStriegel tested it, it failed, I still see the back button. 
![image](https://user-images.githubusercontent.com/25330625/49233349-d5722500-f3c3-11e8-8567-0f55093963a5.png)

**Comment by NathayaMDOL** [comment]
I just tested it on Dev. It works fine on my end. @binwang89 Please make sure you test on DEV site!

![2 successful submitted application](https://user-images.githubusercontent.com/40499717/49233981-26cee400-f3c5-11e8-8742-385904fc938a.png)

**Comment by EStriegel** [comment]
Confirmed in Chrome.  @binwang89 Can you confirm in IE?

**Comment by binwang89** [comment]
@EStriegel @NathayaMDOL confirmed in IE. it looks good 
![image](https://user-images.githubusercontent.com/25330625/49242214-3a377a80-f3d8-11e8-99b8-d9106ea38190.png)
