### ISSUE TITLE
As a WHD Security Officer, I would like the system to provide the capability to process audit reports around "events of interest"

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#86]
Descripition:
In Ref to NIST Control AU-7(1), AUTOMATIC PROCESSING () The information system provides the capability to process audit records for events of interest based on [Assignment: organization-defined audit fields within audit records].

WHD will provide the defined list of auditable events.
auditable events were identified in User STory #84, capability to process audit reports will consist of DOL using a tool that they select to pull the database records and process to look for events of interest. There are no tasks or actions for this User story as most of the identified work is in User STory #84

Tasks:
- [ ] No Tasks identified for this User Story, see User STory #84

Acceptance Criteria: User STory #84 will provide the audit records that can be reported on by the reporting tool of DOL's choice
Considerations:
1. Application Status
2. Role

**Comment by mgwalker** [comment]
Since this issue is not actionable and describe what DOL will do (i.e., pick a tool to pull database records), can it be closed?

**Comment by afrimpong** [comment]
For #83, 84 & 86 - Employee Name and ID are fields that the events will be associated

**Comment by jmmcnj** [comment]
Can this be closed based on Greg's comments above?

**Comment by bggordon** [comment]
This item can be closed as long as the information system associates the requested information (Employee ID and Name) with activity performed by users.

**Comment by jmmcnj** [comment]
The identifier will be username and email which is one in the same, we do not have employee id mappings which I am assuming is an internal DOL identifier.

**Comment by bggordon** [comment]
Then I believe this can be closed.

**Comment by jmmcnj** [comment]
Closing based on DOL's Decision

**Comment by binwang89** [comment]
capture audit information in User Stories  #84

**Comment by mmurthydol** [comment]
Michelle,

We need a story on non-vendor side (OCIO/DIT) to provide a report for this data if this report is not already included in #82
Michelle,

We need a story on non-vendor side (OCIO/DIT) to provide a report for this data if this report is not already included in #82
