### ISSUE TITLE
Bug: Employer Registration Page: Help link is not usable.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#864]
When you’re logged in but have not completed the “Register An Employer” page, you can’t go to the Help page (https://section14c.dol.gov/#!/help). When you click on Help, the page loads and then re-directs back to the Register An Employer page.

![image](https://user-images.githubusercontent.com/25183303/49394982-4175c580-f703-11e8-9350-d7178ed7c1da.png)

## Acceptance Criteria

- [x] Help link must be usable on employer registration page. That is user must be able to view help page info.

#### Accessibility

- [x] The usual requirements.

**Comment by NathayaMDOL** [comment]
Fixed

**Comment by EStriegel** [comment]
Confirmed and closed.
