### ISSUE TITLE
Bug: Forgot Password Email text field default verbiage is incorrect.

### ISSUE THREAD

**Issue by mmurthydol** [18F/dol-whd-14c#866]
![image](https://user-images.githubusercontent.com/25183303/49395512-b39ada00-f704-11e8-917c-b37178dd2343.png)

Usually, you don’t use both form labels and placeholders with the same text. 
![image](https://user-images.githubusercontent.com/25183303/49395534-c6adaa00-f704-11e8-907b-e5eb74212441.png)

Please use text that is standardized for all text fields. (please ask Liz/Madhu for input).
Should be something like "Enter Email Address" and/or with an example. 
Ideally this pattern must be followed through out the App. But fix is for this field only. But let's discuss with Liz about the whole App if a pattern doesn't exist. @EStriegel

**Comment by NathayaMDOL** [comment]
For this issue, most of the fields are blank (no placeholder). So I decided to go with blank and make it as a standard for the whole site (remove a placeholder). The screenshot below is an example. 
@EStriegel let me know if this issue needs to apply with any text pattern in the future. 

![image](https://user-images.githubusercontent.com/40499717/49471051-dea32d80-f7d9-11e8-9ccb-a251a6250cd8.png)

**Comment by EStriegel** [comment]
@NathayaMDOL Sounds good.  Yes, let's keep this pattern in the future.

**Comment by mmurthydol** [comment]
@NathayaMDOL : How many other places are there to change in the App? If there aren't many, let's go ahead and make the change. We can discuss during stand up if there are any questions. We will add this to the other patches that I am planning for production next Monday - which means we should be done with this on Thu + testing.

**Comment by NathayaMDOL** [comment]
@mmurthydol, the fixes are already on dev. The changes are below.

1. Manage Users page: Reset password
2. Your Account page: Change password
3. Reactivate page
4. Forgot password/Reset password page

**Comment by EStriegel** [comment]
@NathayaMDOL @binwang89 
Confirmed on application pages (your account page and forgot password).  

Michelle, can you confirm on admin screens and close this story?

**Comment by binwang89** [comment]
@NathayaMDOL @EStriegel  tested in admin account for Manage user page:reset the password. 

![image](https://user-images.githubusercontent.com/25330625/49605785-767e5400-f95f-11e8-81cb-be004dd2ec04.png)

**Comment by binwang89** [comment]
@NathayaMDOL @EStriegel Reactivate the account,  please see below screenshots

![image](https://user-images.githubusercontent.com/25330625/49607692-bf84d700-f964-11e8-8cd5-c919aecadce4.png)

![image](https://user-images.githubusercontent.com/25330625/49655285-417a0c00-fa08-11e8-988b-225e236712fb.png)

![image](https://user-images.githubusercontent.com/25330625/49655367-7d14d600-fa08-11e8-886d-421314693c46.png)
