### ISSUE TITLE
Bug: 'You are already logged in' is displayed even when the user is not logged in.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#871]
'You are already logged in' is displayed even when the user is not logged in. This happens even when the user is logging in (after a long time) for the first time on a day.

**Comment by PrabhakarThummalaDOL** [comment]
Fixed.

**Comment by PrabhakarThummalaDOL** [comment]
@EStriegel 
This is fixed.

**Comment by EStriegel** [comment]
@PrabhakarThummalaDOL @mmurthydol @binwang89 

I haven't experienced this problem again, but not sure how to test.  Any thoughts, Madhu or Michelle?

**Comment by binwang89** [comment]
@PrabhakarThummalaDOL @mmurthydol @EStriegel i got this issue before and i can't reproduce the same issue anymore.

**Comment by PrabhakarThummalaDOL** [comment]
Closing the story.
