### ISSUE TITLE
Validation update: Total number of employees on work site tab on renewal application can be "0" 

### ISSUE THREAD

**Issue by NathayaMDOL** [18F/dol-whd-14c#878]
For Renewal Application: 
Under the Add Work site tab, if a user enters "0" to the question “Total number of employees..” (bottom of the below screenshot1), the system should not show an error when no employees are added on the Add Employees tab as screenshot2.  

*screenshot1*
![image.png](https://images.zenhubusercontent.com/5b2d31b202104679709f357e/9a9b441b-5a9c-44fd-a15d-8952a74b879e)

*screenshot2*
![image.png](https://images.zenhubusercontent.com/5b2d31b202104679709f357e/23d2b150-f37b-4451-a486-56b71c1d8af7)

**Comment by NathayaMDOL** [comment]
Front-end has been fixed and pushed to Dev. Please check on back-end @PrabhakarThummalaDOL

**Comment by NathayaMDOL** [comment]
related #880

**Comment by EStriegel** [comment]
Confirmed 12/17.
