### ISSUE TITLE
Validation update: API - Total number of employees on work site tab on renewal application can be "0"

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#880]
Total number of employees on work site tab on renewal application can be "0"
- [x] Add server validation to accept number of employees for a work site be 0.
- [x] Remove existing validation Rule for the Number of Employees

**Comment by PrabhakarThummalaDOL** [comment]
Fixed.

**Comment by EStriegel** [comment]
Confirmed 12/17.
