### ISSUE TITLE
Fix: Change Parent Trade Name field to an optional field

### ISSUE THREAD

**Issue by NathayaMDOL** [18F/dol-whd-14c#881]
On Employer tab --> Q: Does the Employer have a Parent Organization? Choose "yes"
Trade Name field should set to optional. Screenshot below

![image.png](https://images.zenhubusercontent.com/5b2d31b202104679709f357e/f8479794-d0a8-43bf-966a-d404fc4431c7)

**Comment by NathayaMDOL** [comment]
@PrabhakarThummalaDOL front-end has been fixed and pushed to Dev.

**Comment by NathayaMDOL** [comment]
related #883

**Comment by EStriegel** [comment]
Confirmed 12/17
