### ISSUE TITLE
Bug: IE 11 & 10

### ISSUE THREAD

**Issue by johnsonpatrickk** [18F/dol-whd-14c#89]
// IE9-11 has no method "contains" in SVG element and in Node.prototype. Bug #10259.
var jqLiteContains = window.Node.prototype.contains || function(arg) {
  // jshint bitwise: false
  return !!(this.compareDocumentPosition(arg) & 16);
  // jshint bitwise: true
};

![image](https://cloud.githubusercontent.com/assets/3799764/19811578/fc9676bc-9cff-11e6-8a67-1e91f450e5f7.png)

File: app.js

**Comment by michellewang89** [comment]
Updates - OCIO pulled the latest code and deployed to DEV, and also fixed the firewall issue. 
Retested it during the weekend 10/30, the results - 
1. Firefox is working after firewall issue has been resolved. 
2. IE 9,10 is working, but IE seems still have CITRIX issue, need to be tested from office .
3. Chrome can't be launch from Citrix, need to be tested from office.
[14c_connection_by_IE_Chrome_FireFox.docx](https://github.com/18F/dol-whd-14c/files/561046/14c_connection_by_IE_Chrome_FireFox.docx)

**Comment by michellewang89** [comment]
it seems we still have some browser compatibility issue for IE11.  for IE 9 or 10, the content will be display, but in IE11, the content still can't be loaded. 
[IE browser compatibility issue.docx](https://github.com/18F/dol-whd-14c/files/579350/IE.browser.compatibility.issue.docx)

**Comment by jmmcnj** [comment]
We have tested this in our local IE 11 - Version 11.672.10586.0, what version is DOL running/testing on of IE 11?

**Comment by rrefoy** [comment]
@michellewang89 Can you circle up with @mgwalker on this next week?

**Comment by jmmcnj** [comment]
@michellewang89 and @mgwalker was there any resolution to this issue?

**Comment by michellewang89** [comment]
DOL  IE - Version: 11.0.9600.18524/ Update Versions: 11.0.37
tested good 

![image](https://cloud.githubusercontent.com/assets/19672037/20725039/99f9f5da-b63e-11e6-84d9-9c33b796396f.png)

**Comment by oghaffari** [comment]
Note: there are a lot more issues than are captured by this story. Need to expand on this.

**Comment by binwang89** [comment]
DOL is using the DHS trusted tester process for Section 508 testing and the testing tools of Trusted Tester process is designed for IE only.   We need to make sure the 14c application can run on IE browser asap.

**Comment by mmurthydol** [comment]
@binwang89 Found a fix/workaround. IE -> Tools -> Compatibility View Settings -> uncheck "Display Intranet sites in compatibility view".

Questions: 
1) Do we need to support IE compatibility view? If so, additional work is needed. 
2) Is this setting being enforced through AD group policy? If so, ensure the above IE/workaround to unblock 508 testing.
