### ISSUE TITLE
As an Applicant, I want conditional logic to ensure I only have to complete relevant sections so that I am not confused about what sections to complete and the time it takes to complete the application is reduced.

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#9]
226 form
    1. Section 1 everyone
        a. Follow up on signature - esignature
    2. Section 2 everyone sees
        a. Except 3rd on b unless they click YES
    3. Section 3 - everyone 
        a. Lead with questions on if fields
            i. Only seen if says yes
    4. Section 4 - If YES from 3
    5. Section 5 - eveyone
    6. Section 6 - everyone, the number they put there should be linked to 226a for 5 locations, include validation to see if they match
    7. Sectiion 7 - everyone
    8. Section 8 
        a. A and b - everyone
        b. C and d - dependent on answer to b
        c. Yes to b triggers attachment on d - could be large file attachment
        d. E - everyone
    9. Section 9
        a. if they say no to 9a, skip to 11
        b. If they say yes, see how many workers in b
            i. c, questions indicate whether to show the 1st, 2nd or 3rd
    10. Section 10
        a. Only see 10 if yes to 9a
        b. A is an answer
        c. B is an attachment, different file formats
    11. Section 11
        a. If they say nom, skp to 13
        b. If yes, c is three questions
            i. Minimum of 3 on 11c
    12. Section 12
        a. Only see 12 if yes to 11a
        b. A is an answer
        c. B is an attachment
    13. Section 13
        a. If box checked then proceed
    14. Section 14
        a. If box checked then proceed
    15. Section 15
        a. Everyone
    16. Section 16
        a. Everyone on a
        b. For b, everyone shoulkd see, if they hgave a worker than they need yes/no in field

226a Form
    1. Section 1 - everyone
    2. Section 6 - mapped to Section 7 number of workers from 226 form
        3. Section 7 - should match number of workers entered and number for rows completed should match as well

**Comment by jmmcnj** [comment]
- [ ] Iteration 1 - Conditional logic flow
- [ ] Iteration 2 - informed by design and PO feedback

Acceptance Criteria: User follows flow of form as described in Description of this Issue.  Iteration 1 follows requirements above, Iteration 2 will be defined by design assets and PO feedback on Iteration 1

**Comment by EStriegel** [comment]
I think the attached will be useful in working on the conditional logic - more detailed than what is currently listed in this issue.  Let me know if you have any questions.
[14c Form Requirements & Logic.xlsx](https://github.com/18F/dol-whd-14c/files/551808/14c.Form.Requirements.Logic.xlsx)
