### ISSUE TITLE
Section14c: Database column mapping document for WH226 and WH226A forms

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#972]
- [ ] Section14c: Database column mapping document for WH226 and WH226A forms
@NathayaMDOL1

**Comment by NathayaMDOL1** [comment]
We have done it in branch "whd-aqa-972-pthummal-docs-14c-wh226-wh226a-database-mapping-document".
The file is on Dev - https://gitlab.dol.gov/whd-dev/section14c-18f/blob/dev/docs/Section14cOnline_DBColumnMapping_Ver1.0.xlsx
--

**Comment by PrabhakarThummalaDOL** [comment]
Done.
