### ISSUE TITLE
An answer of yes or no to the first question in the WIOA section creates an error message.

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#99]
![image](https://cloud.githubusercontent.com/assets/19496579/20360028/39328656-ac00-11e6-98d8-34a568d3e041.png)

![image](https://cloud.githubusercontent.com/assets/19496579/20360142/9d6bbab6-ac00-11e6-80bc-c4ec05b27a42.png)

**Comment by jmmcnj** [comment]
This was resolved in a previous build (yesterday) to the integration site, please re-test to validate that it is no longer an issue!

**Comment by EStriegel** [comment]
Yes, bug fixed!
